### ISSUE TITLE
for ABA/inventory research 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#103]
@budparr - to continue our discussion, it looks like Harvard Book Store has integrated the ABA shopping cart with their design. Maybe they redesigned with one of the ABA's templates? 
I don't know that they're using the ABA inventory for certain but I searched the same book through our website and theirs and the same list popped up. 
http://www.harvard.com/

**Comment by budparr** [comment]
Do you know anyone there?

**Comment by shuchibooksmith** [comment]
I can ask around. We're competitors, but Dana, the owner, might be able to ask...

**Comment by budparr** [comment]
Okay, no problem if not.

**Comment by budparr** [comment]
Thinking…Do you have a contact at the ABA I could speak to? Might be awkward if they're selling you a service they might feel is threatened, but ultimately would be helpful to understand the breadth of their offering. Between me and you, my personal feeling is that their overall offering is antiquated, at best, but, unless some company like Bookwitty has a compelling offering, they may be the only source of inventory for you, which is key. That begs the question. Do you have, internally, some sort of inventory report that you can output in a standard format? I'm guessing you do, but not one with the sorts of information we'd need (cover image, synopsis, etc).

**Comment by shuchibooksmith** [comment]
i'll look into this!

**Comment by budparr** [comment]
@shuchibooksmith Closing this since we're going to chat about it on Monday.
