### ISSUE TITLE
kids top 25

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#104]
here is the top 25 list for the kids section.
can it get it's own post and go on both the homepage and the kidsmith page?

Diary of A Wimpy Kid: Old School: 9781419717017
  
 Make Way for Ducklings: 9780140564341
  
 Paper Towns: 97804241934
  
 Nimona: 9780062278227
  
 Good Night Boston: 9781602190030
  
 Waiting is Not Easy: 9781423199571
  
 Book With No Pictures: 9780803741713
  
 Adventures of Beekle: 9780316199988
  
 Day the Crayons Quit: 9780399255373
  
 Very Hungry Caterpillar: 9780399226908
  
 Magnus Chase & the Gods of Asgard: The Sword of Summer: 9781423160915
  
 Wishing Spell: 9780316201568
  
 The Snowy Day: 9780670867332
  
 Home: 9780763665296
  
 Day the Crayons Came Home: 9780399172755
  
 What Pet Should I Get: 9780553524260
  
 El Deafo: 9781419712173
  
 Julia's House for Lost Creatures: 9781596438668
  
 Half Magic: 9780152020682
  
 I Will Take a Nap: 9781484716304
  
 Good Night Moon: 9780694003617
  
 I really Like Slop: 9781484722626
  
 Flora and Ulysses: 9780763676711
  
 Roller Girl: 9780803740167

Beyond the Kingdom: 9780316406895

**Comment by budparr** [comment]
No problem

**Comment by shuchibooksmith** [comment]
Thanks! And looks like the scheduling for training has worked out. Looking forward to meeting you and showing you around the store!!

**Comment by budparr** [comment]
Me too. Really glad I was able to fit in bringing my kids to Boston (and they are bookstore junkies).

**Comment by shuchibooksmith** [comment]
They'll love our kids section. If you all happen to come in on Sunday, all three kids booksellers are in that day and love giving recommendations. I don't work Sundays, but Peter will be there until 1, so you can ask for him, or ask for Amy (the kids backlist buyer) if you come in after 12:30.

**Comment by budparr** [comment]
awesome, thanks!
