### ISSUE TITLE
adjust search shop bar

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#106]
when i minimize my browsing window, the search shop bar/button disappears, just want to make sure it's always visible no matter the size of the window.

**Comment by budparr** [comment]
@shuchibooksmith FYI, I'm not ignoring this. I'm working on a redesign of the top part with that button. Though, I have gone through this at all the breakpoints and haven't seen any errors.

**Comment by shuchibooksmith** [comment]
okay! if you manually adjust the window, the search bar disappears at a weird in between point.
