### ISSUE TITLE
add february events

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#107]
@budparr  - please note i included links to the aba event page zoe created and other notes within text. let me know if you have any questions!

Monday, February 1st at 7:00pm
HEALTH/MEMOIR
Dr. James J. O’Connell
Stories from the Shadows: Reflections of a Street Doctor - http://www.brooklinebooksmith-shop.com/event/dr-james-j-o%E2%80%99connell-stories-shadows-reflections-street-doctor-author-event
book not available through the ABA, pull the cover from here: https://www.bhchp.org/stories-shadows

Dr. O’Connell’s collection of stories and essays, written during 30 years of caring for homeless persons in Boston, gently illuminates the humanity and raw courage of those who struggle to survive and find hope while living on the streets.

Wednesday, February 3rd at 6:00pm
HUMOR/FASHION
Grace Helbig
Grace & Style: The Art of Pretending You Have It - http://www.brooklinebooksmith-shop.com/event/grace-helbig-grace-style-art-pretending-you-have-it-author-event

From the #1 New York Times bestselling author of Grace’s Guide and the host of The Grace Helbig Show on E! comes a beautifully illustrated, tongue-in-cheek book about style that lampoons fashion and beauty guides while offering practical advice in Grace Helbig’s trademark sweet and irreverent voice. This is a signing-only event. Purchase of Grace & Style from Brookline Booksmith is required to attend.  

Thursday, February 4th at 7:00pm
Remembrance of Amir Aczel
Join us in a celebration of the life and work of Amir D. Aczel. Amir was an acclaimed science and mathematics writer and longtime Brookline resident. More details to come.

Friday, February 5th at 7:00pm
She Writes Press Night (bud, for the image can you grab the logo from their website?
all book titles can hyperlink to this page - http://www.brooklinebooksmith-shop.com/event/she-writes-press-night-

Join us for a night of fiction, memoir and mystery featuring four She Writes Press authors: Nina Angela McKissock (From Sun to Sun: A Hospice Nurse Reflects on the Art of Dying), Connie Hertzberg Mayo (The Island of Worthy Boys), Kate Raphael (Murder Under the Bridge), and Leah Lax (Uncovered: How I Left Hasidic Life and Finally Came Home).
all their books can link to this site on the page - 

Monday, February 8th at 7:30pmn
Book Club -  9781476731902

The Brookline Booksmith Book Club meets at 7:30pm downstairs in our Writers and Readers Room. This month we’ll be discussing The Short and Tragic Life of Robert Peace by Jeff Hobbs.   No need to sign up, just show up. To contact our moderator, email bookclub@brooklinebooksmith.com 

Wednesday, February 17th at 7:00pm
FICTION
Kristopher Jansma
Why We Came to the City - http://www.brooklinebooksmith-shop.com/event/kristopher-jansma-why-we-came-city-author-event

Kristopher Jansma’s award-winning debut novel, The Unchangeable Spots of Leopards, was praised for its  “wry humor” and “charmingly unreliable narrator” in The New Yorker and Jansma has been hailed as “F. Scott Fitzgerald meets Wes Anderson” by The Village Voice. In Why We Came to the City, Jansma offers an unforgettable exploration of friendships forged in the fires of ambition, passion, hope, and love. This glittering story of a generation coming of age is a sweeping, poignant triumph.

Thursday, February 18th at 7:00pm
Small Press Book Club

Our newest book club selects readings from independent presses. Free and open to the public, meeting the third Thursday of every month at 7:00pm. To contact our moderator, email smallpress@brooklinebooksmith.com 

Friday, February 19th at 7:00pm
Breakwater Reading Series 

Join us for a night of new stories, essays, and poems by MFA candidates from Emerson, BU, and UMass Boston. For more information, please visit breakwaterreadingseries.wordpress.com

Saturday, February 20th at 10:30am
KIDS
Storytime

Do you love picture books? Join us in our children’s section as our fine children’s team reads stories aloud every third Saturday and last Sunday of the month.

Tuesday, February 23rd at 7:00pm
NATURE/HISTORY
Lauret Savoy
Trace: Memory, History, Race, and the American Landscape - http://www.brooklinebooksmith-shop.com/event/lauret-savoy-trace-memory-history-race-and-american-landscape-author-event

Sand and stone are Earth’s fragmented memory. One life-defining lesson Lauret Savoy learned as a young girl was this: the American land did not hate. As an educator and Earth historian, she has tracked the continent’s past from the relics of deep time; but the paths of ancestors toward her—paths of free and enslaved Africans, colonists from Europe, and peoples indigenous to this land—lie largely eroded and lost. In this provocative and powerful mosaic of personal journeys and historical inquiry across a continent and time, Lauret Savoy explores how the country’s still unfolding history, and ideas of “race,” have marked her and the land. 

Thursday, February 25th at 7:00pm
POETRY
Brookline High School Poetry Fest 

Join us for the 21st annual Brookline High School Poetry Fest, as the budding young Poets of Brookline grace our podium.

Sunday, February 28th at 10:30am
KIDS
Storytime

Do you love picture books? Join us in our children’s section as our fine children’s team reads stories aloud every third Saturday and last Sunday of the month.

Monday, February 29th at 7:00pm
FICTION
Dawn Tripp
Georgia -  http://www.brooklinebooksmith-shop.com/event/dawn-tripp-georgia-author-event

In 1916, Georgia O’Keeffe is a young, unknown art teacher when she travels to New York to meet Stieglitz, the famed photographer and art dealer, who has discovered O’Keeffe’s work. Their connection is instantaneous. O’Keeffe is quickly drawn into Stieglitz’s sophisticated world, becoming his mistress, protégé, and muse, as their attraction deepens into an intense and tempestuous relationship and his photographs of her, both clothed and nude, create a sensation. A breathtaking work of the imagination, Georgia is the story of a passionate young woman, her search for love and artistic freedom, the sacrifices she will face, and the bold vision that will make her a legend.

**Comment by budparr** [comment]
But why in two places? That's generally an SEO no-no.

**Comment by shuchibooksmith** [comment]
hm yes i see what you're saying. @zchyde can maybe jump in here, but i think the idea is that this particular listing includes event information in case people want to preorder. but yeah maybe we can just forgo it entirely, maybe only use it for the events where people have the opportunity to purchase a bundled ticket + book. @zchyde thoughts?

**Comment by shuchibooksmith** [comment]
@budparr, is it possible to get these up today? if you'd prefer, you can just skip out on linking to the ABA pages zoe created, and we can discuss that later. the events do need to go up asap. and i have some additions and corrections which i'll soon post.

**Comment by budparr** [comment]
Oh, okay. Didn't realize they needed to be up right away (good thing you said something because I was going to save some of them for training on Mon.). Just let me know when your changes are up and I'll put them up.

**Comment by shuchibooksmith** [comment]
1/31 Storytime- “Join us for a special Storytime with Keith Cohen and Roberta Paul, the local author and illustrator of the picture book Henry and Lola: A Puppy Love Story.”
 
2/5 She Writes Press- Leah Lax is no longer part of the event.
 
2/10- NEW Event Addition (please make a poster, Zoe)
 
Wednesday, February 10th at 7:00pm
FICTION
Roger Rosenblatt
Thomas Murphy (9780062394569)
 
Roger Rosenblatt, the award-winning essayist and New York Times bestselling author of Making Toast, returns to fiction with this reflective, bittersweet tale that introduces the irrepressible aging poet Thomas Murphy. An Irishman, a dreamer, a poet, Murph, like Whitman, sings lustily of himself and of everyone. Through his often-extravagant behavior and observations, both hilarious and profound, we see the world in all its strange glory, equally beautiful and ridiculous. Behold the charming, wistful, vibrant, aging Thomas Murphy, whose story celebrates the ageless confusion that is this dreadful, gorgeous life.

**Comment by budparr** [comment]
Got it. working on them now.

**Comment by shuchibooksmith** [comment]
and last one 
Wednesday, February 3rd at 6:00pm
HUMOR/FASHION
Grace Helbig
Grace & Style: The Art of Pretending You Have It - http://www.brooklinebooksmith-shop.com/event/grace-helbig-grace-style-art-pretending-you-have-it-author-event

From the #1 New York Times bestselling author of Grace’s Guide and the host of The Grace Helbig Show on E! comes a beautifully illustrated, tongue-in-cheek book about style that lampoons fashion and beauty guides while offering practical advice in Grace Helbig’s trademark sweet and irreverent voice. This is a signing-only event. Purchase of Grace & Style from Brookline Booksmith is required to attend.

**Comment by budparr** [comment]
the copy changed on that one?
