### ISSUE TITLE
Fix newsletter sign-up

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#108]
A customer tried to sign up for our newsletter and it took them to an NYU page and to a mailchimp email list?

**Comment by budparr** [comment]
Oh, crap! I must have mixed up another client's code. I'll fix it right now.

**Comment by budparr** [comment]
Should be up in a couple of minutes. I'll log in to their account and see if I can get a sense of anyone has erroneously signed up for their list. Not one of my finer moments :(

**Comment by budparr** [comment]
Was the email of the person who told you this nssotomayor@gmail.com

**Comment by shuchibooksmith** [comment]
nope, wasn't her - we got the name of the person who notified us and already added them. thanks!
