### ISSUE TITLE
edit february events 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#109]
2/1 Dr. James O’Connell- Add: *appearing in conversation with James Parker. Final line (in bold): “James Parker is a contributing editor for The Atlantic and the editor of The Pilgrim, a literary magazine written by Boston’s homeless.”

**Comment by shuchibooksmith** [comment]
2/5 has the wrong covers for the event. The books are correct. The covers are not.

**Comment by budparr** [comment]
Oh, can you point me to the right covers? I got those from the brookline page http://www.brooklinebooksmith-shop.com/event/she-writes-press-night

**Comment by shuchibooksmith** [comment]
Sorry about this! Here's the one to use - 
http://www.brooklinebooksmith-shop.com/event/she-writes-press-night-0
