### ISSUE TITLE
pull down holiday gift guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#112]
the holiday gift guide posts should be pulled down from the homepage and from the main menu, but still stay up on the blog. thanks!

**Comment by budparr** [comment]
Hi @shuchibooksmith - sorry not following you. Right now the HGG posts show up on the home page, the blog page and the HGG landing page. The home page posts have nothing to do with categories, just time, so as new posts are added the HGG will only be on the HGG landing page and the blog page. Let me know what part I may not be understanding.

**Comment by shuchibooksmith** [comment]
i think pull down was the wrong action for that. marshall (the owner) doesn't want the holiday gift guide featured so prominently on the website - it makes it look outdated. and he feels pretty strongly about it. we still want it on the website, but not so prominently featured. so, no longer in the main menu, and not on the homepage, but have it only show up in the blog. is that possible?

**Comment by budparr** [comment]
Makes perfect sense now. I took it off the menu. I made a temporary fix to remove that category of post from the home page.
