### ISSUE TITLE
Zoe Training - events on homepage

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#114]
HI! i remebered my github password. 

How do I get rid of the events on the homepage after they have happened? 

Thank youuuu

**Comment by budparr** [comment]
Hi @zchyde Awesome. Every time you change something on the site the home page refreshes. I'll see if I can come up with something that refreshes it once a day or something to make sure events to hang out there too long.

**Comment by peterbooksmith** [comment]
Hello,

&nbsp;

I will be away from the bookstore at Winter Institute from January 22-26.&nbsp; While I will be checking emails, please contact the store at 617-566-6660 if you need assistance.

&nbsp;



Peter Win

Assistant Manager / Co-owner

Brookline Booksmith

279 Harvard Street

Brookline, MA 02446

617-566-6660
