### ISSUE TITLE
add header for events listings on homepage

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#115]
i know we talked about this previously, i just can't find the thread.
i don't think we want headers like we do on the kidsmith page.
thoughts on just having a header for upcoming events, but shifting the list down so that the header Upcoming Events lines up with the top of the most recent blog post?

**Comment by budparr** [comment]
Okay. Let's shelve this just for the moment. I'm re-working the top-nav banner area, then will address the body area just after.

**Comment by peterbooksmith** [comment]
@budparr - could this be revisited/taken care of soon?  Dana and Marshall have asked me more than once about having "Upcoming Events" on the home page, and I have told them it is in the works.   I know you are still probably playing catch up from your move, so just recognizing that.  Thanks.

**Comment by budparr** [comment]
Sure, except, I think the headers should be consistent throughout the site. You said you didn't want headers like on the kidsmith page, so I'm not sure really what to do there.

**Comment by peterbooksmith** [comment]
I don't know either, but we have to do something.  If it just said Upcoming Events in the same font as the kidsmith headers but without the underline, would that look terrible?  Of if it should totally consistent, with the underline.  I know I am countering what Shuchi said above, but I am again trying to manage and work with what the others owners want.

**Comment by budparr** [comment]
Well I'm fine with putting the headers there as the kidsmith page. That was my original suggestion. Let's put it up in the same manner and at least you'll have something and we can change it if need be.

**Comment by shuchibooksmith** [comment]
Maybe we can put it up but without the underline?

**Comment by budparr** [comment]
Then I should take the underline off of the kidsmith page as well. I put the underline there because text alone can easily get lost with a lot of things on the page and to make it clear that it's a heading. I'll take it off though, just as long as we're consistent throughout the site.

**Comment by shuchibooksmith** [comment]
Hm okay. I didn't love the underline, but that was a personal preference. If you think it's better with then go for it. And we'll do the same thing consistently throughout with the kids page.

**Comment by budparr** [comment]
I tried with and without the lines and it really needs them. However, I toned down the colors a bit. http://bbs160229v1.surge.sh/

**Comment by shuchibooksmith** [comment]
oh i like that! i think the "Featured" font size might be a point smaller than "Upcoming Events" other than that it looks good! 
And I like "Featured" better than "Blog Posts" too, so thanks for thinking of using that word instead!

**Comment by budparr** [comment]
The point sizes are precisely the same.

**Comment by shuchibooksmith** [comment]
HA. okay. my bad. thanks!

**Comment by budparr** [comment]
No prob.
