### ISSUE TITLE
Add an event

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#118]
This is a late addition to the events page, could it go up asap?  This is all the info I have:

Friday, February 26th at 7:00pm
James Geary
Short Flights: 32 Modern Writers Share Aphorisms of Insight, Inspiration and Wit
 
To celebrate the publication of Short Flights: 32 Modern Writers Share Aphorisms of Insight, Inspiration and Wit, James Geary, author of the New York Times bestselling The World in a Phrase: A Brief History of the Aphorism and a contributor to Short Flights, presents 'Juggling Aphorisms', a talk/performance exploring the power of wit and aphorisms in literature and daily life through the lively juggling of words, ideas—and balls—and lots of audience participation, including a pun competition!

**Comment by budparr** [comment]
Sure, @peterbooksmith what's the isbn for the book?

**Comment by budparr** [comment]
and the category (e.g. "fiction")

**Comment by peterbooksmith** [comment]
The isbn is:  9781936182886

category is: Essays

thank you

**Comment by budparr** [comment]
All set. Have a great day!
