### ISSUE TITLE
weekly bestsellers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#119]
hi bud! zoe is out this week, can you update our weekly bestsellers for us this week?

this is for the kids team-
1. Five Minute Star Wars Stories - 9781484728208
2. Where The Wild Things Are - 9780064431781
3. Auggie and Me - 9781101934852
4. My Crazy Inventions Sketchbook - 9781780676111
5. Diary of a Wimpy Kid Madlibs - 9780843183535
6. There is a Bird on Your Head - 9781423106869
7. Big Guy Took My Ball - 9781423174912
8. Elephant and Friends - 9781438005270
9. Make Way For Ducklings - 9780140564341
10. Julia's Home For Lost Creatures - 9781596438668

**Comment by shuchibooksmith** [comment]
i'll send along the adult bestsellers shortly

**Comment by budparr** [comment]
Sure
