### ISSUE TITLE
Blog Posts

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#12]
-the backlog of posts on blogger, can we still access them?
-can each post be dated in the card format?
-can we create a separate card for alerts (if the store is closing early or we have special hours)

**Comment by budparr** [comment]
> can we create a separate card for alerts (if the store is closing early or we have special hours
This is interesting and something I've thought about. I think it should probably be separate from blog posts, though.

**Comment by shuchibooksmith** [comment]
yes, agreed!

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GtJhCafl&#x2F;7-create-blog-post-archive"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Create blog post archive</a>

**Comment by shuchibooksmith** [comment]
i had a chance to peek at the website when it was in transition, before richard switched it back. one thing i noticed is that the homepage didn't include the most recent blog posts, only the posts it has been showing in the various demos (from end of august). how will that work for monday?

**Comment by budparr** [comment]
Good point. I'll start getting them in over the course of the week; when we initially went to see if we could import from blogspot, my developer on that told me it wasn't possible, but I'll revisit it. As for Monday, I think the most important thing is the newest posts, being the holiday gift guide.

**Comment by shuchibooksmith** [comment]
okay sounds good, thanks!

**Comment by budparr** [comment]
@zchyde - my colleague once asked you to send us an export of the blogspot blog. Could you do that again, please? You can then just upload it here.

Thanks!

**Comment by budparr** [comment]
@zchyde @shuchibooksmith The blog posts are in. There are still some that are funky and I next need to link up the staff.

**Comment by budparr** [comment]
FYI, though - I'm going to chip away at a few other issues before I go back to the blog posts, since that import took so long (feel like there are other things that need my attention).

**Comment by shuchibooksmith** [comment]
@budparr I was so excited to see all the blog posts up! Thank you.

**Comment by budparr** [comment]
Thanks @shuchibooksmith - I still have some work to do on some of them (like assigning authors), but I'll start to tackle them next week when I'm back to work (on a light schedule this week with the kids home).

**Comment by shuchibooksmith** [comment]
Absolutely @budparr! A lot of catching up for me this week too. I had sent you an email about connecting over the phone but lets do that when you're back in the office next week. 
Enjoy your time at home!
