### ISSUE TITLE
add social media share buttons to author events

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#122]
pretty self explanatory - we just want authors to be able to share their event listing on social media platforms.

**Comment by budparr** [comment]
How about I add them to the individual event page? I can add them to the listing pages, but they'll get quite busy along with the add to calendar stuff. Just trying to keep things clean and simple

**Comment by shuchibooksmith** [comment]
okay! i think that should be fine. if people feel strongly otherwise, we'll revisit. thanks!
