### ISSUE TITLE
add button for pre-order harry potter

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#125]
so we're going to be offering those who want to pre-order the new harry potter a 20% discount. we need this to live somewhere on the homepage, but the thing is that it needs to stay fixed on the homepage for the next several months - until the release party on july 30th. i'm wondering if this can live on the sidebar - maybe on the unoccupied white space. not that i want to start using that white space regularly but this seems like an exception. thoughts?

**Comment by shuchibooksmith** [comment]
i should mention this is kind of a priority! we're working on the aba side of it to so that we can get it going asap. thanks @budparr!

**Comment by budparr** [comment]
When exactly, do you need it up?

**Comment by shuchibooksmith** [comment]
as soon as sometime tomorrow, end of the week at the latest. richard needs to make the book available to order on the aba site first and then we're ready to go after that.

**Comment by budparr** [comment]
Let me know as soon as you have it ready, please.

**Comment by shuchibooksmith** [comment]
will do, thanks!

**Comment by peterbooksmith** [comment]
@budparr the Harry Potter is all set on our indiebound site now.

http://www.brooklinebooksmith-shop.com/book/9781338099133

**Comment by budparr** [comment]
Hi @peterbooksmith and @shuchibooksmith - I've been without internet all day (just moved today). I put something up. Let me know if you think it's too much. I can also make it only show this way the first time anyone comes to the site, but then also have a more subtle button down on the page. I think that might be the best way, but welcome your input. I'll be slow to respond over the next day or so as we unpack.

**Comment by shuchibooksmith** [comment]
Hi @budparr! Thanks for putting this up so quickly! 
What are your thoughts on making this a version of the post, so that it's the first item in the list of posts. But maybe it could be a pinned post, for now, like Twitter? 
For now this is good, until you have time to handle. The alert bar does disappear when I navigate away from the site. Maybe for now can we keep it fixed on there until you have more time to go over it?

**Comment by shuchibooksmith** [comment]
Okay so we do want to change this to more of a button or something a little bit more discreet, perhaps with the image of the book cover. Thoughts of putting it on the lefthand white space on the homepage? the space to the left of the blog posts?

**Comment by budparr** [comment]
I'll think of a solution and send you an example when I've got it worked out. We're using the pinned posts now for something [else](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/128).

**Comment by shuchibooksmith** [comment]
right, pinning the post won't work now. 
thanks!

**Comment by budparr** [comment]
I left the HP topbar up, but made it gray. What do you think of that?

**Comment by peterbooksmith** [comment]
I am not seeing it at all right now, but regardless - at some point we want to have something using the cover image for the Harry Potter book.  It is distinctive and people will look for it.  I can provide examples if needed.  I do not have a specific suggestion as to how to do this on our site or where to do it.

**Comment by budparr** [comment]
It goes away after repeated viewings so as not to annoy users. I'll work up something new.

**Comment by shuchibooksmith** [comment]
Yes, what @peterbooksmith said. Because this book is a special case (we never do pre-orders like this or midnight release party), I was thinking it could be somewhere down near the blog posts, to the right or left or maybe smaller and above the events list.

**Comment by budparr** [comment]
There's no room to the right or left. We can certainly put it above events, but note that some people will not notice the events in that case. If you must have the entire cover though, that's really the only solution.

**Comment by zchyde** [comment]
Ok, what about something like this, mirroring the dimensions of the blog post image height and the events sidebar width. Also I did this fast so don't judge me that this looks like garbage.org . 

![hideouslol-compressor](https://cloud.githubusercontent.com/assets/15219441/13406697/e256a1ee-def2-11e5-8b1d-43bc5e5aadaf.jpg)

**Comment by budparr** [comment]
Do you need the entire book cover in the image, or no?

**Comment by zchyde** [comment]
I think the answer will be "yes" to needing the entire book cover image.

**Comment by zchyde** [comment]
k did not have to say that so crazy

**Comment by zchyde** [comment]
doing an awesome job over here

**Comment by zchyde** [comment]
I could make a graphic if need be

**Comment by budparr** [comment]
Can you drop in here some hi-res cover art for the book?

**Comment by zchyde** [comment]
yes please hold

**Comment by zchyde** [comment]
Do you want them compressed or just natural

**Comment by budparr** [comment]
uncompressed is fine

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child](https://cloud.githubusercontent.com/assets/15219441/13406895/ddd59944-def3-11e5-881d-55c63b1640bb.png)

thats the cover

**Comment by budparr** [comment]
How about using this?

![harry-potter-and-the-cursed-child-artwork](https://cloud.githubusercontent.com/assets/115347/13407048/94783080-def4-11e5-933d-9c4d81d7080b.jpg)

**Comment by zchyde** [comment]
That looks really good and I like that better, but I have a feeling that we will get the note asking us to make it the full book cover :(

**Comment by zchyde** [comment]
thats just my instinct

**Comment by budparr** [comment]
Then it's just going to be the cover and some copy next to it, really.

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13407418/5958c4b8-def6-11e5-842c-ce1da96e2e89.png)

Maybe this?

**Comment by budparr** [comment]
That's fine. Can you do a bit of drop-shadow on the cover and maybe make the copy stand out a bit more?

**Comment by zchyde** [comment]
yes one moment

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13407805/43529ec6-def8-11e5-8cb1-5c98760db4b4.jpg)

Is that better? I can add a bit of a square behind the copy if it needs to stand out more

**Comment by budparr** [comment]
Actually, I think the color was fine. What I really meant was to give it like very subtle inset drop-shadow just to make it stand above the background. I also think it needs to be a bit smaller (Can we remove "Parts 1 & II"?) with greater line-height. It's a bit in-your-face.

**Comment by zchyde** [comment]
![itgood](https://cloud.githubusercontent.com/assets/15219441/13411007/ddf64aa8-df08-11e5-85b9-74b01fc2c30d.jpg)

Like this? Sorry, I'm half here, I moved offices today and theres like 60 things in my head.

**Comment by budparr** [comment]
Better. Can we nudge the text to have a bit more leading? Imagine you're whizzing by this in your Facebook feed; that's about the amount of time you get to make an impression. Wondering, since the title is prominent, we deemphasize the title more and emphasize the discount more. Or, does the discount not much matter. Aren't you having a party for it? Maybe that should be on here?

**Comment by zchyde** [comment]
We are having a party for it, I dont know if we want that on here? I can ask shuchi. 

I tried to think about what would be eye catching wizzing by a facebook feed, this seems like maybe overkill but I do think it would be effective? 
![omg](https://cloud.githubusercontent.com/assets/15219441/13411417/e5371ee4-df0a-11e5-955f-3142cd380074.jpg)

**Comment by zchyde** [comment]
maybe "BUY NOW" is too aggressive

**Comment by zchyde** [comment]
"BUY HERE"?

**Comment by budparr** [comment]
Yeah, I agree. Perhaps "buy..." is implicit? (I'm no marketer though)

**Comment by budparr** [comment]
I think the typeface for the copy needs to be either more like the site font or the book font, likely the book font.

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13432678/adf02420-df9c-11e5-8c09-945e8f6d81aa.jpg)

Ok so, I changed the typface of the actual book to mirror the serif of the title on the cover, and the rest of the type is chronica. I think we should do all chronica or this, an all-serifed look was ghastly. I also took out "Buy now" and put in "at brookline booksmith" because it mentions our name and prompts to click for more.

**Comment by budparr** [comment]
I love it! (you're good at this). I'm not entirely sure about the yellow, but I think we put it up on the site and see how it fits in. Be back in a bit on that.

**Comment by budparr** [comment]
Looking at the full-sized version: Do you know how to do "Gaussian" blur? I think the background needs it , just a bit. And the copy is a bit blurred. You can send me your mechanicals if you like.

**Comment by zchyde** [comment]
I didnt save it an its fullest res but I can, I know warmer colors = more artifacts and blur. I do know about gaussian blur, I can throw that on there

**Comment by budparr** [comment]
awesome thank you

**Comment by budparr** [comment]
And, fwiw, the topbar has had nearly a 2% conversion rate with 78 clicks (I'm not sure if that's after I made the color more subtle). Those are good numbers.

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13433334/54c98410-df9f-11e5-9ccf-aa9e79189478.jpg)

slight blur really makes the features stand out, thats cool
if I dropbox you the .psd will that be sufficient for you to make changes?

**Comment by budparr** [comment]
Yeah, but if you just want to send me a hi-res version, that's fine too. (and I think you can drop psd here on github too.)

**Comment by zchyde** [comment]
Good to know about the topbar, maybe we can convince the upper ech to let us use it for something else in the future
I think its a pretty effective mechanic but I do think its just too next level for our powers that be...still, not ruling it out entirely

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13434078/a6bc3ada-dfa2-11e5-9362-3ddb74d8be7d.png)

thats a .png, tried to drag and drop. psd but no go - I will drop box it. I gotta swtich to updated the bestsellers now or I'm definitely going to get A CALL. Bbs

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13434139/d0ac0668-dfa2-11e5-85cf-27ea0867ad6b.png)

**Comment by zchyde** [comment]
![harry-potter-and-the-cursed-child-2](https://cloud.githubusercontent.com/assets/15219441/13434268/38440154-dfa3-11e5-92dc-808f4a99d38b.jpg)

**Comment by zchyde** [comment]
![hp_graphic_xl](https://cloud.githubusercontent.com/assets/15219441/13435521/b6c1f068-dfa8-11e5-8429-3298f4fad321.jpg)

**Comment by zchyde** [comment]
github will not let me drag .psd so I am putting it in the dropbox now

**Comment by zchyde** [comment]
jic

**Comment by budparr** [comment]
That last image was good. Removing the gold leaf was a good move - reducing the clutter of the image. 

In addition to adding it to the site, I've given you some flexibility here:
- Created a content section called "campaigns" so you can control these in the future, including ending this one, or adding new ones, or changing the image for this one yourself.
- Made it flow for mobile on the home page - so on mobile the campaign comes up first, but on desktop it's over to the right.

**Comment by budparr** [comment]
I'm going to close the issue, but let me know if you have any questions, issues. You should be able to change the image, or whathave you on your own, but let me know if you need any help with that. 

If you do, just make sure you follow best practices on image compression, etc. I think I made that image 700px wide to accommodate some screens.

**Comment by budparr** [comment]
Also note that I put some parameters on the link for tracking purposes (the parameters will show up on google analytics), and it's a good idea to do that too when you create new campaigns. 

This is the link: http://www.brooklinebooksmith-shop.com/book/9781338099133?utm_source=internal&utm_medium=website&utm_campaign=harrypotter-2016

And this is how you get the URL: https://support.google.com/analytics/answer/1033867?hl=en#using_the_url_builder
