### ISSUE TITLE
change url for search button

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#126]
currently our search button goes here- http://www.brooklinebooksmith-shop.com/search/site
we'd like it to go here instead - http://www.brooklinebooksmith-shop.com/
thanks!

**Comment by budparr** [comment]
@shuchibooksmith Do you mean the "Search our Online Shop" button?

<img width="294" alt="screen shot 2016-02-23 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/115347/13264711/7eb75746-da3d-11e5-8938-72fa2230479d.png">

**Comment by shuchibooksmith** [comment]
@budparr yup! the red button.

**Comment by budparr** [comment]
Okay. So that has to go to the search page; otherwise it won't actually show any search results. We could just make it a button and not have search at all, but that's the only way.

**Comment by shuchibooksmith** [comment]
ahhh okay i see. what if next to the search bar we had a magnifying glass and that will function as the return button? then we can get rid of the current red button.

**Comment by budparr** [comment]
That's great. I seem to recall having it that way when we launched the site and was asked to put the big button there.

**Comment by shuchibooksmith** [comment]
yes! you're right. we did that because there was an initial panic around the holiday season, but hopefully people are used to the site enough now that they'll figure it out. let's go for it! i'd love to get rid of the big red button, personally.

**Comment by budparr** [comment]
Okay.

**Comment by budparr** [comment]
And, I agree. Really dislike that button!

**Comment by peterbooksmith** [comment]
@budparr sorry to reopen this, but could you make the search button have some red on it like on this page for example - http://www.harvard.com/index.php?/

I can explain to others here that is a standard search button, but I am concerned that no color at all will not be obvious enough for everyone's liking.

**Comment by peterbooksmith** [comment]
@budparr sorry to reopen this, but could you make the search button have some red on it like on this page for example - http://www.harvard.com/index.php?/

I can explain to others here that is a standard search button, but I am concerned that no color at all will not be obvious enough for everyone's liking.

**Comment by budparr** [comment]
Red there makes it an anti-pattern (red is a signal of an error). I'll see what I can come up with. What is your goal with having it stand out so much? If it's that important, perhaps we should do something with it other than just give it color.

**Comment by peterbooksmith** [comment]
It just seems like many bookstores have a red button.  Another color would be fine, but I don't think the current version stand out enough.  The reasoning is - you and I know that is the search button.  Many other people would know that is the search button, but not everyone.  Not everyone who works here knows it, so the thinking is not everyone looking at our website would know.  Just trying to account for that, because I know that is what some people here will say.

**Comment by shuchibooksmith** [comment]
Hm, yeah I don't know if red is right, but the search window was white before and that was a little bit easier to see. Maybe having the magnifying glass, search button outside of the search box would help? To the right of the box maybe?

**Comment by budparr** [comment]
I'll come up with something
