### ISSUE TITLE
Blog Post Image Issue - Larger Images Needed

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#127]
Sooo, one of our bloggers creates page-sized comics featuring herself as a stick figure character. Previously, we were posting these on the blog, and we are going to start posting them on the new site's blog posts. However, as things are right now, I can only upload images that are ~250x250 or so. We would need a much larger image in order to allow the comic to be read, maybe something that's almost as wide as the middle box. The images would be large but they're not very complex, literally black and white stick figure comics that are scanned in.

**Comment by budparr** [comment]
contemplating how best to do this. I can easily give you another field for that image, but just making sure that's the only/best way to do it, because I always try to consider carefully when adding new fields.

**Comment by budparr** [comment]
There's now a checkbox below the featured image that says "Show Featured Image in Post," which will do just that. I also left the featured image up on the hero, because it often looks like an abstraction anyway. Let me know if that all works for you.

**Comment by zchyde** [comment]
We testing this today, looked good to me. Excellent work
