### ISSUE TITLE
Pin blog post

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#128]
Looks like we want "this week in books" blog posts to be pinned to the top of the blog feed. I told them I could do this but I think I may have lied - can you put that functionality in? Maybe like a "actual date" vs "posted date", and then I can just make the actual date like 1000 years in the future?

**Comment by zchyde** [comment]
..maybe that didnt make sense...

**Comment by budparr** [comment]
No problem. I'll take care of it.

**Comment by peterbooksmith** [comment]
Thanks @budparr  - just FYI, this came about b/c Dana and Lisa and Marshall would like to see a consistent blog post about book and book-industry related topics.  A new one will be done weekly and we want to try having it live in that top spot.  Along with that, Shuchi has organized our bloggers and we will have more posts coming very soon, which will fill in the other spots under "This Week in Books".

**Comment by budparr** [comment]
@peterbooksmith and @zchyde 

Options:
1) I give you a box to check to pin a post to the top by checking it.

2) I automatically pin the latest "this week in books" post to the top automatically. 

I tend to prefer option #2 because it's always best to keep fields limited. You'd want option 1 if you want to pin posts of other types.

Let me know and I'll implement right away.

**Comment by peterbooksmith** [comment]
@zchyde  - you should make the call on this, as you are doing the work.  I am inclined to agree with Bud, though I could see us wanting to pin a different post to the top for a while.  Maybe it is just easier to set up that functionality now.

**Comment by zchyde** [comment]
My instinct is to follow Buds advice and only pin the "this week in books" posts, but this will mean we are limited in what we can post to the top. I think this limitation is good, but if we want a "this week in books" post pinned to the top every week, then we won't be able to pin other posts anyway, as to pin anything but 1 post to the top would be way too confusing.

But I am almost certain that if we set up option 2, then we'll be back eventually, asking Bud to widen the parameters on that option so we can pin another type of post to the top. So I suppose we want to go with option 1, because I have a feeling that there will be other things we want to pin to the top in the future.

**Comment by zchyde** [comment]
Sorry I pressed the wrong thing :) :) ;)

**Comment by budparr** [comment]
When you make a new post you'll see a "Featured" checkbox just below published checkbox. That will pin that post to the top on the home page (not the blog page). 

Let me know if you have any issues!
