### ISSUE TITLE
add bookseller names for blog

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#129]
i know we're still figuring out staff pages, etc, but is it possible to get some other names added to the blog list?

**Comment by budparr** [comment]
Sure, just add them to the "staff" collection in the CMS.

**Comment by shuchibooksmith** [comment]
@zchyde is this something you can do? if so i'll email you the list of people to add.

**Comment by zchyde** [comment]
new names have been added
