### ISSUE TITLE
Gift Guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#13]
What we need from you: deadlines for us to get you the content. 

Here is the important information:
Dates for email blasts:
Monday, Nov 23rd 
Wed, Dec 2nd
Wed, Dec 9th
Wed, Dec 16th
Monday, Dec 21st
Wed. Dec 30th

categories:
-kids
-cookbooks
-travel & place (to include travel, landscape photography, nature)
-art & design (to include art books, coloring books, but also architecture, etc)
-literature (i don't love the heading for this, maybe we can think of something better, but this would be the books for book lovers - the complete primo levi, for example.)
-mindfulness/home (for the December 30th blast, the week before christmas and new years)

For reference, here is an example from last year's gift guide: 
http://brooklinebooksmith.com/giftguide2014/cooking.html

**Comment by budparr** [comment]
Do you have the content for them all at once, or just before the dates they're going out?

**Comment by shuchibooksmith** [comment]
We don't have the content yet. Over the next couple of weeks we'll select the books. Then the write-ups for the books will probably come after, in a couple of big chunks, along with the gift photos and write-ups. In the past, we've uploaded the content into the blast at least a week or two before it goes out. This is of course how we handle it here, doing everything haphazardly and at the last minute. If we have to get it to you guys first, we can work with firmer dates and deadlines that fit with your schedule.

**Comment by budparr** [comment]
What does the blast look like? That is, on the backend. Is it constant contact? Do you enter the content into a WYWIYG editor at their site?

**Comment by zchyde** [comment]
Yes. The backend of the blasts are html and internal css. They're usually pretty simple, and the gift guide ones look exactly like the site, same graphics and colors, etc.

**Comment by shuchibooksmith** [comment]
For the gift guide banner, I think we're going to be going with something illustrated - would that be alright? We're going to have the woman who handles the chalkboard design for the gift room send us some images. Thoughts on that?

**Comment by budparr** [comment]
That's sounds great! You see on the about-us page my attempt at creating an illustration look from a photograph, which I think is a good idea too, but in more capable hands (graphic design is not my thing).

**Comment by shuchibooksmith** [comment]
Yes! I LOVED that in the About Us page - it gave it a nice retro look, which works for a page that is about our history.

**Comment by zchyde** [comment]
Hi Bud,

While I was putting together the gift guide newsletter today, I put this functionality in (even though its too complex for a newsletter) and I showed it around and I think we're interested in maintaining it, its the hover scale on the book pages. I don't know how you want to go about that, but if you want to set it up and I can put the images in thats fine, whatever works for you.

http://www.brooklinebooksmith.com/GG2015/kids2015.html

**Comment by zchyde** [comment]
in case you're wondering I just picked pink as a basic non denominational-yet-close-to-red color, I have no special connection to it and will change it when we get that banner that's being designed for us.

**Comment by budparr** [comment]
I'll check it out.

**Comment by shuchibooksmith** [comment]
will we wait until we have content for the gift guide to go live?

**Comment by budparr** [comment]
who are you asking, @shuchibooksmith ? Are we doing the gift guide as posts, just like we talked about with the other sections, specifically the newsletter/ubc?

**Comment by shuchibooksmith** [comment]
hi @budparr asking you, yes!
we aren't doing the gift guide as posts. each featured area would need it's own list. so the content portion for each section will look something like this (as far as how it's listed)
kids - http://www.brooklinebooksmith.com/giftguide2014/kids.html
cooking - http://brooklinebooksmith.com/giftguide2014/cooking.html
travel & nature - http://www.brooklinebooksmith.com/giftguide2014/travel.html
etc for art & literature and mindfulness and home

so we need a way to jump to each featured section within the gift guide page.

does that make sense? what do you think?

**Comment by budparr** [comment]
Yes, but is there one gift guide per section, or several? I'm still inclined to make them posts, partly for consistency and partly because they are, essentially, date-based, but I'll think about the best way to do that. And no problem on shifting between them - I'll figure something out.

**Comment by shuchibooksmith** [comment]
Hm so it's one gift guide per section. So cooking contains 6 books, with covers and blurbs, and then about 4 books that we suggest, and that is just images, and then underneath that, there's a gift portion with all the cooking related gift items. Ideally, on the gift guide landing page people could see all of the categories and click on them. So, yes - I think that could work as posts!

**Comment by shuchibooksmith** [comment]
Here are the write-ups for the Kids Books email blast which is going out on Monday-

PICTURE BOOKS
INTERSTELLAR CINDERELLA by Deborah Underwood, illustrated by Meg Hunt 
ISBN 9781452125329
This spirited retelling retains Cinderella's classic structure, but capable mechanic Cinderella meets the prince when she repairs his spaceship, and she loses a wrench instead of a glass slipper. The illustrations swirl and sparkle through the cosmos. Read-aloud friendly rhyming text carries everyone to a happy ending: Interstellar Cinderella is too young for marriage, but she's old enough to be the royal chief mechanic! A great fit for fans of princesses and Rosie Revere, Engineer.
 
SING A SEASON SONG by Jane Yolen and illustrated by Liesl Ashlock 
ISBN 9781568462554
Jane Yolen's quiet lullaby, set to the rhythm of the changing seasons, explodes into brilliant full color in Ashlock's sharply detailed illustrations. As plants and animals of the woods and fields traverse the year, you can also catch glimpses of a few far-off children—the natural world is always close by, if you're willing to look. The story starts and ends in snug and sleepy winter, while vibrant images of summer will be especially welcome on cold nights.

ZEN SOCKS by Jon J Muth
ISBN 9780545166690
Sometimes, if we stop and listen, our friends can give us the best advice. With gentle watercolor illustrations and whimsical characters, Muth perfectly captures quiet moments of friendship, and reminds us that rushing won’t get us as far as we think, and perseverance can lead us through even seemingly insurmountable tasks.

ROBO-SAUCE by Adam Rubin, illustrated by Daniel Salmieri
ISBN 9780525428879
What could be better than a book that TRANSFORMS?! Into a ROBOT no less?! Rubin and Salmieri really hit it out of the park with this one! A wickedly clever (make sure you read all the fine print and details!), robot romp that captures the heart of the imagination and proves that we are still kids at heart. After all, who could be too old for cardboard robots?

LITTLE ELLIOT, BIG FAMILY by Mike Curato 
ISBN: 9780805098266
A sweet and heartwarming follow up to Little Elliot, Big City. When Mouse leaves for a family reunion Elliot feels left behind. But before long Mouse comes back for him and brings him a surprise. With his signature whimsy, Curato looks at how sometimes family finds you when you need them most.

JACK FROST (The Guardians of Childhood) by William Joyce
 ISBN: 9781442430433
Yet another beautiful installment in Joyce's Guardians of Childhood series. To keep the lonely cold inside him from taking over Jack spreads it to the landscape instead until one day he learns that bringing joy to others is another way to keep himself warm. Jack Frost is a gorgeously illustrated look at the power of helping others and the bravery that it sometimes takes.

Honorable Mentions:
HarperCollins Treasury of Picture Book Classics (various) 	ISBN 9780062427250
Magical World of Strega Nona by Tomie de Paola 	ISBN 9780399173455
Lizard From the Park by Mark Pett 		ISBN 9781442483217
This is My Home, This is My School by Jonathan Bean 	ISBN 9780374380205
Lenny and Lucy by Philip C. Stead and Illustrated by Erin E. Stead 	ISBN: 9781596439320
The Boy who Loved the Moon by Rino Alaimo 	ISBN: 9781939629760

FIRST CHAPTER BOOKS (no blurbs)
The Complete Brambly Hedge by Jill Barklem ISBN 9780007450169
The Story of Diva and Flea by Tony Diterlizzi and Mo Willems 	ISBN 9781484722848
Francine Poulet Meets the Ghost Racoon by Kate Dicamillo Illustrated by Chris Van Dusen
	ISBN 9780763668860

INTERMEDIATE FICTION 

THE NEST by Kenneth Oppel, illustrated by Jon Klassen
ISBN 9781481432320
Anxiety-ridden Steve can hardly stand to think about his sick newborn brother. Then a white wasp comes to Steve in a dream with an offer: let this little brother go. The wasps will make a new one. A better one. He only has to say yes. Klassen's illustrations augment the papery creepiness of the story (chapter headings are marked by a growing swarm of wasps), but it's the courage and love bursting from this book that make it a staff favorite.
 
GEORGE by Alex Gino
ISBN 9780545812542
George is a pretty normal fourth-grade girl. She likes clothes and friends. She's dying to be Charlotte in her class production of Charlotte's Web. The only thing that's different about George is that no one knows she's a girl. Not her teachers, her family, or her friends. But George wants that to change. Alex Gino's debut stars a strong-minded, good-hearted, totally believable protagonist, a transgender girl who's ready to be seen by the world as she sees herself.


DOLDRUMS by Nicholas Gannon
ISBN: 9780062320940
A unique and whimsical story that is just begging to be read out loud. Characters reminiscent of Roald Dahl, with quirky humor and the best round about logic. Who doesn't get in shape for an Arctic Expedition by eating as much ice as possible?  The author also created stunning full color illustrations that perfectly highlight the setting of this brilliant new classic.

WOLF WILDER by Katherine Rundell 
ISBN: 9781481419420
Feo has a very unusual  job. Her and her mother re-introduce domesticated wolves into the wild. They call it Wolf Wilding. Feo loves the wolves and she loves her snowy home deep in the Russian wilderness. Unexpected friends, and fierce enemies change Feo's life, and the lives of the wolves closest to her, forever. After all, "wolves, like children, are not born to lead calm lives."

THE MARVELS by Brian Sleznick 
ISBN: 9780545448680
Marvels opens with the lone survivor of a shipwreck, a story told in Selznick's beautiful illustrations, and fans out into the text story of a runaway almost 200 years later. Both stories are beautiful and intriguing and in the end  marvels themselves when they meet in a way the reader won't expect. Marvels is a stunning follow up to 2011's Wonderstruck that is hands-down worth every second of the wait.

MAGNUS CHASE AND THE GODS OF ASGARD, BOOK 1: THE SWORD OF SUMMER by Rick Riordan ISBN: 9781423160915
Riordan has without a doubt done it again! With his signature wit and understanding of his audience, he crafts the punny, brave, and hilarious story of runaway, Magnus Chase, who had just been informed that he is the son of a Norse God. With a story set in Boston and chapter titles that are laugh-out-loud funny on their own, Sword of Summer is sure to make Riordan new fans while still managing to bring the old ones back for more.

Honorable Mentions:
Harry Potter and the Sorcerer's Stone: The Illustrated Edition by J.K. Rowling/illustrated by Jim Kay	
ISBN 9780545790352
Caretaker's Guide to Fablehaven by Brandon Mull 	ISBN 9781629720913
 Goodbye Stranger by Rebecca Stead	ISBN: 9780385743174


YOUNG ADULT 
SHADOWSHAPER by Daniel José Older
 ISBN 9780545591614
Sierra Santiago never knew magic was part of her Puerto Rican heritage. But shadowshaping—the ability to immortalize the souls of the dead in works of art—is real, and shadowshapers are being murdered. Sierra and a young shadowshaper named Robbie race through Brooklyn against time, zombies, and worse—before they lose shadowshaping forever. With language that sings and a story that pelts across the pages, Older's urban fantasy will go straight to your head.
 
DUMPLIN’ by Julie Murphy
ISBN 9780062327185
It's not easy being the fat daughter of Miss Teen Blue Bonnet 1997, but Willowdean is more interested in Dolly Parton, her best friend El, and the gorgeous boy at work than pageants. When her aunt dies and her friendship with El gets shaky, Willowdean loses confidence. To get back her gumption, she and a group of fellow unlikelys decide to compete in the pageant as they are—because every girl is good enough. Dumplin' is funny, fierce, romantic YA at its best.
 
ORBITING JUPITER by Gary D. Schmidt 
ISBN: 9780544462229
Have you ever read a book that was so profound, so full of soul, and meaning, and truth, that all you could do was sit in silence for a while once you finished? Orbiting Jupiter is that book. Make yourself some tea, snag a box of tissues, and let Gary Schmidt tell you the story of a boy named Joseph, a foster family, a small snowy town, and a baby girl named Jupiter.

THE REST OF US JUST LIVE HERE by Patrick Ness
ISBN: 9780062403162
 When the world is ending, it's the "special" kids who get all the attention. What about the people who are normal and not saving the world? Can they be extraordinary too? Or are they only background noise to all those special events? Mike, is a "normal" but in reality he is anything but. This story will stick with you long after you finish that last page, and will beg you to re-read it over and over.

ILLUMINAE by Annie Kaufman and Jay Kristoff 
ISBN: 9780553499117
Told through e-mails, interviews, and instant messages Illuminae follows Katy and Ezra, two refugee teens after their illegal mining planet is bombed.  They're genuine, smart, and resourceful as they attempt to uncover the depth of the conspiracy behind the tragedy. Managing to be alternately heart-breaking and laugh-out-loud funny, Illuminae delivers a story unlike anything you're expecting. With a story told this well, it doesn't matter if you're a sci-fi fan or not.


SIX OF CROWS by Leigh Bardugo 
ISBN: 9781627792127
Leigh Bardugo pulls no punches with her fast-paced and wildly addictive heist novel. Told through the point of view of six different characters all with their own voice, motive, and skills, Crows follows their attempt to break into an unbreakable prison. The story unfolds like all great heists with enough twists and misdirection to leave you begging for more. Welcome to the Dregs.

Honorable Mentions:
Simon vs. the Homo Sapiens Agenda by Becky Albertalli 	ISBN 9780062348678
 Hunter by Mercedes Lackey 	ISBN: 9781484707845
Trouble is a Friend of Mine by Stephanie Tromly 	ISBN: 9780525428404

NONFICTION
CABINET OF CURIOSITIES: Collecting and Understanding the Wonders of the Natural World by Gordon Grice 
ISBN 9780761169277
Budding scientists and naturalists can rejoice in this splendid introduction to nature collecting. Grice provides tips on specimen preservation, a history of nature collecting, and information on a wide array of natural objects (vegetable, animal, and mineral) with photos and illustrations. For those who prefer to stay inside, the book is tremendous fun to delve into; for those who like to pick up feathers, pebbles, and bits of bone, it's a genuinely valuable (and beautiful) resource.

 WHY’D THEY WEAR THAT?: Fashion as the Mirror of History by Sarah Albee and Timothy Gunn
ISBN: 9781426319198
Full of pictures, illustrations, and anecdotes, this is the only guide you will need to explore the history of fashion trends throughout the world. Why’d They Wear That? doesn't just depict what was worn in a certain era, but also highlights the influences, political and otherwise, that might have lead to that fashion trend at the time.

 SWAN: The Life and Dance of Anna Pavlova by Laurel Snyder, illustrated by Julie Morstad 
ISBN: 9781452118901
It doesn't matter if you know who Anna Pavlova is or not. Snyder and Morstad's Swan is a beautifully whimsical look at ballet and the life of a girl who loves it. Morstad's illustrations are soft and heart-achingly fitting to the story. Ballet fan and picture book fans alike will be taken in and delighted by the gorgeous story. A wonderfully perfect introduction to biographies.

Honorable Mentions:
Symphony for the City of the Dead by M.T. Anderson 		ISBN 9780763668181
Creaturepedia by Adrienne Barman 		ISBN: 9781847806963
Historium by Jo Nelson and Richard Wilkinson 	ISBN: 9780763679842


GRAPHICA
NIMONA by  Noelle Stevenson 
ISBN 9780062278227
Take one embittered villain, one beautiful knight, and add the most stupendous firebreathing, shapeshifting, attitude-having sidekick of all time, and you get Nimona! Nimona turns up and hires herself to Ballister Blackheart like it's no big deal, but as soon as she arrives, things do get big. Very big. Stevenson hits every note with a graphic novel that's uproarious, action-packed, and great to look at.

LUMBERJANES TO THE MAX by Grace Ellis Watters, Noelle Stevenson and  Brooke A Allen
ISBN: 9781608868094
Friendship to the MAX! That is what the Lumberjanes are all about. At this girl scout like camp anything is bound to happen. Yeti's, mermaids, demigods, possession... sounds like fun right? This gang of five friends can take on anything, anyone, anytime. Clever, sincere, subtle and one of the best new series around, there are no damsels in distress here! Just down-to-earth friends and outdoorsy adventure. There is good reason this series is the talk of the comic world this year!

FABLE COMICS edited by Chris Duffy  ISBN: 9781626721074
Different artists illustrate some of their favorite fables. The stories range from George O'Connor (of Olympians fame) tackling tales of the Greek Hermes, to Vera Brosgol (Anya and the Ghost) telling an Indian fable, The Hare and the Pig. Fables Comics has a little something for everyone and is perfect for both reluctant readers and graphic novel fans looking to find new authors to explore.

Graphic Series -
MS. MARVEL SERIES by G. Willow Wilson 
 vol 1. ISBN: 9780785190219
 The new Ms. Marvel is many things. Award winning, beautiful, quick-witted, and full of those awkward growing up moments. Wilson and Alphona are taking the world by storm with their brilliant re-imagining of a classic super lady. Your kid wants to read graphic novels? Hand them Ms Marvel and know that they are reading top quality graphica.

 
BABY-SITTERS CLUB: Full Color Edition by Ann M. Martin and Raina Telgemeir
(Vol 1 ISBN: 9780545813877)
Ann M. Martin's long-running series boldly, brightly, beautifully steps into 2015 with its first three full-color graphic novel volumes. With art by Smile and Sisters' Reina Telgemeier, these books and their enterprising heroines feel completely fresh. You don't have to be old enough to babysit to enjoy the BSC, but once you've met them, they're bound to be your fictional friends for life.
 
NATHAN HALE’S HAZARDOUS TALES by Nathan Hale 
( vol 1 ISBN 9781419703966)
A delightful and educational series about some of history's bloodier tales. A little gruesome, a little funny, Nathan Hale makes history interesting for even the most hesitant learner while still honoring the people who sacrificed their lives.

**Comment by shuchibooksmith** [comment]
Also included in this are Kids Gift items. Please let me know if the photos won't work. They are smartphone photos because of our time constraints for this first email. If they don't work we'll get better quality photos for the remaining gift guide sections.
![1](https://cloud.githubusercontent.com/assets/15218891/11256474/165a92a4-8e1a-11e5-9524-5e27bfb45938.jpg)
![2](https://cloud.githubusercontent.com/assets/15218891/11256475/165affe6-8e1a-11e5-8483-20851a8c0f7d.jpg)
![3](https://cloud.githubusercontent.com/assets/15218891/11256477/165b7340-8e1a-11e5-9d0f-8e3cf6d8e2d4.jpg)
![4](https://cloud.githubusercontent.com/assets/15218891/11256473/16589efe-8e1a-11e5-9290-19e472dbab69.jpg)
![5](https://cloud.githubusercontent.com/assets/15218891/11256476/165b71ec-8e1a-11e5-8a49-765ddf4c14a4.jpg)






Science Kits- $12.95-$24.95
Learning is fun when excavating a glow-in-the-dark T-rex and building a working volcano!  These science kits for kids range in interests from building robots to creating original works of spin art and are great for both girls and boys.
 
Retro Board Games- $18
Bring back fond memories and create new ones with board game classics like Candy Land and Chutes and Ladders.  Easy, educational and nostalgic, these games are fun for the whole family and have been a joy for generations.
 
Ridley's Toys- $8-$18.95
Good old-fashioned fun is exactly what you need to get the kids to put away their ipads and learn how to master the game of Kendama and yo-yo tricks, classic and new, with the new light-up effects version.  Our addictive collection of goodies and novelty toys will entertain for hours.
 
Bestie Kits/ DIY- $12.95-$16.95
The essential gifts for BFF tweens this year is our Bestie Kit and all of the DIY fashion jewelry and fabric markers and paints.  They can express themselves with a little pop of color and maybe even a temporary tattoo.
 
Bendable Action Figures- $9.95-$16.95
This little collection of caped crusaders are super poseable and make super gifts for kids ages 4 and up.  Also, the retro appeal makes these toys a great collectible and unique gift for the grown ups who are kids at heart.

**Comment by shuchibooksmith** [comment]
Here are some screenshots of Zoe's email blast-
![screenshot 2015-11-18 17 24 49](https://cloud.githubusercontent.com/assets/15218891/11257077/7b584572-8e1d-11e5-98f6-6b9a1b4202d7.png)
![screenshot 2015-11-18 17 30 41](https://cloud.githubusercontent.com/assets/15218891/11257078/7b61e00a-8e1d-11e5-9170-2c94c5726204.png)
![screenshot 2015-11-18 17 24 52](https://cloud.githubusercontent.com/assets/15218891/11257079/7b6213a4-8e1d-11e5-8c63-cbf6af38bd99.png)
![screenshot 2015-11-18 17 24 40](https://cloud.githubusercontent.com/assets/15218891/11257080/7b62ec48-8e1d-11e5-882e-b752d94cc1d4.png)

**Comment by budparr** [comment]
@shuchibooksmith - Love the banner! Did you have it made? If so, can the animals be closer to the center? They get cut off on many screens (remember these images have to work on really large and really small screens, so making them work on really large screens makes them cut off a bit on smaller).

**Comment by shuchibooksmith** [comment]
Oh no! Let me see if that's possible at all. I'll get back to you!

**Comment by shuchibooksmith** [comment]
can she design one that is smaller to fit the smaller screen?

**Comment by shuchibooksmith** [comment]
if you can send me the dimensions she can work on something! "she" - is Line, she does all the chalkboard art for us in the store.

**Comment by budparr** [comment]
I'm walking to a meeting and can't write right now. You want to call me?
646 484 8283

**Comment by budparr** [comment]
Generally speaking this https://github.com/sonnetmedia/brooklinebooksmith.com/wiki/image-dimensions
applies to anything that goes in the banner area.

We don't really want you to create multiple versions (if that was what you were suggesting), just to avoid complexity for you.

The important thing is to have the action in the center, particularly for mobile devices. It actually doesn't look bad as it is, just no cute animals. 

You're on a p.c., right? Not a mac? If you have access to a Mac I can show you a cool way to see what different screen sizes look like.

**Comment by shuchibooksmith** [comment]
I am on a PC! I'll send her the dimensions for the banner. The animals are so cute! So it would be great to get them to fit in. 

I happen to have my laptop with me and it's a mac, I can hop on it later this afternoon though!

**Comment by shuchibooksmith** [comment]
and how are the photos for the gift section? will those work??

**Comment by budparr** [comment]
Oh, yeah, they're fine. The only hard stuff is for the banners.

**Comment by shuchibooksmith** [comment]
PERFECT.
Okay great, working on the gift guide banner image, more soon. Thank you!

**Comment by shuchibooksmith** [comment]
Copy for the Cooking gift guide-

The NoMad Cookbook by Daniel Humm and Will Guidara 
9781607748229
This is one of the most beautiful cookbooks I’ve ever seen. It’s the product of pioneering restaurateurs Daniel Humm and Will Guidara, who distilled the experience of sitting down at their Manhattan dining hall into one elegant volume (technically two, since the last chapter is composed of false pages that form a box for a pocket-size cocktail guide). The recipes range from the minimalist (butter-dipped radishes with fleur de sel) to the decadent (duck roasted with apricots, chamomile and swiss chard), but all are exquisite enough to put stained glass windows to shame. There is one tomato tart with eggplant and rosemary that might be too dazzling to even eat, but if you decide otherwise, you’ll always have the picture.

My Kitchen Year: 136 Recipes That Saved My Life by Ruth Reichl
9781400069989
If there’s anyone who can harmonize the turning of seasons, the solitude of nature, the intimacy of a diary and the reverent joy of food, it’s Ruth Reichl. Following the abrupt shuttering of Gourmet magazine after 10 years as its editor, Reichl retreats into the practice of cooking, weighing every step - from visiting the butcher’s shop to sprinkling the final pinch of salt - as equal parts of a ritual that soothes and centers the preparer. This treasure of a cookbook takes us through a year with Reichl, and we get both the long walk through snowy woods and the roast chicken and apple crisp that follow.

HOMEMADE KITCHEN (the write up for this is still to come)

East: Culinary Adventures in Southeast Asia by Leanne Kitchen and Antony Suvalko
9781742709161
I picked up East thinking it was an opportunity to experience the kitchens and street vendors of Vietnam, Indonesia, Thailand and the rest of Southeast Asia at a fraction of what it would cost to make the trip. I wasn’t wrong, but Leanne Kitchen and Antony Suvalko’s loving descriptions and photos of the region have me all fired up to try a bowl of their duck and egg noodle soup while “watching the sun sink into the Mekong,” or nibble tamarind prawns at a lunch spot in Java to the “rhythmic thud of cooks pounding the freshest ingredients into fragrant curry pastes.” As a cook, my favorite part of this book is the opening section, “Basic Recipes,” which covers many stocks, sauces, spice blends and other staples of eastern cuisine that appear in most main dishes and might otherwise intimidate the home cook.
 
NOPI: The Cookbook by Yotam Ottolenghi and Ramael Scully 
97816077463232
From Yotam Ottolenghi, the visionary behind best-selling cookbooks Plenty and Jerusalem, comes another collection destined to become a classic. Ottolenghi rose to fame as a food columnist for The Guardian, beloved for his unpretentious but relentlessly innovative use of flavors and techniques. This latest book is named for his acclaimed restaurant, where Londoners gather daily for the parade of seasonal new dishes and beloved favorites. Be warned, this is not a book for the conservative palate - it is a wildly celebratory tribute to global cuisine. At the top of my to-cook list: Jerusalem artichoke soup with hazelnut and spinach pesto; gurnard baked in banana leaf with pineapple chile sambal and sticky sesame rice; pearl barley risotto with watercress, asparagus, and pecorino; and baked blue cheesecake with pickled beets and honey.


Vegetarian India: A Journey Through the Best of Indian Home Cooking by Madhur Jaffrey
9781101874868
The first book I read after becoming a vegetarian ten years ago was by Madhur Jaffrey. Thinking back I can’t remember if it was a memoir full of food or a cookbook full of her childhood in India - no one pairs clear, culinary instruction with cultural background the way she does. Her latest, Vegetarian India, is decidedly a cookbook, and it dispels any notions you may have about the limits of meatless dishes - the scope includes the traditions of dozens of cultures within India and ventures into the modern with Western ingredients like corn and quinoa. These recipes are for herbivores and omnivores alike.
 
Stories from the Kitchen edited by Diana Secker Tesdell 
9781101907597
Composed of classic literature’s choicest delicacies, this new anthology collects stories, memories, excerpts and ruminations into a snug, bright little hardcover. From sumptuous feasts to humble hearth gatherings, these writings dwell on the universal experience of a shared meal. Within you’ll find foodie mainstays like M.F.K. Fisher and Jean Anthelme Brillat-Savarin; luminaries like Virginia Woolf and Marcel Proust; and modern storytellers like Amy Tan and Nora Ephron, to name just a few.
 
Honorable mentions (to list)
Home Baked 	9781617691676																					
Shakespeare Not Stirred 	9780399173004	 																					
Mark Bittman's Kitchen Matrix	9780804188012																						
Pimp My Rice		9781848992788																						
The Mad Feast	9781631490736

**Comment by budparr** [comment]
http://brookline-151123-11052.surge.sh/holiday-gift-guide/2015/11/23/holiday-gift-guide---cooking/

**Comment by shuchibooksmith** [comment]
@budparr here are some edits for the kids gift guide
-Little Elliot, Big Family <--Big Family needs to be bolded in title
-Doldrums - it should be THE DOLDRUMS
-Wolf Wilder - it should be THE WOLF WILDER
-Illuminae - the author is Amie Kaufman (not Annie); and the character's name is Kady (not Katy)
-Marvels - author's last name is Selznick (not Sleznick)
-Fable Comics - the titles in parentheses should be italicized (Olympians) (Anya and the Ghost), and it should be Fable Comics not Fables Comics.
-add Graphic Series - next to Baby-Sitters Club and Nathan Hale's Hazardous Tales; next to each title it should read (Volume 1) in the parentheses before the buy button. 
-in Baby-Sitters Club Smile and Sisters' should be italicized, and Telgemeir is misspelled in the heading.

**Comment by shuchibooksmith** [comment]
sorry i didnt mean to close that!

**Comment by shuchibooksmith** [comment]
cooking gift guide -
can the honorable mentions be listed alongside one another in one box instead of a separate box for each title?

**Comment by budparr** [comment]
I was thinking the same, yes.

**Comment by shuchibooksmith** [comment]
Sorry, some more edits for the children's gift guide. I'll try to make sure you're getting much cleaner copy moving forward. 
Robo-Sauce - remove the comma after the parentheses 
Big Family - Little Elliot, Big City <-- italicize
Jack Frost - Guardians of Childhood <-- italicize
George - Charlotte's Web <-- italicize
Wolf Wilder - Wolf Wilder <--- italicize in link
Marvels - Marvels <--- italicize (x2), and delete "in the end marvels themselves when they"
Riordian - Sword of Summer <--- italicize
Shadowshaper - the accent mark should be over the e in the author's name - José
Orbiting Jupiter - Orbiting Jupiter <--- italicize title in blurb
Illuminae - Illuminae <--- italicize title in blurb x2
Swan - Swan <--- italicize title in blurb
Lumberjanes - remove apostrophe in Yetis
Fable Comics -
Olympians <--- italicize
Anya & the Ghost <-- italicize
Fable Comics <--- italicize
Baby Sitters - Smile and Sisters' <--- italicize

gifts-
Candy Land <--italicize
Chutes & Ladders <-- italicize 
Ridley's Toys - iPads

**Comment by budparr** [comment]
@shuchibooksmith are you saying you want all the book title headings italicized? Just checking. I hadn't done it because I made the bold instead. Anyway you like is fine, just let me know.

**Comment by budparr** [comment]
@shuchibooksmith I made the typo fixes. Can you add the kids books extra images here so I can add those too. cc/ @zchyde

**Comment by shuchibooksmith** [comment]
@budparr So in general, the headings for the titles can just be bold, as you've done. But within the blurbs, the titles should be italicized (not bolded).

**Comment by budparr** [comment]
awesome, thanks

**Comment by shuchibooksmith** [comment]
@budparr do you have a screenshot of the banner for the cooking guide? the montage look had lisa smitten so we're trying to replicate for the banner we're going to give you for the gift room. i think it was a certain part of that cover that was showing...i clicked on the cooking guide link and can't seem to find it now though...

**Comment by budparr** [comment]
@shuchibooksmith this: http://brookline-151123-11052.surge.sh/holiday-gift-guide/2015/11/23/holiday-gift-guide-cooking/ ?

**Comment by shuchibooksmith** [comment]
@budparr perfect, thanks!

**Comment by shuchibooksmith** [comment]
for cooking gift guide, the gift items 
![stone](https://cloud.githubusercontent.com/assets/15218891/11384103/fc487136-92da-11e5-8131-b1a752124110.jpeg)
![whipit](https://cloud.githubusercontent.com/assets/15218891/11384105/fc4f46dc-92da-11e5-85da-b25eaf37df30.jpeg)
![inapinch](https://cloud.githubusercontent.com/assets/15218891/11384104/fc4e1fe6-92da-11e5-889e-2e9b3f130992.jpeg)
![localboards](https://cloud.githubusercontent.com/assets/15218891/11384106/fc506b98-92da-11e5-9f2f-31f00e1fbd64.jpeg)
![pop](https://cloud.githubusercontent.com/assets/15218891/11384108/fc522262-92da-11e5-95b4-97a5ceee420e.jpeg)
![spoons](https://cloud.githubusercontent.com/assets/15218891/11384107/fc50b60c-92da-11e5-8429-f64e623c4d55.jpeg)

Bar Boards with Local Flair $19.95
No prep surface in your kitchen would be complete without a USA made bar/cutting board from J.K. Adams Co. Customized by The Giftsmith, the boards celebrate local pride with engraved "Entering Brookline," "Entering Boston," and latitude and longitude coordinates. This is also a great hostess gift and reminds us all that home is where the heart is this holiday season.

Whip It Good! Twisted Towels $12
This mischievous bunch of dishtowels sums up how most of us are feeling this magical time of the year. Made in the USA, each towel features a hilarious phrase or pun ("I have mixed drinks about feelings" is one of our favorites) suitable for most personalities in the kitchen.

In a Pinch Bowl! $4.95
Master your favorite holiday recipes with a little help from our colorful collection of mini prep bowls. In a pinch, the bowls double as condiment dishes or nut bowls during parties.

Rockin' Utensils $8.95-$16.95
"Don't play with your food" does not apply to these rebellious kitchen utensils. You'll be amped up to use the Drum Stick Spoons and Guitar Flipper while rocking around the holidays this season.

Pop Popcorn Maker $22
The Lekue popcorn maker cooks homemade popcorn with steam, making microwave popcorn easy, fun, and healthy. The silicone bowl is BPA free and comes with an instructional book of movie inspired recipes such as Amelie and Thelma & Louise. We recommend coming up with your own original popped treat inspired by your favorite film.

**Comment by shuchibooksmith** [comment]
and the missing cookbook blurb
The Homemade Kitchen: Recipes for Cooking with Pleasure by Alana Chernila 
9780385346153
I think this book is actually magical. On my first casual flip-through it fell open to a page that said only “Do your best, and then let go.” Why don’t all cookbooks start this way? As I read on, I felt the weight of food guilt - farmers’ markets unvisited, fridge vegetables forgotten, toddlers not raised on organic berries- melt away completely. Alana Chernila, author of The Homemade Pantry, delivers wisdom and expertise like a lifelong friend, and the beauty of her dishes inspires fellowship rather than envy. The recipes take advantage of seasonal fare but respect the limits of the home cook. We find simple classics like fried eggs and fresh pasta alongside international plates like miso soup and muhammara (you MUST try the muhammara.) This book could not be more perfect for the beginner, but also for anyone whose love of food could use a smidge of affirmation.

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kg0okVis&#x2F;15-add-gift-items-to-cooking-gift-guide"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add gift items to cooking gift guide</a>

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kg0okVis&#x2F;15-add-gift-items-to-cooking-gift-guide"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add gift items to cooking gift guide</a>

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kg0okVis&#x2F;15-add-gift-items-to-cooking-gift-guide"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add gift items to cooking gift guide</a>
