### ISSUE TITLE
enable comments for blog?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#130]
what are your thoughts on this @budparr? readers could comment on our old blog posts, we just had to go in and approve them first.

**Comment by budparr** [comment]
I can add comments, no problem. I use DISQUS, typically, for commenting, which has great features for moderation. I just don't do comments by default any more because they're so often not used or the comments are not really discussions.

**Comment by shuchibooksmith** [comment]
yeah i think we should give it a shot! The kids team used to get some pretty good feedback on their posts, so let's try it? if it becomes a problem we can disable it.

**Comment by budparr** [comment]
Whomever you want to moderate comments should get an account (free) at DISQUS https://disqus.com/ and send me the usernames and I'll add as a moderator. https://disqus.com/

**Comment by shuchibooksmith** [comment]
that'd be me! i created an account, username is shuchibooksmith

**Comment by budparr** [comment]
Can you leave a test comment on a post on the site, logged into DISQUS (i.e. comment using your DISQUS account)?

**Comment by shuchibooksmith** [comment]
just left one!

**Comment by budparr** [comment]
okay, you're a moderator now

**Comment by shuchibooksmith** [comment]
excellent, thanks!
