### ISSUE TITLE
Blog homepage issue

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#132]
Hey, it looks like the homepage is having trouble loading blog posts - a new post I made last night has shown up on kidsmith and the blog page, but not on the home page. 

This might be a problem with the "featured post" situation, because in addition to that, when I unpinned last week's featured post and pinned the new one, the old one dissappeared from the homepage )but is visible on the blog page). 

Blergs.

**Comment by budparr** [comment]
what's the name of the new post?

**Comment by budparr** [comment]
Oh, I see. It's Ida Always. I'll look. I think you're right, my pinned post logic is probably not quite logical enough (which, sorry, this week has been the week from h.e.double thoothpick after having been out last week)

**Comment by zchyde** [comment]
Ohh noooo, I'm sorry. No sweat, lmk if you want anything from me.
