### ISSUE TITLE
change font color for newsletter sign-up

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#133]
I'm on my home laptop, but when I tried signing my husband up for our newsletter, I typed in his name and it came out a really dark gray? So dark that I couldn't see the email address that I was typing. When I hit enter it took me to the official sign up page, but still, we might want to change the font color so that that it's more visible for people typing in addresses. 
![screen shot 2016-02-29 at 7 33 45 pm](https://cloud.githubusercontent.com/assets/15218891/13413798/63db6b32-df1b-11e5-9da9-c80704dd21fa.png)

**Comment by budparr** [comment]
Good catch, @shuchibooksmith thank you.
