### ISSUE TITLE
limit number of blog posts on homepage

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#134]
Good morning @budparr - is there a limit on the number of blog posts that appear on the homepage?  As we have added new ones, there are currently 10 total posts, which makes one have to scroll down further to get to the material at the bottom of the page.  Do you think it should be fewer posts that appear - maybe 5?  Do you think it should just be even with the events listed - which may vary?

**Comment by budparr** [comment]
I agree. I had changed it here and there to make the blog posts and events to be more even in the space they took up. I think 5 is a good number and will change it.
