### ISSUE TITLE
Do we want the past "This week in books" to show on the home page once there's a new one?

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#135]
I think not since it's had its life already (and will be on the blog page), but want to make sure. I seem to recall a specification that it should be, but was just re-thinking. 

cc @sonnetmedia/brookline-staff

**Comment by peterbooksmith** [comment]
I don't remember if we said anything specific about this.  Now that there are fewer blog posts on the home page, it seems like the previous "This week in books" will get bumped along naturally?  We are missing one post from this week (Wed) and if that was there, the older one would be gone from the homepage.  Also open to any other suggestions on this.

**Comment by budparr** [comment]
If there's no specific reason to have it remain on the home page, I'd say best to not have it, just to keep things fresh. It will, of course, be on the blog page.

**Comment by peterbooksmith** [comment]
Makes sense to me - not sure if @shuchibooksmith or @zchyde have any feelings on this?

**Comment by zchyde** [comment]
hmm I think we could do it either way, but I'm always for killing old content to be honest. From the homepage anyway.

**Comment by shuchibooksmith** [comment]
Nope, no strong feelings. Thanks!

On 3/4/2016 10:43 AM, peterbooksmith wrote:
>
> Makes sense to me - not sure if @shuchibooksmith 
> <https://github.com/shuchibooksmith> or @zchyde 
> <https://github.com/zchyde> have any feelings on this?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/135#issuecomment-192327876>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

P Please consider the environment before printing this email.
