### ISSUE TITLE
is it possible to preview blog posts?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#136]
some of our bloggers are wondering - is there a preview function at all? just thought i'd ask..

**Comment by budparr** [comment]
No. Not in this editor. It's possible to maybe use a different editor though, which I can explore. We have the flexibility to use multiple editors, though the one we're using is the all-around best.

**Comment by shuchibooksmith** [comment]
Let's stick with the we have then! Thanks.
