### ISSUE TITLE
Issue with stray image showing up on events

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#138]
reported via email, by @zchyde 

> Hey bud, I've got an event that's glitching. 4/26, 4:30. "Stories from the Shadows" book cover rears its ugly head again. I thought maybe I could fix it by uploading an image, but that didn't fix it.

> its also on the regular book club listing

**Comment by zchyde** [comment]
I tried to post a blog later and it also showed up there! Its everywhere

**Comment by budparr** [comment]
which blog post??

**Comment by budparr** [comment]
Figured it out. I fixed that post. I know what the issue is, sort of (!), and am working on a fix.

**Comment by zchyde** [comment]
The Ghost Cover 
![duo-clipart-halloween_ghosts_duo_2](https://cloud.githubusercontent.com/assets/15219441/13510818/6d870794-e160-11e5-9578-9d0db1a80830.jpg)

**Comment by zchyde** [comment]
![duo-clipart-halloween_ghosts_duo_2](https://cloud.githubusercontent.com/assets/15219441/13510836/83c648e4-e160-11e5-8a43-7c667d4d321b.jpg)

**Comment by budparr** [comment]
spooky

**Comment by budparr** [comment]
I did some ghostbusting http://www.vox.com/2016/3/3/11152328/ghostbusters-trailer

**Comment by zchyde** [comment]
You probably will not get a chance to see me because I was in the way back of every shot but I DID take three days off from work so I could be an extra in that movie so I can't even tell you how pumped I am about it. And that you fixed the glitch OBVIOUSly

**Comment by budparr** [comment]
that really is about the coolest thing I've ever heard

**Comment by budparr** [comment]
By the way. I solved the issue, but I didn't really "fix" it from happening again. When we relate events/posts to books we look for a non-null (lovely double negative) value in the entry's ISBN field and because books are supposed to all have ISBNs it generally works. But it fails here where we had a book with no ISBN.

**Comment by zchyde** [comment]
huh ok. I remember that one being strange, Indiebound had no page for it, so maybe that was why I didn't input a number into that field. I'll remember that.

**Comment by budparr** [comment]
I'm going to make an issue for a better fix, but should be fine for now.
