### ISSUE TITLE
Create a way to highlight "alerts" or special events

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#14]

**Comment by budparr** [comment]
@shuchibooksmith FYI. I've created this as a separate issue. I've given it a "Milestone" of 1.1 meaning that we may not have it for the initial version, but will prioritize it for soon after.

**Comment by shuchibooksmith** [comment]
Excellent! Thank you.

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;8nB67Msa&#x2F;9-create-a-way-to-highlight-alerts-or-special-events"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Create a way to highlight &quot;alerts&quot; or special events</a>
