### ISSUE TITLE
add store phone number to homepage?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#142]
we had a customer call and complain that she couldn't find our phone number on the website. @budparr what are your thoughts on including the contact info all the way at the bottom of the homepage?

**Comment by budparr** [comment]
1) There's always, and I do mean always, someone who will complain about something. That's not to sound snarky, and not to say everyone doesn't have a voice, but if we changed the design for everyone we'd all go crazy, and...

2) It's on the **very top of the home page on every page** on everything but desktop. And, on desktop it's prominently displayed on the hours/location page, which someone just asked me if we should even have. So, I think it's pretty well covered. 

3) If you wanted it, it could go in the footer, but very few people ever scroll as far as the footer. 


<img width="787" alt="screen shot 2016-03-07 at 1 34 20 pm" src="https://cloud.githubusercontent.com/assets/115347/13579033/536ddfa2-e469-11e5-92a3-0ffc05678bbf.png">

**Comment by shuchibooksmith** [comment]
right. i only shared this one because it seems like a semi-legitimate 
gripe. i agree that the footer would be only place to really add the info.
but we can just hold off for now and see if anyone else complains? i had 
never noticed that the phone number wasn't on the homepage before, but 
that's because it's pretty prominent on the mobile page so in never 
thought to check the desktop homepage.

On 3/7/2016 1:37 PM, Bud Parr wrote:
>
> 1) There's always, and I do mean always, someone who will complain 
> about something. That's not to sound snarky, and not to say everyone 
> doesn't have a voice, but if we changed the design for everyone we'd 
> all go crazy, and...
>
> 2) It's on the *very top of the home page on every page* on everything 
> but desktop. And, on desktop it's prominently displayed on the 
> hours/location page, which someone just asked me if we should even 
> have. So, I think it's pretty well covered.
>
> 3) If you wanted it, it could go in the footer, but very few people 
> ever scroll as far as the footer.
>
> screen shot 2016-03-07 at 1 34 20 pm 
> <https://cloud.githubusercontent.com/assets/115347/13579033/536ddfa2-e469-11e5-92a3-0ffc05678bbf.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/142#issuecomment-193386699>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

P Please consider the environment before printing this email.

**Comment by budparr** [comment]
I'll close this for the moment. Let me know if you want to talk about it some more at any point.
