### ISSUE TITLE
Remove "featured" divider from home

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#144]
Peter and Shuchi convinced our Powers that Be that the "featured" blog post was clouding up our other content, so even though you just put this in the other day, can you please take just the "featured" divider off of the home page and I will unpin the featured post? Sorry again, this has been somewhat of a battle here. To be clear we want to keep "latest from the blog" and "events" dividers.

**Comment by budparr** [comment]
No problem!
