### ISSUE TITLE
Issue with post image?

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#146]
Hi @zchyde wondering if you're having problems with images at all? I notice this one, which was there yesterday, is messed up.

http://www.brooklinebooksmith.com/2016/03/14/this-week-in-books/

https://github.com/sonnetmedia/brooklinebooksmith.com/blob/gh-pages/_posts/2016-03-14-this-week-in-books.md

**Comment by zchyde** [comment]
huh well what I've been doing is letting people upload their blogs to drafts, then I go in, take out their images and replace them with compressed ones, which I attempted ot do to this one thing morning, but maybe i messed it up somehow

**Comment by zchyde** [comment]
the post in the CMS editor has the image there...

**Comment by budparr** [comment]
been working so far, but something went awry with that one. That workflow sounds a bit messy. I'll see if I can automate it for you (after I get through the FEBC commerce stuff) to some degree, though I think it's probably creating some unnecessary images if they're uploading and then you're uploading a new one over that. 

At any rate, I'll dig around

**Comment by zchyde** [comment]
I'm trying to delete the larger files as I go, but yes I have missed a few

**Comment by zchyde** [comment]
the problem is that not every computer we have is equipped to resize images, otherwise I would feel more comfortable telling bloggers to do it themselves

**Comment by budparr** [comment]
No worries! We'll figure something out.

It looks like that image either is corrupt or could have something to do with other images being named "untitled." Not sure. I'd just try uploading it anew, with a new name.

**Comment by zchyde** [comment]
I just did that, waiting to see if it works.

**Comment by budparr** [comment]
I see that. Seems to be taking a while to update. hmmm.

**Comment by budparr** [comment]
There it is. Thanks. I'll revisit the workflow issue soon and try to make your life easier. :smile:
