### ISSUE TITLE
Access web traffic numbers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#148]
hi @budparr  - I know we touched on this briefly before but I forget how we left it - how do access traffic numbers and that kind of data for the website? particularly for the blog, but also in general.

**Comment by budparr** [comment]
Richard Steinberger has all this information.

**Comment by budparr** [comment]
by the way, that's not to say you can't have access too, or, if you want I can set up reports for you, but Richard might be able to do that for you, or give you the information you need. Just let me know!

**Comment by shuchibooksmith** [comment]
no, it's great for richard to have this info! if anyone else needs access i'll let you know. thanks!
