### ISSUE TITLE
upcoming events page glitch

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#149]
when you make the upcoming events page window narrower, the book cover enlarges and gets grainy
![image](https://cloud.githubusercontent.com/assets/15218891/13954717/554831f0-f018-11e5-87c9-b8f16f0f9628.png)

**Comment by budparr** [comment]
Noted. It's an unfortunate side-effect of the original images not being great quality, which shows only on mobile devices, but I'll see if I can adjust the breakpoints so that they go full width only on the smallest screens.
