### ISSUE TITLE
search bar disappears

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#150]
This glitch is still happening - when you change the sizes of the window, there are a few inbetween sizes where the search bar disappears
![image](https://cloud.githubusercontent.com/assets/15218891/13954765/94c48d2e-f018-11e5-925c-54d3a9b234ed.png)

**Comment by budparr** [comment]
This is part of improving navigation, so I'm going to close this issue in favor of the existing issue. Thanks.
