### ISSUE TITLE
Blog post save glitch

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#151]
Oh I haven't done this in so long, is this where I still post issues?

Something is happening with the blog posts, when they are drafts and I hit "publish" on them, and check the "publish" box, they are then moved from Drafts to Posts however they don't show up on our actual blog until I go in and make a save, however miniscule, while it is in the posts folder. If I delete a comma or put a space in (which is what I've been doing) while the post is published and in the posts folder, after the first time i save it as a published post, it will then show up. 

Obviously not a big deal and not something to put at the top of your list, but still curious? And not how it was before.

**Comment by budparr** [comment]
> Oh I haven't done this in so long, is this where I still post issues?

Yes!

How long as this been going on?

**Comment by zchyde** [comment]
At least a week, I was so scattered I didnt really begin to notice it until thurs/fri of last week and then I thought maybe I was just crazy but I posted Lydia's most recent post last night and it didn't show up until about 30 minutes ago when I added a space to her body content and saved

**Comment by budparr** [comment]
Okay, I'll check it out and let you know.

**Comment by budparr** [comment]
Finally making some progress on this, @zchyde  - went through some trial and error, and finally the guys at the editor we're using narrowed it down. Hopefully we'll have a fix in soon, so in the meantime, that extra save step (should be just when you've published a draft post) will work.
