### ISSUE TITLE
Consider Menu items Reconfiguration

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#153]
Ahead of enhancing the site's layout, we should discuss the menu items, as started [here](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/152#issuecomment-217256884) with @peterbooksmith 

This was one approach I had brought up earlier. I understand that it's not ideal, and also why not, but just to start the discussion anew, I thought it would be helpful to have something to work with.

---
Essentially, the basics (hours/about), followed by events and blog, with Kidsmith too, because it has blog posts/events, and the shop, which would encompass any other shop/section pages, since those pages are mostly informational. We can also promote gift cards in other ways besides the menu.

(this table won't look right unless you view it on Github)

| Hours/Location | About | Events | Blog | Kidsmith | Shop^ |
-----------------------|----------|----------|--------|------------|----------|
||||||Giftsmith|
||||||Gift Cards|
||||||Used Book Cellar|

**Comment by shuchibooksmith** [comment]
I had really liked the direction we were moving in with this originally - specifically, the two bar format. i think that moving the search window up there would be helpful too. i know one concern had to do with the size of the banner, and i'm wondering if we can keep that as is, what people think - 
![image](https://cloud.githubusercontent.com/assets/15218891/15056126/26f166c6-12de-11e6-8f62-bb4c1d9c416e.png)

**Comment by budparr** [comment]
I remember that conversation and after going back over it, I may have misinterpreted your comments about the banner, but yes, making the banner larger is possible.

**Comment by shuchibooksmith** [comment]
okay! That would help - i know a couple of people like the large banner image. peter is more tuned in to the priorities of what needs to be represented on the main menu, so i'll let him handle that part.

**Comment by peterbooksmith** [comment]
@budparr  - so far so good with SFE.  Regarding THIS issue, I recommended to our other owners that we ask/let you come up with a different design or designs for the home page, based upon what you have seen this far with google analytics and what you know about us after the past 9+ months and we go from there.  If you want to continue in the direction represented above, fine.  As you previously mentioned, I would also definitely like to consider what is working/getting lots of traffic, and what is not, and what we should do about that.  Everyone is good with that plan, we'd like to know what you think and recommend.

Of course, I can't promise we'll listen to you.  In the end, we - or at least a majority of us - may want to keep things as they are, but everyone is ready to be open to whatever possibilities you want to give us.   I know could be a wide range of possibilities, so please let me know what I can do provide any info that would help.  I can tell you that for a while, we will want some link to the Signed First Editions page nice a visible - probably more so than just a link in the top menu.  Similar with the Harry Potter thing.  We'll want that up through 7/31/16, but after that it can go away.  Aside from that, the one thing that should remain constant is the link to the Giftsmith page should always be part of the plan and visible.  I know you've heard that before, but I am saying it again.

How does that sound? Also, have a nice weekend and thanks.

**Comment by budparr** [comment]
Absolutely, perfect, @peterbooksmith, seriously. Have a great weekend.

**Comment by peterbooksmith** [comment]
@budparr - how is this going?  Any ideas on a time frame?

**Comment by budparr** [comment]
Hi @peterbooksmith - My M.O. with you guys is to come up with a more fully-formed and polished version before showing you because I know you have a rather lengthy internal process, which I don't want to tax. I've been taking my time to come with something that is long-term viable given the above, but I'd say I can show you something within the next week.

**Comment by peterbooksmith** [comment]
That does sound like our process.  Something this week would be great.  Thanks.
