### ISSUE TITLE
HOME on homepage?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#154]
Hi, Bud!
I was just on the homepage and noticed the white Home lettering on the banner, Figure you're working on something?
![image](https://cloud.githubusercontent.com/assets/15218891/15523627/d481dca2-21e9-11e6-9414-561c56d4649e.png)

**Comment by budparr** [comment]
Strange. No idea what caused it, but may have had something to do with software upgrades. I fixed it, and will keep an eye out for it happening again. Thanks!
