### ISSUE TITLE
archive folder in posts?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#155]
hello @budparr!
one of us accidentally deleted the archive folder that was in the posts page. i'm not sure what was in it? how important it was? how easy it is to replace?
sorry about that...
shuchi

**Comment by budparr** [comment]
Hi @shuchibooksmith  - it was an archive folder of really old posts. It was just there for safekeeping. I can restore it if you like, but it's not 100% necessary.

**Comment by shuchibooksmith** [comment]
@budparr ah okay. so all the stuff from blogger. yeah, maybe restore it then? i don't know if we have those old posts anywhere else...

**Comment by budparr** [comment]
It's restored. Have a good one!
