### ISSUE TITLE
SFE page changes

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#156]
On http://www.brooklinebooksmith.com/sfe/ 
1. could "Announcing a very exciting new program for Booksmith and book lovers:
The Signed First Editions Book Club (SFE)"  be...bigger, bolder, something that is more dynamic? In order to match other type in the page, maybe the same size and style as "Signed First Editions Book Club" right under "Subscribe?

2. Tim would prefer the Julian Barnes book still appear as a current, June selection, and not as a Past Selection. Can that be moved back up and appear as June, to the left of the July selection. Each month's pick should remain up until the beginning of the next month, so when we get to July 1st, Barnes can go back to the Past Selections.

I think that is all.  Thank you.

**Comment by budparr** [comment]
All set.

**Comment by peterbooksmith** [comment]
A few more things here.
1. In the "What Does It Cost to Join..." section:

A. There should be a space between "our" and "Pickup Plan" - "or you can save on shipping and choose ourPickup Plan (29.00/month)"

B. Also, could the "sfe@brooklinebooksmith.com" at the end of that section be a hyperlink to that email address?    (...or email Tim Huggins at sfe@brooklinebooksmith.com.)
 
2) PayPal text for Plan Description on Delivery Plan.
Reads "First Editions Book Club: Delivery Plan" but should read "Signed First Editions Book Club: Delivery Plan". The text for Pickup is fine.  (This is per Tim.  I haven't looked at it myself, but let me know if that isn't clear?)

**Comment by budparr** [comment]
the copy changes are done. I'm working on beastly Paypal right now for the other.
