### ISSUE TITLE
homepage content??

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#161]
hello @budparr!
our homepage content seems to have...disappeared?
figured you're working on something, but not sure if you knew that had happened....

**Comment by budparr** [comment]
No, but I'll look right away.

**Comment by budparr** [comment]
Hi @shuchibooksmith - I fixed this. A setting for the page was erroneously removed while someone was editing it. I put it back, but most importantly, I removed the setting to a place where that can't happen again.

**Comment by shuchibooksmith** [comment]
great! thank you!!!

On 6/20/2016 3:32 PM, Bud Parr wrote:
>
> Hi @shuchibooksmith <https://github.com/shuchibooksmith> - I fixed 
> this. A setting for the page was erroneously removed while someone was 
> editing it. I put it back, but most importantly, I removed the setting 
> to a place where that can't happen again.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/161#issuecomment-227245056>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AOg4y19ZGCzaMEtMkXzdjuble7AuTyymks5qNurQgaJpZM4I6B97>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

**Comment by zchyde** [comment]
it was probably me, I updated the bestselling hardcovers/paperbacks this AM, SORRY EVERYBODY thought I'd just delete the whole dang thing for a giggle

**Comment by budparr** [comment]
AHA! No worries though - I shouldn't have exposed something so critical to day-to-day use, so it's my bad actually.

**Comment by shuchibooksmith** [comment]
i just hope @zchyde giggled.

**Comment by zchyde** [comment]
Oh I did in fact giggle, thats undeniable
