### ISSUE TITLE
Unpin Palahniuk blog post

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#163]
Hi @budparr!
Looks like after you unpinned the SFE post the Palahniuk blog post is now pinned. Can you unpin that one? We don't want any pinned blog posts at the moment.
Thanks!

**Comment by budparr** [comment]
Hi @shuchibooksmith - It picks up any post that's marked "featured," so I unchecked that one and made sure there were none others. Have a great weekend!
