### ISSUE TITLE
Sharing Blog Posts on Social Media

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#164]
@budparr -
when we share a post on social media (namely, facebook), we don't have too many options as to which photo and text we can share. so the corresponding image is usually of the homepage banner and something else. any way to fix this?

**Comment by shuchibooksmith** [comment]
![image](https://cloud.githubusercontent.com/assets/15218891/16430618/75e27158-3d4a-11e6-9238-c0cd965f0f34.png)

**Comment by budparr** [comment]
It should be giving you the image from the post. I've been messing around with some of that stuff, so perhaps something is wrong. I'll have a look and get back to you.

**Comment by budparr** [comment]
It has to do with the size of the images. I put a short-term fix in for now and a better one coming up in the next iteration of the site. I'll leave this open so I don't forget about it though.

**Comment by zchyde** [comment]
Just curious - size like dimension or size like file size?

**Comment by shuchibooksmith** [comment]
@budparr hmm, same thing is still happening...

**Comment by budparr** [comment]
Facebook doesn't say which in their lintner. I've never wanted you all to have to put in a separate image for social, but  I can control this with something that I'm implementing here pretty soon. 

Shuchi, it can take a bit of time, because FB caches web pages. Let me know if it persists.

**Comment by shuchibooksmith** [comment]
okay, thanks!

**Comment by shuchibooksmith** [comment]
@budparr i cleared cache and waited some and it still doesn't seem to be working...

**Comment by budparr** [comment]
Okay. I'll go ahead and implement the fix right away.

**Comment by budparr** [comment]
In the meantime, @shuchibooksmith tell me what post you're trying to add and I'll see if I can clear the Facebook cache manually.

**Comment by shuchibooksmith** [comment]
sure! i'm trying to share the most recent blog post, this week in books 
http://www.brooklinebooksmith.com/this-week-in-books/2016/06/27/this-week-in-books-book-record-shop-to-open-in-restored-funhouse/

**Comment by budparr** [comment]
I fetched that with the Facebook tool and am getting the image from the page.

**Comment by shuchibooksmith** [comment]
hey @budparr, sorry to pester. dana was just asking again if i was able to share blog posts on facebook, and the same problem happens (though this time, it's showing the banner home page and the text below is the homepage content, even when i share right from the post page). should i share another way?

**Comment by budparr** [comment]
what is the post? This is what Facebook's official debugging tool shows me for the latest post: 
<img width="949" alt="screen shot 2016-06-30 at 11 57 25 am" src="https://cloud.githubusercontent.com/assets/115347/16495087/e8794050-3eb9-11e6-9ece-11a52d9b581e.png">

**Comment by shuchibooksmith** [comment]
ah-ha, yes, i was sharing through the share button at the bottom of the blog post page. copying and pasting the link gives me the right info. SORRY about that!!!! All good. :)

**Comment by budparr** [comment]
Ah, okay. I'll have a look at that too though. I've been implementing a new sharing set up to optimize those images.

**Comment by budparr** [comment]
@shuchibooksmith Just to clarify, you were sharing with the button on the bottom right of the page?

**Comment by shuchibooksmith** [comment]
bottom left, next to the recommend button

**Comment by budparr** [comment]
Interesting. Okay. So that's part of the DISQUS commenting system. Not sure if I have control over that, but I'll check. I don't "think" that's the primary avenue for sharing. I moved the follow buttons in the newest version (which I'll show you soon) to avoid confusion.

**Comment by shuchibooksmith** [comment]
great! thank you!!!

**Comment by shuchibooksmith** [comment]
heads up, closing this issue, it's resolved on my end at least
