### ISSUE TITLE
New Top 25

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#165]
hey @budparr 
remember this blog post we did a while back?
http://www.brooklinebooksmith.com/2016/01/01/top-25-books-of-2015/
We updated the list with the bestselling books so far. i want to do another post just like this, except i'll add a little bit of text beforehand. how did you do this one?

**Comment by budparr** [comment]
If they're not in already, just add the books to the site as you'd normally do (the "Books" collection), and select them in the post with the "books" field, which I believe is bottom right. 

And, if you see her, say hello to my friend Emily Barton who is reading there tonight!

**Comment by zchyde** [comment]
Hi Bud, Shuchi and I are trying this right now, and it doesn't appear to be working. I know how to add books to the site, but when I select them in the "books" field and publish the post, nothing happens, no books appear. Is this something we're doing wrong? I went looking for the post you made last time but I can't find it in the "posts" or "archive" folder

**Comment by budparr** [comment]
I fixed this and you shouldn't have a problem now.
