### ISSUE TITLE
Ghost Test`

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#166]
Bud I can't figure this out, Shuchi asked me to delete this test post, but there's no icon for it in the drafts - do you have any idea where it might be lurking ? 

http://www.brooklinebooksmith.com/2016/01/15/aaaaaaaaaa-test/

**Comment by zchyde** [comment]
this feels like one of those really obvious fixes that you tell me about and I go "oh duh"

**Comment by budparr** [comment]
They were in the posts list. My bad for not deleting them earlier, but they're gone now.
