### ISSUE TITLE
Discussion on next iteration of the site

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#167]
Hi @peterbooksmith
cc/ @shuchibooksmith, @zchyde 

I'm opening this discussion for us to review progress on the next iteration of the site. 

My goals with this iteration are:
- **Improve the layout of the menu**
  - Better accommodate many items (including the SFEBC).
  - I applied a constraint to myself on this item of not hiding items behind a drop-down menu. I believe that your audience is less apt to click on hidden items.
- **Make home page work harder**
  - show more items in an easily scannable way.
  -  make campaigns and special announcements fit naturally.
  - improve display of bestsellers
- **Improve workflow for content creators**
  - Reduce dependency on featured images (make pages without them look better)
  - improve editor experience (minor changes to improve clarity, but also make way to use the visual editor)
- **Refactor codebase**
  - Necessary to be more flexible and modular in the future. Primary goal is to simplify. This is a little hard to explain, but in earlier version we're more focused on getting your needs met, so now is an opportunity go back and see if we can improve on that initial work after reflection. This makes for a long-term more maintainable version of the site.
  - improve performance (use a CDN for images), decrease javascript dependencies where possible.

This is a time consuming process (particularly refactoring), and I don't want to rush it, but I also want you to understand what's going on and not have to wait for a polished prototype. While we agreed showing a polished prototype was best for the internal BBS workflow, my normal workflow is more iterative (like this) and I like to show my work along the way. I think going back to that is the best bet (better than leaving you in the dark), and I'll let you manage your internal process as you see fit. 

Hope that's okay, I just felt like I was not being as transparent as I'd like and felt like you might have been getting frustrated with me, while, in turn, I was merely afraid to show work-in-progress out of concern that it would cause extra work on your end, and possibly consternation, on the part of people inside the organization. Whew!

---

### Design iteration 1

The screenshot I'm posting here is an article page, just because there are fewer things to focus on. You'll note that the navigation is all on the side now. I went with a ton of iterations before arriving at the idea of making it "app-like" with the side navigation. This allows you to have a lot of menu items without having to hide any of them (_as I set as a requirement_), or break them up into multiple rows (as you may recall an earlier iteration of mine had).

So, as you can see, everything fits here and I think it's quite easy to navigate from section to section. I think it gives the site an element of clarity and makes the navigation items more noticeable and inviting, particularly since the side-nav stays fixed within view even while the reader is scrolling down, so they're never out of site.

On smaller mobile devices the menu will be hidden as it was before, but it also includes the address and phone number for quick access.

Also, the side-navigation solves another problem, albeit subtly. I wanted pages to look good without a "featured image," however, a page without an image can be dull. The bright color of the side-navigation allows the page to have no image without being dull (the color spanning the height of the page livens it up). 

I'm attaching two versions. One with the nav on the left, and one with the right. I can change the side it's in about 10 seconds (owing to the newly refactored code-base), so which side isn't set in stone. I like them both. 

Putting the nav on the left feels more natural or intuitive, while putting it on the right feels like it gives the article more breathing room, putting the text more in the center of the page.

Also note that I removed the search box and put it together with giftcards. I did this because I feel that it's jarring for someone to come to the site, search and be led to a completely different site. When, earlier in the year, I had looked into making the shop site look like the main site, I felt like doing so would have been terribly time consuming (because Drupal uses a theme-based structure) and would have hurt our efforts on the main site. The theme you've chosen is better than what was there before, but it's still a jarring difference.

I think the labeling is clear for the search/giftcard item (and putting it last on the menu gives it attention) and putting it on it's own dedicate page gives us the opportunity to add some copy to the page explaining that they're going to the shop site, and can give us another opportunity to display specials, etc.

Note the prominent "subscribe to mailing list" button, which I separated from other menu items. I'm not married to the color, I just wanted something friendly here. The page itself is lighter than it appears in the screenshot, for some reason.

Happy to hear your thoughts. You're welcome to show to anyone, of course, and give me feedback, but I don't want anyone to feel like this is formal or set in stone. That said, while I'm never set on anything, as you know, I do feel strongly that this side-navigation solves some problems for us, so I'd encourage everyone to not dismiss it too easily. 

<img width="1440" alt="screen shot 2016-07-01 at 1 38 01 pm" src="https://cloud.githubusercontent.com/assets/115347/16529849/193d2010-3f93-11e6-8f67-afa6a4a01407.png">

<img width="1440" alt="screen shot 2016-07-01 at 1 24 26 pm" src="https://cloud.githubusercontent.com/assets/115347/16529852/1f67af5a-3f93-11e6-8d9a-902c4606e8c3.png">

**Comment by peterbooksmith** [comment]
Thanks Bud.  I've looked everything over and shared with Dana via email.  She and Shuchi will share and discuss with others here while I am away.  All of your explanations and reasoning make sense to me, and I like this menu layout.  We'll see what others think and hopefully we can come up with some productive ideas and feedback, keep this moving.

**Comment by budparr** [comment]
Excellent, @peterbooksmith - have a great trip!

**Comment by zchyde** [comment]
I think this looks really good for the blog post/individual pages but I'm so curious to see what the homepage would look like

**Comment by budparr** [comment]
I'm curious too, @zchyde :). I'm working through some ideas now. When I get to something I'm reasonably confident with and can explain my thinking in writing, I post it here.

**Comment by peterbooksmith** [comment]
Hello,
  
 I will on vacation from July 5-18.  Please contact the store at 617-566-6660 or thestore@brooklinebooksmith.com if you need assistance.
  
 Peter Win
Assistant Manager / Co-owner
Brookline Booksmith
279 Harvard Street
Brookline, MA 02446
617-566-6660

**Comment by shuchibooksmith** [comment]
hi @budparr! sorry for the silence - dana and i are going to discuss tomorrow and i'll get back to in the afternoon/evening. thank you!!

**Comment by shuchibooksmith** [comment]
Hi @budparr! 
So we took a look at this, and I think the biggest question we all have is why the restraint of no drop down menu. You mention that you don't think our customers will use the drop down menu, and wondering why you think that? (if there's data specific to our customers?) We do agree that our current menu, with the "More" menu item being the only one that's a drop down, certainly doesn't work. But if the menu headers are more interesting/refined, then it can accommodate what we need.
The main argument for this is that quite a few other bookstores, other full and busy indies like us, use drop-down menus - [Harvard Bookstore](http://www.harvard.com/), Porter [Square,](http://www.portersquarebooks.com/) [Powells,](http://www.powells.com/) Tattered [Cover,](http://www.tatteredcover.com/), [Strand]([url](http://www.strandbooks.com/)). 
I think the problem with the left hand or righthand menu nav is that it ends up being a big block of text that becomes easy to skim over. And we also lose the overall aesthetic - and most of us do like how the current website looks, and for, the most part, want to work with that design and aesthetic (image heavy). 
What do you think?

**Comment by budparr** [comment]
Only 1.55% of your users clicked on the blog link in the drop-down menu now. The 'about-us' page is not better. Other bookstores hold no sway here as most of them are themes (i.e. pre-formatted stuff that no one used user-behavior metrics) to design.

**Comment by budparr** [comment]
And, this is the best way I can think of to get the entirety of "signed first editions book club" in the visible menu. 

I don't agree that this menu will make people miss things in the menu. I think the opposite is true, partly because one can click through the site with this no matter where they are.

**Comment by shuchibooksmith** [comment]
Okay.
And maybe that will end up being true.But ultimately we really just don't like the look of a side nav.

**Comment by budparr** [comment]
And, I might add, you're not losing the images that you like here. My goal is to make the page not depend on them, not get rid of them. I find there are many posts where the images really don't make sense. The design should accommodate the images, but not force you to use them.

**Comment by budparr** [comment]
I presented a version a while back with a two-layer nav to solve the same problem, and you didn't like that either, so I'm at a bit of a loss where to go with it.

**Comment by budparr** [comment]
Can you give me a sense of what about the side-nav you don't like?

**Comment by shuchibooksmith** [comment]
I think with the side nav it's not something we really see on other sites, and it makes our site look...old? Like we've gone back to an older platform or something. It's just not very visually appealing. I'm not sure how really to describe it. 
I'm going to share the two-layer nav. I really liked that, and I wasn't part of the discussion with the others, so I have no idea why they didn't. Let me see what they say.

**Comment by budparr** [comment]
Okay. I understand that you might feel tied to the current layout, but keep in mind that what design has to do is to solve problems, and that's what we're trying to accomplish here. What's old, if I may, is a standard horizontal navigation (which doesn't make it bad). Newer sites tend to hide the menu altogether, but I don't feel that's appropriate for your audience (based on feedback, particularly when we launched this version of the site) and user research, which I can show you if you're interested. The vertical side navigation is borrowed from application design where there tend to be more involved menus. What you might be responding to is the color scheme, or typography, rather than the menu itself. 

At any rate, I'm happy to carry on the conversation, or drop it altogether. I just caution you to not use other bookstores' sites as a measure.

**Comment by shuchibooksmith** [comment]
Okay. We'll digest everything. If you have examples of websites that use 
the vertical side bar, that might be helpful for us to see.
Thanks!

On 7/8/2016 6:43 PM, Bud Parr wrote:
>
> Okay. I understand that you might feel tied to the current layout, but 
> keep in mind that what design has to do is to solve problems, and 
> that's what we're trying to accomplish here. What's old, if I may, is 
> a standard horizontal navigation (which doesn't make it bad). Newer 
> sites tend to hide the menu altogether, but I don't feel that's 
> appropriate for your audience (based on feedback, particularly when we 
> launched this version of the site) and user research, which I can show 
> you if you're interested. The vertical side navigation is borrowed 
> from application design where there tend to be more involved menus. 
> What you might be responding to is the color scheme, or typography, 
> rather than the menu itself.
>
> At any rate, I'm happy to carry on the conversation, or drop it 
> altogether. I just caution you to not use other bookstores' sites as a 
> measure.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/167#issuecomment-231489983>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AOg4y-mPA0SFdodT6zfAnqAA9TbvMgoSks5qTtJ5gaJpZM4JDXul>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

**Comment by budparr** [comment]
@shuchibooksmith here's some of the research I mentioned earlier, if you care to read it (not required!). This is from one of the most well-known user experience research firms in the industry:
[Hamburger Menus and Hidden Navigation Hurt UX Metrics](https://www.nngroup.com/articles/hamburger-menus/)

Of course, nothing is absolute. This is just food for thought so you can see how we try to make the best decisions for our audience.

**Comment by budparr** [comment]
And, here are some examples of sites with side navigation. I wouldn't necessarily say any of these are applicable to you guys, though.
http://www.landvetterairporthotel.se/
http://www.buildinamsterdam.com/ (both side and top)
http://www.sabemente.de/restaurant
http://www.theliteraryreview.org/ (side and top)
http://ponder.online/ (right side)

So digest, and let me know. Like I said the side nav is just meant to solve some particular issues (many and long navigation items, all of equal importance),  I'm happy to work in a different direction.

**Comment by shuchibooksmith** [comment]
Hi @budparr!
I shared this info with the team, and everyone's agreed to go with the two tier menu that you originally showed us 
https://cloud.githubusercontent.com/assets/15218891/15056126/26f166c6-12de-11e6-8f62-bb4c1d9c416e.png
The two-tier menu doesn't solve some problems (like what to do with "alerts" - harry potter party, ticketed events, etc.) but we figured finally coming down conclusive on the orientation of the menu (two-tiered versus left or right nav) would be a step forward. :)
If we still find that shifting some items up to the top doesn't give us quite the space we need, then we can look into reducing menu items.

The reason they hadn't originally liked the two-tiered was because they didn't want to cut off or shrink the picture. Would we still be able to keep the picture close to it's current size?

**Comment by budparr** [comment]
Yes, that's no problem. Thanks for the feedback.

**Comment by shuchibooksmith** [comment]
Great!! Thank you.
So I guess the next thing is figuring out how to add alerts?
They liked how the tabs floated over the photo on this website, but open to any suggestions you have...
![image](https://cloud.githubusercontent.com/assets/15218891/16742157/74ece588-4774-11e6-8b1e-1abd29a36d75.png)

**Comment by budparr** [comment]
I don't imagine the people in those photos like having their faces covered up.

**Comment by shuchibooksmith** [comment]
ha, no, probably not.

On 7/11/2016 2:35 PM, Bud Parr wrote:
>
> I don't imagine the people in those photos like having their faces 
> covered up.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/sonnetmedia/brooklinebooksmith.com/issues/167#issuecomment-231824370>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AOg4y77_bnaRnydwWG5oDJ81bwvIUwk4ks5qUo0IgaJpZM4JDXul>.
>

-- 
Shuchi Saraswat
Backlist Buyer
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

**Comment by budparr** [comment]
Consistent with this discussion, and the design initiated in #153 I'm just putting a new menu structure up for you to consider. This doesn't have alerts or the [Libro.fm](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/168) information, which I'll circle back around to once I have some more structural work done. 
<img width="1440" alt="screen shot 2016-07-21 at 12 58 46 pm" src="https://cloud.githubusercontent.com/assets/115347/17031606/f5f7dbee-4f42-11e6-90cd-78a3854bafc6.png">

**Comment by zchyde** [comment]
oooh I like this, this mirrors a lot of ecommerce sites I've seen and use

**Comment by zchyde** [comment]
I think separating our more "about me" type links from our more content heavy links makes a lot of sense and is easy to navigate. Are you proposing we get rid of the search field altogether?

**Comment by budparr** [comment]
No, but I do think that it's a bad idea to have a search on one site land on another. That can be disorienting for some, particularly older people and physically challenged people, and we try to be as inclusive as possible. So, I think it should go to a page with the search box, and we can also use that page to display some copy about the store, sell gift certificates, etc.

**Comment by zchyde** [comment]
interesting, ok, because the transition from our website to the aba site could be confusing, people might think they're not still shopping with us because the websites look different.

**Comment by budparr** [comment]
exactly

**Comment by budparr** [comment]
Hello everyone. Apologies for being quiet this past week or two. I had some family issues that have made things topsy turvy for me, so most of the work I've been doing on the site has only been incremental technical refactoring stuff, and less design. I'm getting close to sending you an actual prototype of the new version, but I want to share with you one change that I've made. 

One of my goals with the new site is to make image handling for pages and posts easier and for pages to look better when there's no image. I've long felt that some of the images on posts looked really bad, not through anyone's fault, but that we were kind of asking the image to fill a really large and odd-shaped space. So, this change confines the image to a space that is more predictable and works well over a variety of screens. 

Practically speaking, you'll note that it's a very small change, visually, but with a large impact on how professional the site looks. Whereas before, depending on the size and resolution of the screen, what's visible could change, this will be consistent. 

Here are some screenshots:

<img width="1435" alt="screen shot 2016-08-02 at 11 38 48 am" src="https://cloud.githubusercontent.com/assets/115347/17335043/8f795420-58a6-11e6-9826-bb248d4aa0a4.png">

<img width="1438" alt="screen shot 2016-08-02 at 11 41 48 am" src="https://cloud.githubusercontent.com/assets/115347/17335049/93f122c6-58a6-11e6-84b7-179b46e2416f.png">

**Comment by shuchibooksmith** [comment]
I like it @budparr! I think it looks really clean.

**Comment by budparr** [comment]
Glad to hear that, @shuchibooksmith  - I've also made some typography changes, but I think those will have to wait for the prototype to demo them, because I'm not sure they'll come through well in a screenshot.

**Comment by budparr** [comment]
Posting some screenshots here to highlight some of the things I've been working on. 

1) Color - I'm not married to this color, and I've been fooling around with it, but I'm trying to lighten things up a bit. Feedback welcome.

2) Typography - Note paragraph typeface is now serif. I think it's more readable and warm. 

3) Layout. As mentioned earlier, I want images to look better, and have them consistent and more easy to make consistent. So you'll see that here on the blog posts where each image fits in its own space, and the flow down the page is less rigid, so the images can be natural. It's also seen on the article page, though I've mentioned that already.

_note that the content here doesn't reflect the latest you've posted_

I think I've gotten through some of the more slower going issues where I mock something up and reflect on it, so expect things to go faster and we'll get to a new version soon.

---

Blog page:

---

![screencapture-localhost-3000-blog-1470839352938](https://cloud.githubusercontent.com/assets/115347/17557729/51678ad0-5ee6-11e6-8eaf-d1840757f379.png)

---

Article page

---

![screencapture-localhost-3000-this-week-in-books-2016-06-20-this-week-in-books-dan-brown-keeps-literature-weird-1470839326120](https://cloud.githubusercontent.com/assets/115347/17557737/56d375f6-5ee6-11e6-948b-65e720847a49.png)

**Comment by budparr** [comment]
Forgot to mention, on layout, note on the blog page, the idea is to get more posts on the page visible higher up and let the images make more visible interest, rather than the more linear flow from before.

**Comment by peterbooksmith** [comment]
Hi Bud - I like where you're going with everything.  There is one new development for you, but hopefully this makes things easier.  We are not going to continue the Signed First Editions Club (SFE) into the Fall.  Despite everyone's efforts (yours included), it just has not brought the return we were looking for.   At some point, I will post on github about removing the existing SFE page and references.  Going forward, you can stop thinking about it for this new iteration.  At least it is one less item to consider for now.

**Comment by budparr** [comment]
Okay, @peterbooksmith  - anything I can do to help on that end? Seems like such a good thing!

**Comment by peterbooksmith** [comment]
Thanks @budparr - unfortunately, I don't think so.  Tim, and the rest of us have considered the options, and we just have so much else going on here, that based on the low response so far, we don't see it working for us and we're just moving on.  I don't think the online part or any of your work was a negative factor.

**Comment by zchyde** [comment]
I love it, and I've actually been working on a redesign for the bookmark that is still very much in the early stages of the editing processes but we both kind of went in a similar branding direction, which is cool. If we end up using both these elements, we should coordinate which blue we use in the end, have them on both bookmarks and on website, and think about locking in a specific blue for the Booksmith brand.

**Comment by budparr** [comment]
Okay. Well, I had hoped having it in the main menu would have helped give it day-to-day visibility.

**Comment by budparr** [comment]
> and think about locking in a specific blue for the Booksmith brand.
Yes!

**Comment by peterbooksmith** [comment]
The idea if of a branding discussion gives me a massive headache...but it would be good to work toward that.  Finding one blue for the website and the bookmark could be an approachable starting point, so I will keep that in mind.  I don't think we'll have a final bookmark design for a few more weeks.

Back to SFE Bud, I am sure day-to-day visibility. would have been a positive.  We think the biggest thing is that our customers just didn't embrace this concept.  They have so many things going on in their lives and can come into the store and get great book selections, and I think many people may not want another commitment.

**Comment by budparr** [comment]
Okay @peterbooksmith - didn't mean to belabor the point - just disappointed.

**Comment by zchyde** [comment]
No I know I know. I'm cool, its cool. We'll just talk about some blues. It's very casual I swear.

**Comment by zchyde** [comment]
![448](https://cloud.githubusercontent.com/assets/15219441/17561622/ee5ff094-5ef4-11e6-915a-33ac168387af.jpg)

**Comment by peterbooksmith** [comment]
We were too @budparr - everyone put a lot into it.

**Comment by shuchibooksmith** [comment]
I love how this looks too! I do want to get the audiobooks link somewhere on the menu. Maybe on the top menu bar, near search our online shop. I'll leave that up to you guys. It'd be great for it to link to a landing page within our website, and from there it can link out to libro.fm's bookstore. And we can work with libro on the design. 
re: https://github.com/sonnetmedia/brooklinebooksmith.com/issues/168

**Comment by budparr** [comment]
I've done the events for the most part. Nothing to show there, as the changes are mostly minor, making them more clean. I'm re-working color scheme now and will coordinate with you directly @zchyde and provide you with a full palette I think will you will find workable.

@peterbooksmith Should I go ahead and replace the SFEBC page with the audiobooks page, being that we're a good week-or-two away from launching the next version?

**Comment by peterbooksmith** [comment]
That should work @budparr .  Could you make audiobooks the last link in that row - all the the way to the right?  So...   Events   Blog   Giftsmith   Kidsmith   Used Book Cellar   Audiobooks

**Comment by zchyde** [comment]
Awesome

**Comment by budparr** [comment]
## Updated Design Notes

Alright, the long-awaited prototype. Thanks for being patient with me while I rewrote essentially the entire code-base for the site. It will now be more modular and faster to change to experiment, etc.

_Some of these notes repeat from earlier, but I thought worth mentioning again._

Housekeeping notes: I haven't updated the content to the latest, and there are a few images missing here and there. That sort of thing will be updated. 

You will, of course, note that the home page has the Harry Potter campaign graphic. I left that in to show where it would go when you have a new one. If it's not there, that row disappears and the blog posts move up.

The first thing that will jump out at you is the color scheme. It's much brighter than before. The important thing is that I made it relatively easy to change the color scheme (you could even change it with the seasons!, conceptually, at least). So, I'm not wedded to this, but I think it's necessary be more engaging. My goal here was not only to lighten things up, but also to draw attention to certain areas of the site.

My goal on the home page is to get more things in front of people and make a clearer differentiation between sections of the site. There's less info on the events, but we're showing more of them and now you can, at a glance, see the events (before they were blending in with the blog posts).

On the blog page and Kidsmith pages I also wanted to get more content up where it's visible. You'll note on the home page and Kidsmith page I got rid of the carousel and spread the book covers out. I think that no one would ever see the images on the carousel that weren't immediately visible, so displaying them all is more effective. They're also higher up on the page.

Also note, as mentioned earlier. I changed the typography on interior pages to a serif font, which is more readable.

The banner images should be easier to maintain with this style, and I'm also working on a slightly easier workflow for adding the weekly bestsellers (where you won't have to put in ISBNs, just select the titles from the list).

As you can see, I've taken out SFE and replaced it with the Audiobooks page from issue #168. I took the page copy from the example in that issue, but it can be changed.

So have a look! I'm open to discussion and changes, naturally, so don't take this prototype as take-it-or-leave-it.

http://brooklinebooksmith.netlify.com/

**Comment by peterbooksmith** [comment]
Hi @budparr.  Sorry I haven't commented yet.  In general, I like this and the changes make sense to me.  A few minor questions, thoughts, in order...

With the Harry Potter graphic/campaign spot - what if we don't have a relevant campaign/  Maybe that's for us to figure out, I guess a recent/relevant blog post could always occupy that space for a little while/  One would think we would always have something "special" to go there, but what if we don't?

I am fine with the bright & lighter colors.  Do you think that makes our storefront photo look even darker or too dark?  I am sure we could redo that, though I'd love to avoid it.  Just asking your opinion.

I like the book cover images for bestsellers they way you've done them.  Minor thing, for the Kidsmith page, we should probably just do 6 bestsellers so that they're all on one line?

These are minor things/questions, maybe can be figured out later.   I like the design/direction, so what next?  I will show this iteration to Dana and Lisa.  As always, it is possible that a number of differing opinions could arise, but I want to try and manage that best as possible so that we can get this done.

**Comment by budparr** [comment]
Thanks, @peterbooksmith  - so most of the things you're talking about are content-driven. So, for instance, if you don't have a campaign right now, that row goes away and the blog posts move up to fill the space. The storefront photo can be changed at any time. The Kidsmith book covers, which I agree, fewer is better, is just a function of how many you put in.

So, yeah, gather everyone's thoughts and let me know. One thing to keep in mind, is this isn't so much a thumbs up/down conversation, but a bit more specific than that. Everything is flexible, and don't let the color get in anyone's way, because that can easily be changed.

**Comment by peterbooksmith** [comment]
Got it.  I will work on showing this to the various parties tomorrow, maybe Thursday.

**Comment by peterbooksmith** [comment]
@budparr I just went over this with Dana and Lisa.  Three things they feel strongly about - 

1. on the home page, could we get rid of the white "brookline booksmith" going across the banner image?  On that page, with it in that location, and at the top right in blue, and with booksmith in the actual photo, it seems a bit much.  Also, we think the white lettering makes that banner image look darker.

2. The blue (all of the blue) should be closer to a royal blue.  This one is too light.  The brightness is good, but we all think it needs to be a darker shade.  I am looking at some Pantone blues, and maybe something closer to PMS 286?  Not sure if that would be too dark?

They also kept mentioning the darkness of the banner images, but they look the same in the current live iteration.  Possibly changing the blue and removing the white brookline booksmith from the home page would help that appearance?

I realize this is also more content-related, but those are the things they keyed on.  Layout-wise, I think we are all ok with the changes.

**Comment by budparr** [comment]
Hi @peterbooksmith 1) is an easy fix. 2) I should have for you by tomorrow morning (it's an easy thing, but I'll likely need to fiddle with the colors a bit.

re: the darkness of the images. We can fiddle with that too, but the copy on top of the images is most important to your readers who really just want to know where they are on the site.

**Comment by budparr** [comment]
@peterbooksmith that color ended up looking a bit purplish on the web. I'm going to experiment with some other colors and show you what I come up with.

**Comment by peterbooksmith** [comment]
@budparr - I can see how that might happen.  We are looking for is something is both bright but closer to a solid, royal blue but definitely not purple. Maybe something in between your choice and PMS 286.

**Comment by budparr** [comment]
Hi @peterbooksmith  - I'm using a color here that is about midway between the two. The color is very strong so I did a lot of fooling around with it so that it wouldn't overpower the page, so I pulled-back on it a bit (it's still strong, but I think this works). Let me know what you all think. I really want to keep it as clean as possible. I'd love to replace that image on the home page with something less distracting. It's a nice image, but it's busy and not really what we want people to pay attention to (we want them to see the blog posts and events).

I also lightened the images a bit and I took away the promo (Harry Potter), so you could see the page without it.

<img width="1440" alt="screen shot 2016-09-22 at 12 03 25 pm" src="https://cloud.githubusercontent.com/assets/115347/18756168/e10f4266-80bc-11e6-89c9-0144a1354eee.png">

http://brooklinebooksmith.netlify.com/

**Comment by budparr** [comment]
By the way @peterbooksmith I don't mean to dictate the color. If that color you mentioned, or some other color is what you want for you brand color, then it's up to me to figure out how to make it look good on the site. Just want to be clear about that, as I see it looks like I was saying otherwise, because I wasn't allowing that you might have decided on a color outside of the website context.

**Comment by peterbooksmith** [comment]
@budparr this blue looks better, both Dana and Lisa like it, so let's go with that.  We also understand what you mean about the busy-ness of that banner photo.  We're going to look at some of the others we took or have and see if there is something else we could use.  Otherwise, we can continue to proceed.

**Comment by budparr** [comment]
@peterbooksmith - Awesome. I'll update the content to the latest and get this version live. I'll make the transition at a low-traffic time to make sure that it's smooth for users.
