### ISSUE TITLE
Try making banner white with blue copy for store name

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#17]
In one version, I think in between versions, Zoe and I noticed a white banner with a blue Brookline Booksmith. We really liked that, and are thinking since we don't have a designed logo, and the store name is our current logo, that the store name being blue would be more important than the banner. A white banner might also open up space.

**Comment by budparr** [comment]
Yeah, I can do that. Funny, I didn't put that version into the last mix because I didn't think you'd like it. I'm learning not to underestimate you guys!

The next version I'll make white banner and we'll see if we like it. I usually find that I try things out and only by having them around for a bit is a good test.

**Comment by budparr** [comment]
Here's a version with white. Honestly, I'm not sure it works, but that's just my first glance. It looks best on pages like the about page.
http://brookline-151028whitebanner.surge.sh/

**Comment by shuchibooksmith** [comment]
this is what came up! (!!)

![ah](https://cloud.githubusercontent.com/assets/15218891/10805847/520fdeea-7da7-11e5-9889-d35f2b521002.png)

**Comment by budparr** [comment]
Yeah, I had a problem with that too. For me the fonts weren't showing up. Not sure if it's the service I use for these, or what. I'd try to load it a few times, or perhaps try a different browser. If it's not corrected by morning I'll figure something else out.

**Comment by budparr** [comment]
I think I fixed it, if you want to try it again.

**Comment by shuchibooksmith** [comment]
ah-ha, yes i see! and yes, i also notice that it doesn't *quite* work. looks very bare. hmmm
