### ISSUE TITLE
Kids Bestsellers?

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#170]
This might be a dumb question, but where did the Children's bestsellers carousel go?

**Comment by peterbooksmith** [comment]
Hello,
  
 I will not be working on Monday, August 29.  Please know that while I will be in the store August 30-September 2, I will be working with new employees and may not be available right away.  I will reply to your email as soon as possible.  Thank you.
  
 Peter Win
Assistant Manager / Co-owner
Brookline Booksmith
279 Harvard Street
Brookline, MA 02446
617-566-6660

**Comment by zchyde** [comment]
Hey Bud, any movement on this? It looks like the kids events arent showing up on the kidsmith page when I mark them as kids events either. Poor kids page!

**Comment by budparr** [comment]
I'll have a look. Sorry - didn't mean to ignore - getting ready to send over the newer version and got caught up in that rewrite.

**Comment by budparr** [comment]
Okay, this is set. Somehow the page lost its layout. I moved the layout field to the config file, so it won't happen again. Thanks for pointing it out!
