### ISSUE TITLE
Fixes to new interation

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#173]
@budparr @zchyde - here is a list of (mostly small) things we see that need fixing.  @shuchibooksmith compiled most of this and I added a couple of notes. (indicated by **)

- [x]  homepage - list all weekly bestsellers (7 hcs, 6 pbks) - ** It looks to me like 6 images across the page is what fits best.  Maybe that be changed, maybe not.  I think it would be fine if we just did 6 HC and 6 PB bestsellers, so long as it is an equal #.

- [x]  homepage - on the main menu, it should be Audiobooks (one word) not Audio Books 

- [x]  events page - the share buttons for each individual event have little numbers in the boxes next to them, i originally thought they were for the number of shares, but they all have the same number

- [x]  blog page - all the blog posts have "th-" next to the author's name

- [x]  blog post - when you open up an individual blog post, want the author's name somewhere there

- [x]  homepage - search online shop should go to: http://www.brooklinebooksmith-shop.com/ - ** I think I raised this once before and Bud said that it had to go to the search page, but I don't recall that exactly.

- [x]   ** Our icons for Facebook, Twitter & Instagram used to be on the Homepage or maybe every page?  I don't remember exactly, but those should appear somewhere.
- [x]   ** Kidsmith bestsellers - currently there is one duplicate cover (Minecraft) and we should have twleve total books so that there isn't a blank spot at the end.
- [x]  individual event - 10/11 Patti Smith - the font changes towards the bottom, gets smaller
- [x]   individual event - Thurs 10/7, image for The Muralist is broken (I think they just changed the cover for the book so that might be why)

- [x]  blog page - some of the banner images aren't showing up in the list of blog posts (but when you click on it, the banner image comes up just fine)

- [x]   ** Kidsmith blog posts - underneath the bestsellers, where "more blog posts" appear, those are all of our blog posts, not just the kids-related ones.  Should they be just kids?  I don't feel strongly about that, but I think previously they were just the kids ones.

As I said, I think there are all minor fixes.  Overall, I think response has been very positive, and I am happy with the new appearance.

**Comment by budparr** [comment]
Thank you, @peterbooksmith and @shuchibooksmith - I should be able to knock these out pretty quickly.

**Comment by budparr** [comment]
@shuchibooksmith @peterbooksmith These are fixed, with the exception of one, about the blog images, which I've opened a separate issue for. Thanks!
