### ISSUE TITLE
Fix times on *all* events

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#174]
All of the events are currently coming up as a 5:41pm start time. It was fine this morning, so I think there's some glitch...

**Comment by shuchibooksmith** [comment]
Make that the date AND time...All coming up as Monday, October 3rd at 5:41pm...

**Comment by budparr** [comment]
Sorry, I've been working on some stuff, and didn't realized that where I changed it effected those. BRB

**Comment by shuchibooksmith** [comment]
Thanks @budparr !

**Comment by budparr** [comment]
should be fixed now.
