### ISSUE TITLE
Fix Images in Gwen's Blog Post

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#176]
I just posted a blog post for Gwen and the images are coming up funny. I'm not sure if you have some guidelines @budparr  or @zchyde on how I should handle image heavy posts?

**Comment by budparr** [comment]
In the editor, type a `---` in between sections with the images/copy. I have the images set to float to the left of the copy, so it can be a bit weird without that.

**Comment by shuchibooksmith** [comment]
perfect, will do, thanks!

**Comment by zchyde** [comment]
Also, in general, I need a longer turnaround for Gwens posts. Her posts are really image heavy and she uploads them in absolutely enormous sizes, it takes me a while to gather, resize and compress them.

**Comment by zchyde** [comment]
These are things I can do after the blog is uploaded but it will occasionally change the layout slightly, I guess turnaround isn't the right word since I can change the images after the post is published, but just know that her posts specifically go through a longer process then the rest of them.

**Comment by shuchibooksmith** [comment]
@zchyde good to know, thanks!
