### ISSUE TITLE
Swap "Upcoming Events" & "Latest from the Blog" on homepage

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#179]
@budparr as we discussed offline, we definitely want to swap the placement and appearance of "Upcoming Events" & "Latest from the Blog" on homepage.  I realize this will take some reformatting and/or reconfiguring.  Looking forward to seeing what you come up with.

**Comment by budparr** [comment]
Thanks for initiating the issue, @peterbooksmith  - and, to reiterate some specs:

- [ ] Blog posts listed as the events are now
- [ ] Events in larger space, but may look different than posts do now.
- [ ] Images to use. 
  - book covers, likely. 
  - required to show entire cover (not stylized) 
  - What to do with multiple covers
  - author photos a possibility

**Comment by peterbooksmith** [comment]
Yes.  With some more thought and talk, I do think book covers, not author photos, and I also think showing the entire cover (not stylized).  I think having multiple stylized covers in this area for this purpose might look strange, and I know that events people, authors and publicists prob want to see entire covers.

**Comment by shuchibooksmith** [comment]
just wanted to chime in real quick. i understand not having the book covers be stylized for the homepage. but when we open up to the individual event's page, it might be nice to have a banner image that's maybe a close up of the cover? a little more stylized? this is what author's share, and what we often link to, and if we're featuring events more prominently, it might be good to have these pages look a little jazzier (for lack of a better word). :) thoughts?

**Comment by budparr** [comment]
@peterbooksmith FYI, I'll likely release this for your review on Monday. I've been going through a lot of iterations to streamline the look of events for the home page and haven't come up with anything radically different than the way we're displaying them now. It's otherwise set. Have a great weekend!

**Comment by peterbooksmith** [comment]
Sound good Bud, looking forward to seeing it.  Have a great weekend as well.

**Comment by budparr** [comment]
Hi @peterbooksmith, 
My first thought on this was to format the events in a more compact way than they are in the events page. I've tried several iterations, but haven't yet come up with something that does as good of a job of displaying the events clearly. I haven't counted it out, but rather than delaying getting a more fundamental change done (switching the prominence of events over blog posts), I thought it'd be a good idea to push this verision out, and then I can iterate on it from there.

Here's the prototype:
http://2016-10-31-v1-bbs.surge.sh/

**Comment by peterbooksmith** [comment]
I understand.  You've probably this, but what about just having the cover image with the author's name, book title, date and time?  For example - Monday, Oct 31 - 7:00 PM  Teju Cole - Known and Strange Things: Essays

I only mention b/c one thing we definitely like about the current iteration is that everything on the home page is closer to the top, so less room to scroll down.  Does that make sense?  Of course, I realize asking for this switch meant it might not work out exactly the same way.  I'm fine with proceeding as you suggest, and trying to iterate it from there.

**Comment by budparr** [comment]
Totally. I didn't think that option would be on the table. I'll work something up.

**Comment by budparr** [comment]
So this iteration removes the primary copy. I didn't put a link to read more, trying to be less cluttered, but probably could use that. http://2016-11-01-v2-bbs-homepage.surge.sh/

**Comment by peterbooksmith** [comment]
I like it.  If people really push for a "read more" link, I will explain the less cluttered approach, as I def support that.

**Comment by budparr** [comment]
Hey @peterbooksmith Was just thinking that maybe we color code the events. We'd put a key at the top, but we'd have a color for kids, book clubs, regular readings, paid events, whatever. What do you think? Might give readers an easy 'at a glance' at the events that interest them. If you like the idea, I'll open a separate issue for it.

**Comment by peterbooksmith** [comment]
@budparr things are looking good.  That's an interesting idea about the color coding, guess we should see what i would look like.  One thought is that too many different colors might be too much, but what do you think about that? 

Separate thing, and I can open a new issue for this, but could we also have a heading above the events that says "Upcoming Events"?  The same size and style text as the weekly bestsellers might even work?
