### ISSUE TITLE
Todays event

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#180]
@budparr Bud I can't get todays event to show up on the website, am I doing something wrong?

**Comment by budparr** [comment]
I'll look

**Comment by budparr** [comment]
what's the name of the event?

**Comment by zchyde** [comment]
Elissa Altman - Tref

**Comment by budparr** [comment]
Okay. I found the issue. I recently changed some of the events code and need to fine tune something. Shouldn't be more than a few minutes.

**Comment by zchyde** [comment]
Thank you!

**Comment by budparr** [comment]
okay. should be set in a minute. pardon my idiocy

**Comment by zchyde** [comment]
Every time its a code problem it means its not me just, like, not having checked "publish" or something. Thanks for the quick fix!

**Comment by budparr** [comment]
It's always nice when it's not your fault :)
