### ISSUE TITLE
Question about timing of events display

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#181]
Hi @peterbooksmith , and @zchyde  (not copying Shuchi because I think she's still on vacation).

I've been fine tuning events a bit and have it set currently so that if an event scheduled for 7:00pm, it will not show at 7:01 (that is, of course, if the site is built at that time, which it's not usually, so in most cases the event would still be there for a while). I've set the site to build automatically every morning, but but I'd like to set this up so that in all circumstances events show and go away when it's appropriate. Would you say that to have an event show up for how long? 2 hours, 3, 4, after it's begun? 

Again, in most cases, the event will show up until the site is built the next morning, which I think is good, but I want to allow for those edge cases where someone might possibly edit the site in the evening. 

Thanks!
Bud

**Comment by peterbooksmith** [comment]
@budparr  - I think having an event up for 1-2 hours after is starts is fine.  Almost all of our events run for an hour.  It for any reason it is easier to make it more time than that, that's ok too.  Yes, Shuchi is away until next Monday (11/7).  Thanks!

**Comment by budparr** [comment]
Thanks!
