### ISSUE TITLE
Improve Storytime graphics

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#182]
Hey, @zchyde. Any chance we can get a better/bigger graphic for the book clubs and story time? These are the only ones I see.

http://images.brooklinebooksmith.com/kids_storytime_web.jpg
![](http://images.brooklinebooksmith.com/kids_storytime_web.jpg)

http://images.brooklinebooksmith.com/breakwater.jpg
![](http://images.brooklinebooksmith.com/breakwater.jpg)

http://images.brooklinebooksmith.com/bookclubicon.jpg
![](http://images.brooklinebooksmith.com/bookclubicon.jpg)

**Comment by zchyde** [comment]
We can, I probably won't be able to get them done until tomorrow at the earliest. These icons don't exist in a larger format so I'll have to make new ones, which is fine, will just take more time then I have today.

**Comment by budparr** [comment]
No rush! 

Make them at least 350px wide, and I think the square aspect ratio is fine.

**Comment by budparr** [comment]
And thank you!

**Comment by zchyde** [comment]
ok cool, will do!

**Comment by zchyde** [comment]
What do you think of these? I don't want them to be too busy, that's often my downfall
![artboard 1 copy 2bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19973791/a3f53e96-a1bc-11e6-8280-f6541f23315f.png)
![artboard 1 copy 3bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19973793/a400752c-a1bc-11e6-96f1-e478aca55d25.png)
![artboard 1bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19973794/a40293de-a1bc-11e6-8358-936f5f2151a4.png)
![artboard 1 copybsmithicons](https://cloud.githubusercontent.com/assets/15219441/19973792/a4005b78-a1bc-11e6-92d4-45816ade4081.png)

**Comment by budparr** [comment]
I like them. Do you think the copy should be centered?

**Comment by peterbooksmith** [comment]
I'll leave the visuals up to the two of you, but I think the Between the Lines one prob needs to be centered.  The Breakwater one kind of looks ok the way it is, but if all others are centered, than maybe just for consistency sake.

**Comment by zchyde** [comment]
I'm not opposed, I can center them, hold on one second

**Comment by zchyde** [comment]
![artboard 1 copy 2bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19976876/d526fb2a-a1c7-11e6-8eb6-b9ebff483ac2.png)
![artboard 1 copy 3bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19976877/d529ae24-a1c7-11e6-925e-f97ffef40a90.png)
![artboard 1bsmithicons](https://cloud.githubusercontent.com/assets/15219441/19976874/d524357a-a1c7-11e6-88d7-039250a916a5.png)
![artboard 1 copybsmithicons](https://cloud.githubusercontent.com/assets/15219441/19976875/d5247184-a1c7-11e6-88b0-d29f155bfe78.png)

**Comment by peterbooksmith** [comment]
yes - and thanks, these look good

**Comment by budparr** [comment]
@zchyde Can you send me a zip file with hi-res versions, please?

**Comment by budparr** [comment]
I'm going to close this. I've added these to the site (in the "programs" collection). @zchyde whenever you get a chance, perhaps you can take make them into jpegs and run them through the compressor (hopefully they won't lose color) and swap them out, so they're nice little files. I love PNG format because it retains colors nicely, but the file sizes tend to be rather large.

**Comment by zchyde** [comment]
I can totally do that, its not wrong in the programs section but it looks like "between the lines" is showing up on the book club events on the homepage and on the events page?

**Comment by budparr** [comment]
> it looks like "between the lines" is showing up on the book club events on the homepage and on the events page?

Fixed. Thanks for the catch.

**Comment by zchyde** [comment]
We've got another small glitch - images come up correctly on homepage but 11/14's book club has "between the lines" graphic on events page

**Comment by budparr** [comment]
I'll check it out.

**Comment by budparr** [comment]
Fixed now.

**Comment by budparr** [comment]
@zchyde How would you feel about creating some variations on those images? Maybe a large one for the event's landing page (so same size as any banner graphic), and maybe a smaller one for the home page (i.e. not as tall, the width is fine). Thoughts?

**Comment by zchyde** [comment]
Yes I can definitely do that, will have those done today
