### ISSUE TITLE
Create individual pages for Programs

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#184]
Purpose is to show the recent past books discussed/read. 

cc/ @peterbooksmith

**Comment by budparr** [comment]
ref PR #187

**Comment by budparr** [comment]
I've added programs pages to events, @peterbooksmith. You'll see them listed on the left-side column of the events page. Still some things to do on the content-entry side to display past book discussed. I think this will give your customers a sense of the scope of your regular programming. Let me know what you think.

**Comment by peterbooksmith** [comment]
Looks good @budparr .  One change please - we're no longer doing the BASH Poetry Reading Series so can you just disappear that?  Thanks.

**Comment by budparr** [comment]
Thanks, @peterbooksmith. I unpublished BASH.
