### ISSUE TITLE
Fix photos on event partnerships page

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#186]
https://www.brooklinebooksmith.com/the-booksmith-event-spaces--partnerships/

Tim emailed me, "Noticed the photo links are broken".  I honestly don't remember what it is supposed to look like.  Additionally, in the coming weeks we may want to update some of the info on this pages.  Thanks.

**Comment by budparr** [comment]
Hmm. They're on the images subdomain. @zchyde any thoughts?

**Comment by budparr** [comment]
Actually, think I fixed it. I've got the images showing, but have to have a quick look at the slideshow.

**Comment by budparr** [comment]
This is fixed now. Closing. It was an issue where the images weren't resolving to https (which we use for security), so I tweaked them a bit.
