### ISSUE TITLE
Replace 'Programs' in Nav Menu - put 'Kidsmith' instead

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#19]
I know you felt strongly about 'Programs' but we're thinking now that there won't be enough fresh content for 'Programs.' And our 'Kidsmith' (kids section) is pretty vibrant and active. They blog and they have their own Twitter feed, and the story times can go here. What do you think?

**Comment by budparr** [comment]
I'm totally fine with that and love have an area devoted to kids. 

Content (I'm guessing): Blog posts categorized as kids, twitter feed (at least a couple of the most recent posts), and the kids related events.

One question - right now on the home page we have blog posts, most of which are kids. You mentioned earlier that you want the newsletter copy to go there (correct?), which I see essentially the same thing as a blog/news post. So, do you want the kids stuff that's on the home page now (events/posts) only on the kidsmith page? Or, in both places. The reason I ask is that I'd be inclined to keep them separate, but if you don't have enough non-kid content the home page could get boring.

**Comment by shuchibooksmith** [comment]
For now, both places. The idea (hope, ideal) is that we are generating much more content come the new year, and then the kids blog posts can transition over to the kids page.

How about the kidsmith page just show all of the full blog posts, one on top of the other? So it will read more like a blog. And then the Twitter feed on the right. AND the "new releases" covers, which I mentioned in a new thread, would be represented somehow here, and the kids team could feature their new releases.

I think for now that would work for content, and maybe they will decide to do something different with it in the future, or just post about new releases more frequently.

**Comment by shuchibooksmith** [comment]
here's the kidsmith twitter:
https://twitter.com/kidsmithbooks

**Comment by shuchibooksmith** [comment]
Before we go live:
can you put "kidsmith" under the "more" tab and move giftsmith up so it's one of the main menu items?
