### ISSUE TITLE
Kids events - need additional category

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#190]
To get kids events to show up on the kids page I've been tagging them as a storytime or a book club even if they aren't. It wasn't an issue before but now that we're labeling those events, I need an additional label that will send the event to the kids page when the event is neither a book club nor a read aloud storytime.

**Comment by budparr** [comment]
The "program" is "childrens-story-time" that I have loading on the kidsmith page. So, you want a more general category then, sounds like. Working on it.

**Comment by budparr** [comment]
Now choose the category "Kidsmith" and they will show up on the kidsmith page. Note you have to do that for everything (i.e. the category is the thing that makes it show up on that page, not the program).

**Comment by zchyde** [comment]
Thank you!
