### ISSUE TITLE
add new blogger to list

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#204]
can you add the following names to the list of bloggers?
Travis
Kiersten

thanks!

**Comment by budparr** [comment]
I'm on a train to #AWP right now, but @zchyde should be able to from the CMS

**Comment by shuchibooksmith** [comment]
You're going to AWP!!!! awesome. have so much fun.

**Comment by budparr** [comment]
Ah, yeah. I'm speaking on a panel about design stuff. Should be fun.

**Comment by zchyde** [comment]
Yeah I can take care of this in one second.

**Comment by zchyde** [comment]
All done!
