### ISSUE TITLE
image size in Gwen's blog post

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#205]
@budparr, the images in this blog post - https://www.brooklinebooksmith.com/2017/02/21/the-truth-about-blind-dates/
are publishing much smaller in the actual blog post. When I was proofreading the post, the images were larger (which is necessary, because you need to be able to read the text). Can you fix this?

**Comment by budparr** [comment]
All set, @shuchibooksmith Have a nice night.
