### ISSUE TITLE
bring back 'staff recs' page

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#206]
hello! this has been on my to do list for a while - I'd love to bring back our staff recs page. here's what it used to look like on the old version of the site.
http://www.brooklinebooksmith-shop.com/staff-picks

ideas of how best to do this, @budparr ? ideally, it'd be great to somehow sync up bloggers names with their staff recs pages...

**Comment by peterbooksmith** [comment]
I am interested in any idea you might have about this Bud, but before we really proceed, I want to talk with Dana and Lisa to see if we definitely want this.  Don't mean to cut you off, Shuchi, but I want to consider this first.

**Comment by budparr** [comment]
FYI, we have a previous [discussion](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/111) on this. I definitely like the idea of recommendation pages though.
