### ISSUE TITLE
fix numbering on alex's blog post

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#208]
hi @budparr -
can you fix the numbering on this blog post? i can't figure out how to do it..
https://www.brooklinebooksmith.com/kidsmith/2017/03/02/how-to-impress-us/

**Comment by peterbooksmith** [comment]
I will not be in the store February 28-March 2.  I will be returning on Friday, March 3.  
 Thank you,
  
 Peter Win
Assistant Manager / Co-owner
Brookline Booksmith
279 Harvard Street
Brookline, MA 02446
617-566-6660

**Comment by budparr** [comment]
That was strange, @shuchibooksmith I fixed it for now and see why it was doing that.

**Comment by shuchibooksmith** [comment]
great, thank you bud!
  
    Shuchi Saraswat
Brookline Booksmith
279 Harvard Street
Brookline, Massachusetts 02446
617.566.6660
www.brooklinebooksmith.com

 P Please consider the environment before printing this email.   

   

  

----------------------------------------
