### ISSUE TITLE
adjust cover image in Alex's blog post

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#209]
sorry, @budparr, me again, same blog post as before. alex uploaded an image to her blog post, but it's now showing up as the banner image? can you see what's up? i just want to share the post on facebook and the banner images are nice on there.
thanks!

**Comment by zchyde** [comment]
Hi Its me, I'm compressing images now thats its gone, please hold

**Comment by shuchibooksmith** [comment]
OH okay thanks @zchyde xoxo
