### ISSUE TITLE
Kids Events

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#212]
I could be wrong, but I don't think the kids events are showing up on the Kidsmith page, programs nor book categories.

**Comment by shuchibooksmith** [comment]
Thanks for your email. I will be out of the office until Saturday, March 18th. I'll get back to you shortly after I return.

**Comment by budparr** [comment]
Should be all set. I think it was a result of a software upgrade but I'm checking to see for sure. But at any rate, it's fixed now. Thanks for pointing it out and hope you're managing the weather okay.
