### ISSUE TITLE
Bookclub page needs updating

### ISSUE THREAD

**Issue by peterbooksmith** [sonnetmedia/brooklinebooksmith.com#215]
https://www.brooklinebooksmith.com/programs/book-club/

Right now there is no bookclub book listed.  This might just be an error?

**Comment by budparr** [comment]
I don't see any upcoming events that are classified as bookclub. So what is the behavior you are expecting?

**Comment by peterbooksmith** [comment]
https://www.brooklinebooksmith.com/events/2017-05/brookline-booksmith-book-club/

This event should be classified as bookclub, so maybe that's the problem?

**Comment by budparr** [comment]
Yep. That was it. I updated the entry and it's set now.
