### ISSUE TITLE
fix weekly bestsellers image link

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#217]
hi, @budparr !
i created some new books for the weekly bestsellers, and it looks like their images have broken links. i had to grab the cover of 'shattered' off the web because the final cover isn't up on the aba page, but even the ones i created with the aba page cover link seem to not be showing up. what did i do wrong here?

**Comment by budparr** [comment]
Just looks like maybe you didn't save the entry? Not sure, but everything is working fine. To test, I put in the cover for The American Spirit, and Shattered (the aba one, so you might have to change it) and they're showing up. Give that a try and let me know if you continue to have any issues.

**Comment by shuchibooksmith** [comment]
okay so i add the link in, but then i can't save - the save disk icon is greyed out, so i can't click on it?

**Comment by budparr** [comment]
I just put in This Fight is our Fight and it seems to work. Can you send me a link that you're trying to put in? 

And just to be sure, this is where you're trying to do it (screenshot):
![screen shot 2017-04-24 at 2 34 21 pm](https://cloud.githubusercontent.com/assets/115347/25352869/6ee1674a-28fb-11e7-882b-39dce8632624.png)

**Comment by shuchibooksmith** [comment]
@budparr nvm, figured it out!

**Comment by budparr** [comment]
Awesome!
