### ISSUE TITLE
missing paperback cover for Leaving Russia

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#218]
Hi @budparr! We're trying to create a new book record for the paperback of Leaving Russia (9780815610885)  and we want to link to that cover, but the ecommerce site doesn't include a book cover image. What's the best thing to do so that if someone clicks on the cover it'll still go to our website? 
(this is the book for the may 24th event).

Thanks!

**Comment by budparr** [comment]
you can get a cover from the internet. Just add the ISBN in the book entry and it will go to the right page. If there's no (appropriate) cover at all, I'd suggest adding the link to the buy page in the copy of the event.
