### ISSUE TITLE
Signed First Editions Club

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#22]
just adding this here...

 We haven't done anything like
this in the past, but you might be familiar with it. Basically,
customers sign up to be a member of the club, they pay us a monthly
amount and each month we send them a signed copy of a new book out in
hardcover. They put a lot of faith in our taste, and we hopefully get
them something great before the rest of the world realizes it's great.
This is perfect for the web as we can attract customers who used to live
in the area and want to continue to support our store.
A few bookstores already do this-
http://www.parnassusbooks.net/first-edition-clubs
http://www.greenlightbookstore.com/firsteditionsclub

It will be a recurring-billing-membership requiring us to acquire and
store credit card information. Here's a note from Tim, our Controller -
If he has any experience working with companies that integrate with
retail websites and help manage such a thing, I'd be all ears. Examples
of potential companies:
http://developer.authorize.net/api/reference/features/recurring_billing.html
https://paysimple.com/

**Comment by shuchibooksmith** [comment]
Bud, here are some examples of bookstores that have a signed first editions club-

● Harvard Bookstore (est. 200 members) *

○ http://www.harvard.com/clubs_services/first_edition_club/

● Lemuria Bookstore (est. 250‐300 members)

○ https://lemuriabooks.com/first‐editions‐club/

● Square Books (est. 220‐250 members)

○ http://www.squarebooks.com/signedfirsts

● Powell’s City of Books (est. 2,000...no subscriptions available at this time)

○ http://www.powells.com/indiespensable

● Parnassus Books (est. not known) *

○ http://www.parnassusbooks.net/first‐edition‐clubs

● The Odyssey Bookshop (est. 250‐300 members) *

○ http://www.odysseybks.com/first‐editions‐club‐faq

● Greenlight Bookstore (est. not known)

○ http://www.greenlightbookstore.com/firsteditionsclub

**Comment by budparr** [comment]
One crinkle: Peter said we can't do any commerce on the new site. So can you set up the commerce bit on the ABA site? Pretty much this would just a page where we send people to your aba site, methinks.

**Comment by shuchibooksmith** [comment]
Right. Well I'm wondering since this is kind of it's own entity entirely, if we can use the ecommerce through the site rather than the ABA. @peterbooksmith and I are sitting down next week after he gets back from Winter Institute to discuss everything in greater detail, but just for your reference (and ours @peterbooksmith) here is Harvard's sign-up for their first editions club. Looks like it bypasses ABA-
https://secure.harvard.com/signedfirst.html

**Comment by budparr** [comment]
Okay. We can get started though, if you have your first selection.

**Comment by shuchibooksmith** [comment]
We don't yet, actually! Tim is still waiting to get the whole thing approved, he has a big proposal and a lot of details to iron out first. I'm just going through all of my "January projects" and adding them into the queue. :)

**Comment by budparr** [comment]
Okay. Ready when you are. Might be good to throw out a blog post when you've gotten to a point of confidence on it. Great way to get newsletter signups (in fact, if we move to mailchimp we could create a segment for FEBC people and have them sign up to that list). Great way to gauge interest.

**Comment by shuchibooksmith** [comment]
yes! great idea. one of our bloggers is going to try to post something over the next couple of weeks as our guinea pig, and then we'll hopefully be blogging again in full force!

**Comment by budparr** [comment]
:clap: Glad to hear that!

**Comment by shuchibooksmith** [comment]
Hello Bud! I'm not sure where we left on this but Tim is getting ready to propose the signed first editions club and he wanted to know what options you have as far as PCI compliancy. One of his big concerns is that he's thinking about the price changing per month. And about three core groups. 

Group 1 - IN STATE - cost of book + tax (in-store pickup)
Group 2 - IN STATE - cost of book + tax + shipping
Group 3 - OUT OF STATE - cost of book + shipping (no tax)

So the cost would not only vary each month depending on the cost of the book, but would then vary within these three groups. It gets a little complicated, so wondering if that's something one of the PCI compliant carts (not sure of the right term here) would be able to manage.

We're also thinking of just going with a flat fee, though Tim seems keen on changing it since most signed first editions clubs work that way.

Thoughts?

**Comment by budparr** [comment]
PCI compliance is something you have to do when you take credit card data on your site. Something we're not doing. PCI compliance is _very_ expensive. Even if we were processing the transactions from our site we'd use a third-party service to process the credit cards. 

Next thing is that Peter said rather explicitly that we'd not be doing any commerce on the new site, that instead you'd be running transactions through your existing setup with the ABA. Let me know if that's changed. 

So let me know where things stand with regard to the commerce bit. If you're using a third-party commerce system on the new site the pricing issues are no problem.

**Comment by shuchibooksmith** [comment]
Since this is a subscription based club, and completely separate from our usual e-commerce operations, I think it's something we could use a third-party system for. Tim, who you briefly met, is going to handle that part internally. Tim is actually still working on a proposal for this, so we can't even move forward until we get official approval. But if you have the names of a few e-commerce partners in mind, he needs this general info

-cost per month for approx. 200 members
-how long you think it'd take you to set us up with this (I imagine not very much time, it'd involve building a page and then us giving you all the information you need for that page, so the time there really depends on us).

I'm happy to get the numbers info for him if you can tell me a few e-commerce partners to look into. 

Thanks!

**Comment by peterbooksmith** [comment]
Bud - the proposed signed first editions club would be something different, and we would want to look into handling that through the new site.  Sorry, I could have mentioned this before now.  We want to continue using the ABA Indiebound site for our regular ecommerce, but this club could and should be handled separately if possible.

**Comment by budparr** [comment]
Great. So we need two things. A payment gateway and a commerce provider. 

I recommend Stripe for payment gateway. I've been using Stripe for years (you even pay me through Stripe): https://stripe.com/

So this is the provider I use for the commerce bit. The site is geared for developers, but I think you should get an idea of what they're about:
https://snipcart.com/

The beauty of Snipcart is that it's what we call a _thin layer_, meaning it doesn't require expensive and invasive software additions and easy to stop using.

Both of these are inexpensive and in line with the industry on pricing. I've used them both.

I can give you detailed instructions whenever you're ready, and also happy to discuss these choices in more detail.

**Comment by peterbooksmith** [comment]
@budparr not asking for further action on this yet, but I think we are getting close.  Assuming we go with Stripe and Snipcart, when we decide we want to prioritize this, what info will you need from us? Can you estimate how long it will take to have this ready for the public?  For example, if we said we would like this to be a priority after the Events Media Kit is done, what are your thoughts?  I realize there are other projects and pieces to this too, but just checking.

**Comment by budparr** [comment]
It depends on the schedule. All in all, it shouldn't take more than a day or three to implement. We try to schedule our work in week-long sprints so we like to know what's coming the following week (granted, it doesn't always work that way). If we are pretty sure it's coming down the pike, I can set it all up in advance and we can just make it live when you're ready.

**Comment by peterbooksmith** [comment]
@budparr  - I had a meeting about this with Tim and Dana today.  We definitely want to get this moving starting next Monday, 3/14.  Would it be possible for Tim to speak with you on the phone sometime this week re: the ecommerce pieces?

**Comment by budparr** [comment]
Sure

**Comment by budparr** [comment]
Please do these things:

- [ ] Open a Snipcart account and send me the log in credentials (you can change them later).
- [ ] Open a Stripe account and send me the log in credentials (you can change them later).
- [ ] For each book to be sold, add it to the books content section ( @zchyde knows how to do this) and let me know what the book is. _We'll work out the details of the best way to do this on an ongoing basis_.
- [ ] Specify the price of the book or subscription.
- [ ] Specify the term of the subscription (12 mos? etc.).
- [ ] Specify any shipping or handling charges.
- [ ] Specify how you are delivering the books (pickup, shipping, etc).
- [ ] Specify the copy for the landing page.

**Comment by zchyde** [comment]
Snipcart: 
promotions@brooklinebooksmith.com / PW: store279

Stripe:
promotions@brooklinebooksmith.com / PW: store27902445

**Comment by zchyde** [comment]
Those values were also added to the Booksmith googlc doc password master

**Comment by budparr** [comment]
Thank you. I am going to change the passwords as soon as I log in and send them to you securely. This isn't a secure forum (nor is email really. I'm a stickler for security).

**Comment by zchyde** [comment]
Thats fine, I will make sure the others get them

**Comment by budparr** [comment]
@zchyde can you (or someone) log in to Snipcart and fill in the "profile" information as well as the "billing & payments" information? It's on the bottom right under the account menu.

Thanks!

**Comment by zchyde** [comment]
@peterbooksmith I think this is a job for you, I don't know about billing & payments. I am going to send you the login information in a moment

**Comment by peterbooksmith** [comment]
I am just checking with Tim on these two items.  Need to see if he wants a different email for the Sender email and which credit card he wants for the billing.  Will take care of this ASAP.

**Comment by budparr** [comment]
sounds good. You can always change it later, if need-be.

**Comment by budparr** [comment]
When you all get the copy and banner image, could you post it here? I know some of that is coming from Tim, I just want to keep it all in one place.

**Comment by budparr** [comment]
for posterity
> First book is The Waters of Eternal Youth by Donna Leon (Atlantic Monthly Press, March 2016)

> Price is $26.00 for the book.

> Specify the term of the subscription (12 mos? etc.).
Terms offered will be 6 months (gift); 12 months; or Indefinitely. Members may cancel at any time.

> Specify any shipping or handling charges.
No shipping charges for Pickups. Books being shipped inside MA will be charged tax plus 7.00 for shipping. Books shipped outside of MA will be charged no tax and 7.00 shipping.

**Comment by peterbooksmith** [comment]
OK, I have entered billing/payment info into Snipcart, and the profile is set for now.  We are going to change the sender email.  Will post other info when possible.

**Comment by zchyde** [comment]
Thats fine, I set all that up so no worries.

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;fWZ5MPt0&#x2F;32-febc-ecommerce"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> FEBC Ecommerce</a>

**Comment by budparr** [comment]
Just an update, in case you haven't heard it directly from Tim. He and I spoke yesterday. I've laid the groundwork for the FEBC on the site and have reviewed the specifications for what we're trying to accomplish. I've also reviewed the examples (given above) of others' programs, none of which are executed very well, which we agree on. 

To accomplish any ecommerce there are quite a few pieces to the process for which we rely on vendors for a big chunk. That's from the buy buttons and checkout forms, to collecting addresses, determining if there's tax to be charged, processing credit cards, dealing with refunds, etc. etc. These vendors are critical in handling the complexity of transactions in a way that is simple and fast for your customers.

Most of that work, aside from the code I create on the website, is typically handled by two vendors. One vendor processes the credit cards, which we're pretty well set with Stripe, an industry leader. **The other piece is complicated by the fact that the price of these subscriptions varies from month-to-month.** Many systems aren't equipped to deal with such variability, and we have to strike a balance between our needed flexibility and something that won't confound your customers. 

I'm confident we'll find the right solution and I'm working through a few ideas now and I will keep you up-to-date.

**Comment by peterbooksmith** [comment]
Hi Bud,
  
 Thank you for the update.  I am at home sick today (yesterday too), so I am connected and seeing emails, etc, but not quite as engaged as normal.  If anyone needs anything from me, just let me know.
  
 Best,
 Peter
  
  
  

----------------------------------------

**Comment by budparr** [comment]
Hi everyone,
I believe I have a solution for us. I'm going to work on testing this today and tomorrow, with work on implementation right after. I'll update you once I've done the tests.

hope you're feeling better, @peterbooksmith

**Comment by budparr** [comment]
Updating you all here with the note I just sent to Tim:

> Today's update! My approach has been two-fold here. Finding vendors to do the heavy lifting, which ultimately would be best for your use of time on an ongoing basis, as well as your customers' experience. Unfortunately, not too much luck yet. I have found one vendor with whom I've been in contact with and am exploring them further. I'll update you when I have a higher level of confidence on that. And, working on what it would take to build out a custom solution. I think the latter would be something along the lines of Harvard's solution. On both counts it might not be as good as using a vendor for all of it, but seems viable. With any solution we choose, we'll be in the position of having to charge $0.00 and then the book charge (similar to what Greenlight is doing), would could be confusing for some customers, but I'm guessing that you feel the customers will be motivated enough by the prospect of the first editions to overcome that. The difficulties here stem from the variable pricing of the books, as we discussed, so appreciate your patience while we hone in on the best solution for you.

**Comment by peterbooksmith** [comment]
Hi @budparr  - Zoe told me there are some things you have to change on the SFE page, that she cannot do them yet.  Do you think those could be done tomorrow?  While we don't launch publicly until 5/24, I need to go over all of our material this week with Tim and our other owners, make sure all is well and final and ready.  Thanks.

**Comment by budparr** [comment]
Hi, @peterbooksmith - it's not just adding content, I need to code in the ability to have copy for the books listed there, so it's taking a bit, but should be ready by tomorrow, no problem.

**Comment by peterbooksmith** [comment]
That's great, thanks.

**Comment by peterbooksmith** [comment]
@budparr - is this the most up-to-date verson now:  http://www.brooklinebooksmith.com/sfe/#subscribe

**Comment by budparr** [comment]
Yes, it is.

**Comment by peterbooksmith** [comment]
@budparr - I have some edits for you.  If we are ready for @zchyde to do these, that's great, though she is not here until this afternoon.

1. First section, "What it is" - would you add a sentence before the last one, so after "...your home library."  please add "In ten, twenty, and thirty years you will have a unique history of the changes in the literary climate over time."  (followed by the last sentence "Plus, these titles...."
2. Just underneath the "Other Stuff" in the first section, and above the the blue "Subscribe" I see "The Noise of Time 1 - 1"  That should not be there.
3. Right underneath that blue "Subscribe" please add "Signed" before First Editions Book Club  (we want to consistently say Signed First Editions Book Club everywhere).
4. Further Down, in SFEBC FAQs, under "What is the SFE club?", add the word book to the beginning of the first sentence, "The Signed First Editions Book Club...."
5. Further down, in the section "Can I select which months/titles I want?", please delete the last sentence, "However, members of our 12 month and ongoing plans have limited “opt out” opportunities (see below.)"
6. The very next section, "Can I return or opt out of an SFE selection?" - opt out should be hyphenated (opt-out)
7. in the section "When will I receive my books?", the word "publiser" should be publisher.

Please let me know if you have any questions. - Thanks, Peter

**Comment by budparr** [comment]
Hi @peterbooksmith - I've been out all afternoon. @zchyde have you done these copy changes, or do you need me to?

**Comment by peterbooksmith** [comment]
@budparr  - not to speak for anyone, but Zoe is setting up for and hosting an event right now, so would you be able to take care of these?

**Comment by zchyde** [comment]
thanks for making these changes @budparr, this month is super busy events wise. I think these changes are all done, @peterbooksmith

**Comment by budparr** [comment]
Yes, they are. Not sure if you get notifications on the changes, but they're reflected here in the thread. You'll see something like "budparr added a commit that referenced this issue…"

**Comment by peterbooksmith** [comment]
@budparr  - Happy Monday.  Zoe is in later again today, so would you be able to take care of this?

Near the bottom of the page, under "Can I return or opt-out of an SFE selection?"  In the last sentence, "For people in our delivery plan who have any questions or concerns about returns, please email SFE@brooklinebooksmith.com"   The email address is not showing up as a link.  Even though that appears multiple times nearby, it should prob be consistent, so could you make that occurrence a link as well?

I don't want to jinx anything, but I think that's it and we will be rtg.  Once this page goes live tomorrow, we are going to create a blog post about out and send out an email and social media.  Can you let us know once it is live, or is that something you can schedule?

**Comment by budparr** [comment]
Sounds good - I made the change. I'm going to be making a server change so we can serve the site over HTTPS, but that's not a big deal. And, you need to let me know where you want it in the menu. It can't go in the main list without taking something out. 

And that leads me to the fact that I very much need to hear back from you on "[Consider Menu items Reconfiguration #153](https://github.com/sonnetmedia/brooklinebooksmith.com/issues/153)."

**Comment by peterbooksmith** [comment]
I know, and sorry I have not said anything further about that.  For this thing, for right now, we can just make a blog post about SFE and pin it to the top.  I know that is not really anyone's favorite thing to do, but it is a quick-fix and it will make SFE kind of front and center for a little while.  You ok with that?

Regarding the menu items, I did bring that up with Dana, Lisa, etc, but haven't heard anything from anyone yet, so I will press that issue.  Honestly, I have just wanted to get this SFE launched and out of the way because it has taken up so much time and energy, but you kind of experienced that too.

**Comment by budparr** [comment]
No worries. Yeah, the SFE thing was quite a rabbit hole, wasn't it. I didn't imagine something seemingly so simple, would be so fraught with complexity.

**Comment by peterbooksmith** [comment]
Neither did I.  Lots of very specific pieces to it.  You should have been here for all the discussion over all the various pieces!  If it works they way we hope, it could mean a 150-200 hardcover sales per month, so hopefully worth it all.   After tomorrow I can push more around here to focus on what we want to do with the homepage, menu, etc.

**Comment by peterbooksmith** [comment]
Just checking Bud, is everything all set and are we good to go?  We have emails and social medias scheduled and ready, so I just want to be sure.

**Comment by budparr** [comment]
yep

**Comment by peterbooksmith** [comment]
sweet, thanks

**Comment by peterbooksmith** [comment]
@budparr @zchyde  - now we would like to change some things on the SFE page.  Should be mostly text changes.  We want to replace the top section - from "What it is" to just before the blue "Subscribe" with:  

Announcing a very exciting new program for Booksmith and book lovers:
The Signed First Editions Book Club (SFE)

Why join? Consider this testimonial from one of our patrons and subscribers.

"As someone who often participates in conversations about literature it is very easy to look backward and lose sight of the texts emerging right before me. The Signed First Editions Book Club not only provides a reminder of the present literary players, but also encourages a participation in the production of literature by offering the rare gift of a first edition. With this book club I get to be a community member, a collector, and a consumer of new words that are just being put forth in the world, which is an exceptional privilege."  --Molly B. (SFE Subscriber)

Also, by being an SFE member you are supporting an important part of our bookstore’s mission: connecting writers and readers. Many of the books selected in our SFE program will be signed by authors (both well-known and promising literary debuts) who are visiting our bookstore. The more patrons we have as members gives us strong appeal with the publishers deciding where to send those high profile authors.

What does it cost to join and what do I get?

You (or someone as a gift) will receive one signed, first edition book per month that is a personal recommendation from our fine staff of readers. You may subscribe for 3, 6, 12 months or indefinitely (cancel at any time). You can choose our Delivery Plan (36.00/month) where we ship books directly to you, or you can save on shipping and choose our Pickup Plan (29.00/month) where you collect the books directly from the store. You will receive email notifications when books are ready for pickup, or are being delivered, and about upcoming selections. If you have more questions about the SFE Program, review our Frequently Asked Questions list or email Tim Huggins at sfe@brooklinebooksmith.com.

**Comment by peterbooksmith** [comment]
I am going to forward Tim's email about this to both of you so that you can see what he said.  It includes the above text, with some ideas about formatting, etc.   He includes, " I think the larger FAQ section could be on another page or in smaller font."    My feeling is we don't want to put the FAQ on another page, just leave it as is, but would you let me know what you think about that?  Thank you.

**Comment by budparr** [comment]
I'm all for keeping it (the text) as short as possible, but I think that FAQs are fine below. The most important thing is to have the actual buttons as high up the page as possible.

**Comment by peterbooksmith** [comment]
I think that's what Tim had in mine.  Reduce the text and the top, make it a bit more dynamic word-wise and get  the subscribe buttons higher.

**Comment by peterbooksmith** [comment]
I think that's what Tim had in mind. Reduce the text at the top, make it a bit more dynamic word-wise and get the subscribe buttons higher.

**Comment by budparr** [comment]
Okay. You want me to do the copy? No problem, if so. Just don't want to cross-over @zchyde

**Comment by peterbooksmith** [comment]
Your call @zchyde - if you want to attempt this, fine.  If you already have a lot on your plate right now, that's ok too.

**Comment by peterbooksmith** [comment]
@zchyde - any thoughts on this?  If you can't get to this tomorrow, then @budparr  should take care of it.

**Comment by zchyde** [comment]
HELLO SORRY Im here and I will do this right now

**Comment by zchyde** [comment]
@peterbooksmith as far as I can tell, the above changes have been made? If I missed anything, let me know. I think this looks much better.

**Comment by zchyde** [comment]
Hwe @budparr , I have some updates from Peter that I'm not sure how to do myself - 

1. **If you have more questions about the SFE Program, review our Frequently Asked Questions list or email Tim Huggins at sfe@brooklinebooksmith.com.**   -   In this sentence, Frequently Asked Questions should be a link that moves people down the page and sfe@brooklinebooksmith.com should be a link as well (that's how they were before).
 
2. On our homepage, we had wanted the original SFE Blog post pinned as the top post for "a while". Did anyone say to change that?  If not, I think TIm and the other owners would still want that at the top.

(I had that SFE post "pinned" to the top before but it doesn't appear to be staying, could you take a look at that for me?)

**Comment by budparr** [comment]
Sure thing. I thought we stopped doing the pinned thing? At any rate, I'll make it happen. The first is just a relative link. I'll take care of it and you can look at what I did so so you know for next time. Hope you're doing well!

**Comment by peterbooksmith** [comment]
We did stop with the pinning...except for this thing.  We still want the SFE thing to be featured, at least a while longer.  Thanks for taking care of this.

**Comment by budparr** [comment]
I'm closing this issue. Any new issues related to SFE should have their own issue. The last items there are set.

**Comment by budparr** [comment]
➤ Bud Parr commented:
➤ shuchibooksmith updated an existing comment to:
Since this is a subscription based club, and completely separate from our usual e-commerce operations, I think it's something we could use a third-party system for. Tim, who you briefly met, is going to handle that part internally. Tim is actually still working on a proposal for this, so we can't even move forward until we get official approval. But if you have the names of a few e-commerce partners in mind, he needs this general info

-cost per month for approx. 200 members
-how long you think it'd take you to set us up with this (I imagine not very much time, it'd involve building a page and then us giving you all the information you need for that page, so the time there really depends on us).

I'm happy to get the numbers info for him if you can tell me a few e-commerce partners to look into. 

Thanks!
