### ISSUE TITLE
locate what we're reading posts?

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#221]
I need to edit the posts that are up, but I can't seem to find them?

**Comment by budparr** [comment]
It's called "What Were Reading" at the bottom of the list, below programs. Let me know if you don't see it.
<img width="678" alt="screen shot 2017-05-10 at 4 12 13 pm" src="https://cloud.githubusercontent.com/assets/115347/25919049/75795570-359b-11e7-992f-6834a65cc046.png">

**Comment by shuchibooksmith** [comment]
i see them! but i don't see the cover images linked? how are they appearing on the published post?

**Comment by budparr** [comment]
I'll fix the links. You can edit the books in the books section.

**Comment by shuchibooksmith** [comment]
great, thanks!
