### ISSUE TITLE
Build Tumblr Feed

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#223]
Purpose: To build a page with a feed from BBS's Tumblr account. Use the existing "What We're Reading" menu item.

- [x] Get Tumblr credentials (from @peterbooksmith )
- [x] Get API key
- [x] Build template script (use ICJT as an example)
- [x] Hide away/archive existing "what we're reading" template in case we want to use it later, and disable that collection in config.
- [x] Apply JS template to HTML template
- [x] style posts: keep in mind the various types of posts (images/copy/quotes). They should follow a similar format to what's there, but all the content needs to be on the one page, so perhaps they'll need to be bigger. We'll review when we get there.
- [ ] Show x number of posts on the page. To be determined. With the ephemeral nature of the content, this probably should not be more than a handful.

**Comment by peterbooksmith** [comment]
Just let me know what you need - login info, I assume?

**Comment by budparr** [comment]
Yes. Send it to adamchlan@thenewdynamic.com please. Thanks!

**Comment by peterbooksmith** [comment]
Just sent that email.  When possible, could I can an estimate of how long this will take?  Thanks.

**Comment by AdamChlan** [comment]
@peterbooksmith I have received the login info. My goal is to have something to review tomorrow.

**Comment by AdamChlan** [comment]
Confirming that good progress has been made, but still working on getting a logical first draft of how we will handle the various types of posts in tumbler, and making them show up consistently on the page.

**Comment by peterbooksmith** [comment]
Got it, thanks for the update

**Comment by budparr** [comment]
Thanks for this, @AdamChlan I'll post the link (temporary) here: http://brookline-tumblr.surge.sh/tumblr/
Some comments (which are really in place of a design spec since I didn't know what these would look like until they're up):

- [ ] I think the copy needs to be lighter. Make it the same as body copy elsewhere, I think #333.

- [ ] Images need some padding at the top:
<img width="451" alt="screen shot 2017-06-14 at 7 14 56 am" src="https://user-images.githubusercontent.com/115347/27129718-40c6b3e4-50d1-11e7-881f-b43951dba70c.png">

There's also a quote like that:
<img width="460" alt="screen shot 2017-06-14 at 7 17 47 am" src="https://user-images.githubusercontent.com/115347/27129809-9e8ed0c4-50d1-11e7-9d9a-825d4087539d.png">


- [ ]  The post type (photo, quote, etc.) should be set off, perhaps in gray and a one step smaller.
<img width="193" alt="screen shot 2017-06-14 at 7 15 51 am" src="https://user-images.githubusercontent.com/115347/27129793-87b83688-50d1-11e7-9e55-25f4a0189922.png">

- [ ] Make quotes stand out more by making them serif, slightly larger copy and perhaps some stylish quote marks. I'll send you some CSS for that last bit later, but it entails adding the quote mark with a before/after pseudo class using "content"

**Comment by budparr** [comment]
```
blockquote.quoted p::before {
  content: "“";
  margin-left: -15px;
}
blockquote.quoted p::after{
  content: "”";
  font-size:1.375rem;
}
```
This is just an example, so you can do anything within those pseudo classes, and you may or may not want to use an ascii code for the quote mark. You can use different classes to render them, of course. Hope that's helpful!

**Comment by peterbooksmith** [comment]
Just FYI - going forward, we are going to avoid posting photos to this feed and stick to our own text and links to other articles.  I realize you need to adapt what's already been posted.  Please let me know if there is anything to could be done to make that easier.  We don't need those images to remain there, if that would help.

**Comment by budparr** [comment]
Thanks, Peter. We still need to design for all the post types.

**Comment by peterbooksmith** [comment]
Figured.  Just making sure.  As you see, we hadn't been consistently using tumblr, so it will be easy for us to just focus on certain types of posts now.  That's part of why the idea appealed to us.  Thanks.

**Comment by AdamChlan** [comment]
Hi @peterbooksmith. Here is an updated link to review:

http://brookline-tumblr-7.surge.sh/what-we-are-reading/

Please let me know any feedback or questions you may have.

**Comment by peterbooksmith** [comment]
Thanks @AdamChlan I will share this with a few people here.  Just to ask, is there anything that could be done about hiding the older posts from our feed - the photos from 2016 and earlier?  I know you had to work with our feed as it was, but my concern (and anticipating same reaction from others) is that those posts look quite a bit different from the new direction we want to go with this and aren't necessarily things we would want on here.  I understand if there's nothing to be done about it, just want to ask the question.

**Comment by AdamChlan** [comment]
@peterbooksmith is it the photo post in general that you do not like? Do you anticipate not adding any more posts like that, and if you did, would you not want them to to show up in the feed? I could look to exclude photo posts altogether. We think they add a nice visual aspect to page, but I complete understand the concern about not fitting in to your new direction.

**Comment by peterbooksmith** [comment]
I get what you mean about the visual aspect, but we don't anticipate using this for many photos going forward.  I think our idea with this is to use it mostly to post our own text (like the Bear & the Nightingale staff recommendation) or links to other articles, focusing on book-realted stuff.  Those photos, mostly instagram posts are there from long before this idea an concept that Bud suggested.

Photos like the ones on there are not really what we have seen on our website.  We can use instagram for that.  Not that we might not ever want any images, but I don't think that's what we're going for here.   If excluding the photo posts would be the easiest solution, maybe we'll do that and avoid any new ones.  Let me discuss with folks here and get back to you asap.

**Comment by peterbooksmith** [comment]
@AdamChlan  - if those older posts could be excluded or hidden somehow, that would be preferred.  If you have to just exclude any with photos, so be it.

**Comment by AdamChlan** [comment]
@peterbooksmith  Okay, here is an example that excludes the post type "photo" specifically. Let me know if this is more in line with what you are looking for.

http://brookline-no-photo.surge.sh/what-we-are-reading/

**Comment by peterbooksmith** [comment]
Yes, that's great.  It's just much more what we want to do with this.  Thanks.

**Comment by AdamChlan** [comment]
Okay, let us know if there are any more items you'd like addressed, and if not, we can make plans to get it live.

**Comment by peterbooksmith** [comment]
That looks good to go.  Just to make sure I am on the same page, when it goes live, the tumblr posts will also appear on our homepage (https://www.brooklinebooksmith.com/)  in the blue What We're Reading area on the right-hand side, correct?

**Comment by AdamChlan** [comment]
@peterbooksmith our intention was to not have the Tumblr posts feed into the homepage. Due to the way the different post types show up, some with headlines, some just a large quote, etc, we don't fee like it's going to be the best route. We'd just like to link to it from the menu bar.

The existing What We're Reading info has been stashed away so we can use it if we needed it later.

**Comment by peterbooksmith** [comment]
I see what you mean, but I did think the plan was to have them feed there.  Otherwise, we are going to want to do something with that space on the homepage, because it is static now and we definitely don't want that.  Our first choice would be to figure out how to have these posts feed - but have it look consistent.

What if we made sure we formatted our posts so that they had headlines?  The four with the bold headlines are all ones I posted, so I know it is possible.  Do you think that could work?  

Open to other suggestions, but that could be a much larger discussion.

**Comment by AdamChlan** [comment]
Okay, I will get a working example in place feeding them in.

**Comment by peterbooksmith** [comment]
Thank you!

**Comment by AdamChlan** [comment]
Here is a look at the Tumblr feed on homepage:

http://brookline-tumblr-home.surge.sh/

I set it to show post if they meet the following criteria:
- Must have a title
- Must have an external link

This helps keep the feed looking good, and linking to a relevant place.

**Comment by peterbooksmith** [comment]
I do like it.  I think we can just work with that criteria, and it's something we'll need to play with, but one question.  If we wanted to make a post (like the recommendation for The Bear and the Nightingale) fit this criteria, it seems like we could just include a link to that book on our online store - would that work as an external link?

**Comment by AdamChlan** [comment]
Yes, I believe so. Do you want to run a test so we can be sure?

**Comment by peterbooksmith** [comment]
Sure, I will do another book rec and see

**Comment by peterbooksmith** [comment]
I can just try it each way, but do you know, if I do a "Text" post, and just include the link in there, will that be adequate?  Or do I need to do a "Link" post?

**Comment by AdamChlan** [comment]
I believe it would need to be a link post, but i'd recommend testing both ways.

**Comment by peterbooksmith** [comment]
I just did one of each - the first as Text, the second as Link.  In the link post, I cannot figure out how to make that > after Nevernight go away.  Please feel free to alter as you see fit.  I have to be at on offsite event soon, but I can look at this a bit more later.  Interested to see how each will look.

**Comment by peterbooksmith** [comment]
@AdamChlan I've tried a few different things, and we can work with this.  I wish there was a way that a Text post (like the Bear & the Nightingale rec) could still work to post on the homepage and the What We're Reading Page.  That way, we could just use this for simple staff recommendations and other articles (with outside links).  If that just won't work, I understand.  We can still work with the criteria you've set. 

Are both of these accurate as far as how everything will appear?
http://brookline-tumblr-home.surge.sh/
http://brookline-no-photo.surge.sh/what-we-are-reading/

Before we actually go live, I think I want to get rid of some of the posts so that the formatting is more consistent.

**Comment by AdamChlan** [comment]
@peterbooksmith I made some adjustments to get Text posts on the homepage. Since the only place to read them is on the Tumblr, no need to require them to have an external link (outside of Tumblr). On the What We Are Reading page, I added a excerpt to text posts, because it looked a bit bare with just the title. Let me know if this is more in line with your hopes for the pages.

http://brookline-july-4.surge.sh

and 

http://brookline-july-4.surge.sh/what-we-are-reading

**Comment by peterbooksmith** [comment]
@AdamChlan that's really great.  Definitely what we were thinking.  I did another tumblr post this morning to try something out, but I am going to delete that, along with the last two b/c they weren't really what I wanted, format-wise.  Doing that right now, and then I think we can go live

**Comment by budparr** [comment]
@peterbooksmith This is live.
