### ISSUE TITLE
used book cellar

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#23]
copy for this page to come. 
for now you can use what's currently on the website as a placeholder:
http://www.brooklinebooksmith-shop.com/ubc

note that there will be blog posts on here too. those posts will include "find of the week"
http://www.brooklinebooksmith.com/findarchive.htm (paul selects one each week and puts it in bmail)

and ubc finds, which he currently puts into the newsletter in this format:
![ubcfinds](https://cloud.githubusercontent.com/assets/15218891/10806656/93368698-7dad-11e5-813b-30331433c7d1.png)

we're hoping with the new site he'll instead dedicate one blog post per book instead of all three in one.

**Comment by shuchibooksmith** [comment]
this is part of bmail, and currently has it's own page on the website.
maybe each find could be it's own post on the UBC page?
http://www.brooklinebooksmith.com/findarchive.htm

**Comment by budparr** [comment]
If these are like posts then we can make them that, with a category of "Used Book Cellar" and show them on that page. Kind of like what we're doing with the kidsmith page, but I'll show the entirety of the most recent post on the UBC page.

The idea is that when you have things that have a time factor or periodicity, it's best to  add-to and not replace, hence making them posts. Make sense?

**Comment by shuchibooksmith** [comment]
Yes, I think so! 
I think that's been our idea all along - "find of the week" is a segment in the newsletter. This segment will now become a post on the UBC page. Same with all of the segments on the newsletter, for their respective pages. So I think we're saying the same thing, yeah?

**Comment by budparr** [comment]
So that's why the newsletter will be broken into five pieces. Now I understand.

**Comment by shuchibooksmith** [comment]
Yes! 
the only segment from the newsletter that we won't be transferring over yet is the "remainders" segment. doesn't really fit in anywhere, but maybe we'll find a place for it eventually.
Yay!

**Comment by shuchibooksmith** [comment]
another segment for ubc page is the "used book cellar" segment, which is the photo of three books and the blurbs paul wrote about each book. this will now be it's own post on the ubc page.

**Comment by shuchibooksmith** [comment]
Hi Bud-
Can this information for the UBC be included in a sidebar on the UBC page? Maybe in that gray/gold/whatever color we decide on box?

Buying Hours:
Wednesday through Saturday 10-4
No appointment needed.
No curbside service; all books must be brought inside.
Call ahead if you need special assistance.

Contact Us:
ubc@brooklinebooksmith.com

**Comment by budparr** [comment]
Yes. no problem.

**Comment by shuchibooksmith** [comment]
This will make up the body of the page:

Since 2004, the Used Book Cellar, located in the basement of Brookline Booksmith, has been Boston's best-kept secret. With over 25,000 books in our inventory, you're guaranteed to find something to pique your interest. Whether you're looking for a good mystery to get you through the commute home, a picture book for your family story time, or some hard-hitting cultural analysis, there's always a good reason to stop by!
 
How does it work?
Bring your books to the desk in the Used Book Cellar anytime during our buying hours (Mon-Sat from 10am-4pm) and our experienced buyers will go through them. We'll tally the original price of the books we buy and give you either 15% of that total in cash (check if over $50) or 20% in store credit. You are welcome to browse the stacks while we go through your books.
There is no limit to the number of books you may bring in at one time. Please bear in mind that the only parking available is metered and on-street, and we do not have an elevator or back entrance. We can loan you a hand cart on request. Once your books are in the store our staff can assist with transporting them up and down the stairs. Our buyers will go through any books you bring in, but all unpurchased books must be removed by the owner as we do not accept donations. For your convenience our buying guidelines are included below.
Wondering if we'll buy something specific? Feel free to call during buying hours and speak with a used book buyer or e-mail us at ubc@brooklinebooksmith.com as our stock changes regularly. Can't make it in Mon-Sat between 10 and 4? We buy outside designated hours by appointment only. Please call or email to make an appointment.
 
What are we looking for?:
- Gently used and up-to-date paperback fiction and non-fiction.
- At the buyer's discretion we consider hardcovers in graphic novels, art, cooking (published post-2010) and unique vintage editions (published pre-1980).
 
What don't we take?:
- Donations
- Hardcover editions of books available in paperback (most hardcovers come out in paperback after a year.)
- Textbooks, coursebooks & test prep books (e.g. SAT, AP, TOEFL etc.)
- Travel guides
- Computer/technology guides
- Books with water damage, broken spines, dog-eared pages, highlighting, underlining or handwriting (front page notes/inscriptions are ok)
- Books sold from our $1 racks
- Rare, antiquarian or collectible editions
- Wholesale lots or estates
 
Our buyers reserve the right to pass on any book they deem unusable.
 
Our staff cannot:
- Make house calls
- Leave the store or give curbside assistance
- Issue cash or credit for books left at the store outside buying hours
- Appraise rare, antiquarian or collectible editions.
- Split a payment between cash and credit
- Issue more than one sales slip per customer per day

**Comment by shuchibooksmith** [comment]
here is the banner photo for the UBC 
![Uploading _DSC3353_mini.jpg…]()

**Comment by budparr** [comment]
oops, @shuchibooksmith looks like you need to re-upload this one.

**Comment by shuchibooksmith** [comment]
![_dsc3353_mini](https://cloud.githubusercontent.com/assets/15218891/11383839/f172e04a-92d8-11e5-8f0a-88cf48c63c4e.jpg)

**Comment by shuchibooksmith** [comment]
@budparr from the content on the UBC page, please delete this section, so that the first part just ends with their email address -  
as
our stock changes regularly. Can’t make it in Mon-Sat between 10 and 4? We buy outside designated hours by appointment only. Please call or email to make an appointment.
