### ISSUE TITLE
Design Notes 11-11

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#24]
Hi @shuchibooksmith

Finally, this is quite a reworking, and there's still some stuff to be done, but now ready for a conversation.

**Hero unit (the top of the site)**
First note that every page's image can change at any time (note I didn't find a replacement yet for the holiday image), as well as the typeface and copy. This will give you a lot of flexibility in keeping things fresh, changing for seasons, etc.

So the ones I have in there are to start with. I'll give you some resources and guidelines for creating your own.

**Navigation**
Note that there's room for five items in the navigation (which is a fair amount), plus a more link so that you can add more pages as you like. This will allow you to add, for instance, the Holiday Gift Guide to the menu without entirely displacing anything.

**Events**
I changed the event layouts, but note I still need to add in that extra info piece we talked about earlier.

**New Arrivals**
I added a new arrivals section to the home page. We can discuss what we want there.

Remember, once we have our basic foundation, we can change things around relatively easily. 

http://brookline-151111-1226.surge.sh/

_p.s. note that the search box is there, but I haven't made it work yet_

**Comment by shuchibooksmith** [comment]
Hi @budparr 

This is quite a reworking, you're right! I think this is great, and really close to what we'd like to go live with. We will be changing the photos around, but most importantly, we'd like to get rid of the quotation on the Hero unit on the homepage and on the About Us page ("Dedicated to the fine art of browsing" and “Best of Boston” 7 of the last 9 years (which, our fault, is incorrect)) Would it actually be possible to send a version to me today with those two quotations taken out?

I think the events page looks great! The two tabs with genre and tickets work, and the information is conveyed well. And I like how the events are listed on the homepage. 
- One big note is the color of the info box on the side of the homepage - currently it's this sort of gold color, we were thinking something more grey maybe?

If you're able to remove the quotations, I'd like to show the bosses tomorrow and then hopefully we'll be good to go live with this! I'll have lots more specific information, like text for certain pages, etc. but I think we're pretty close to the basic foundation!

Thank you!!

**Comment by budparr** [comment]
Here ya go. Sorry it took a while I was out at a meeting. 
This version has gray sidebar (I personally think they need to be stronger colors, but fine with whatever you like here, and of course we can change anytime), And, I think the images beg for some copy overlay, but totally up to you there.

http://brookline-151111-1723-light-sidebar.surge.sh/

**Comment by shuchibooksmith** [comment]
oh! before we go live we do have to show it to marshall, the owner. he might have a little bit of feedback here and there, but hopefully not a lot. (dana and peter hardly had anything significant). he has to give us the final okay before we go live. he won't be here until wed 11/18, so we have a little bit of time to get photos, etc, in.

**Comment by budparr** [comment]
Sounds good.
