### ISSUE TITLE
The ABA side

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#25]
So this might seem like a silly question, but I'm wondering what this part of the site will look like -
http://www.brooklinebooksmith-shop.com/.
Will it look the same?

**Comment by budparr** [comment]
No, that site itself will stay the same, but ultimately should be deprecated in favor of the new site.

Just to be clear, replicating an entire e-commerce platform such as the ABA's for the volume of books you sell would take a lot of time and be considerably more costly than I think you want. Having said that, the benefit of paying me on an ongoing basis (even if for just a while) is that there's no pre-defined thing I'm doing for you, I just work for you on your website and anything that's within the context of your website is pretty much open. Once we get the core site up and running it doesn't seem that that ABA site serves much purpose other than allowing people to buy a book online, like http://www.brooklinebooksmith-shop.com/book/9780062041289. Correct? Do you get a lot of sales volume from that site?

At any rate, I have some thoughts on this, which we can discuss, and in fact am eager to explore what we can do here. But I don't want to get ahead of myself and it depends on what you want to accomplish, so maybe you can lay that out for me.

What does the ABA charge for the site? Do they charge you like a flat monthly fee, or do they charge a percent of sales?

**Comment by shuchibooksmith** [comment]
All good things to think about. I actually don't know the answers to a lot of these questions (for the more technical questions, how much we pay them, percentage of sales) so I'll have to ask management for more details. We do get quite a bit of business through the website. We have a person on staff, Russ, who almost exclusively handles processing special orders (that includes those we place in store and school orders). And our ticket sales go through there as well. The ABA is quite aware of the fact that the larger bookselling community dislikes their e-commerce site (it's been written up in the trade publications) so hopefully they're moving toward changing that. But you're correct, the purpose of the ABA site is that it allows people to purchase a book online. One of the goals of the redesign, at least in the owner's eyes, is that our new website will drive customers to purchase more books through us online. So however we can seamlessly do that from our site to ABA is an ultimate goal...

**Comment by shuchibooksmith** [comment]
The IndieCommerce fee we pay to the ABA is $175/month. We aren't in any set contract with them, so there's no particular end date.
And after speaking with them, it seems that our online says are actually only a tiny portion of our overall sales. I can get you exact numbers if you'd like.

**Comment by budparr** [comment]
Hey @shuchibooksmith I deleted your post because it had potentially sensitive data in it. Github is essentially public, not that anyone would find it at all, but best not to put sensitive stuff here. 

At any rate, that's interesting. Would be great if they published an API - that would be the modern thing to do!

**Comment by shuchibooksmith** [comment]
I did not realize that!! EEk. I'll be more careful. Thank you!

**Comment by shuchibooksmith** [comment]
I had to look up what API means. I get it now. :+1:

**Comment by budparr** [comment]
Should have told you before. It's kind of the open source ethos to be public and transparent, but that of course has limits. Don't worry too much about it though, just price or log in type stuff.

**Comment by shuchibooksmith** [comment]
I think this is what you mean by API but I thought I'd check - is there a way to add a shopping cart feature that customers can use while they're browsing, and then when they actually want to pay they THEN get sent to the ABA site/linked up to their shopping cart?

**Comment by budparr** [comment]
Hi @shuchibooksmith I've been out at meetings and then family stuff all day. I'll answer this thoroughly for you on Monday.

**Comment by budparr** [comment]
Yes, I agree. I'm still trying to figure out how "close" we can get to the aba data without using the site.

**Comment by shuchibooksmith** [comment]
okay great, thanks!

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;l0jEoSan&#x2F;8-how-to-deal-with-the-old-aba-site"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> How to deal with the old, ABA site?</a>
