### ISSUE TITLE
About Us page

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#27]
Here is the basic text for the "About Us" page-
Brookline Booksmith, located just outside of Boston in Coolidge Corner, originally opened in 1961 as Paperback Booksmith with the slogan “Dedicated to the fine art of browsing.” The store was one of the first bookstores on the East Coast to recognize that “serious” paperback books—a publishing phenomenon of the late 1950s—opened up the world of great literature to a mass audience. Prior to that, paperbacks mostly featured westerns and nurse stories and “serious” literature was only available in hardcover. Paperback Booksmith sold a diverse range of books—from great literature to naughty books, from books by and about the radical left to books by and about the radical right. The Booksmith was one of the first stores to display the books by category, rather than by publisher, and to organize its books alphabetically by author, encouraging customers to enjoy browsing on their own and at their leisure. Since its beginnings as Paperback Booksmith, Brookline Booksmith has continued to evolve, serving the people of Brookline and Boston. – As told by Marshall J. Smith, founder of Paperback Booksmith in 1961.

**Comment by shuchibooksmith** [comment]
also we'd like to eliminate that long list of emails. please just keep 
general email
thestore@brooklinebooksmith.com
store manager, booksmith co-owner, Dana Brigham
dana@brooklinebooksmith.com

**Comment by budparr** [comment]
got it

**Comment by shuchibooksmith** [comment]
banner for about us page 
![Uploading _DSC3344_mini.jpg…]()

**Comment by shuchibooksmith** [comment]
![_dsc3344_mini](https://cloud.githubusercontent.com/assets/15218891/11381843/735c2916-92cc-11e5-94a3-5d7ef6ebec71.jpg)
