### ISSUE TITLE
Kidsmith

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#29]
content for this page -
Alex's blog posts
Amy's blog posts (stick figure Amy)
Paul's "New Books for Kids" segment from the newsletter as a blog post

**Comment by shuchibooksmith** [comment]
add kidsmith twitter feed https://twitter.com/kidsmithbooks

**Comment by budparr** [comment]
@shuchibooksmith  - can you tell me more about "stick figure Amy" - I noticed that there are a couple of those in my initial sample of posts. So they're an ongoing thing? And, can the images be bigger. Thinking I need to make a special layout for them.

**Comment by shuchibooksmith** [comment]
Yes! Amy is one of our kids booksellers and the backlist buyer for the kids section. She hasn't done stick figure Amy in a while because of time constraints, but she is hoping to start it up again. She usually scans the sketches and then shrinks the image for blogger. She can send you the scans if that would help?
