### ISSUE TITLE
Editing Content

### ISSUE THREAD

**Issue by budparr** [sonnetmedia/brooklinebooksmith.com#31]
Just starting a conversation on editing here. 

@zchyde do you write the HTML for the extra images on kids books?

cc/ @shuchibooksmith

**Comment by zchyde** [comment]
Yes, I do. I mean its an amalgamation of stuff that the person who was in my job before me wrote / solutions I've searched for on the internet / beginner code writer stuff.

**Comment by zchyde** [comment]
BUT yes I write it

**Comment by budparr** [comment]
Okay. I figured as much. Just trying to figure out the best way to go about it. No real way of accomplishing the fancy stuff in a WYSIWYG editor, but it's a good (actually, great) thing that you're comfortable with it. More later…

**Comment by zchyde** [comment]
Oh ok I see, yeah I'm pretty comfortable with it an desperate to learn, so anything you want to show me I'm more than interested in!

**Comment by budparr** [comment]
Well, I think you'll find this interesting. We have a typical WYSIWYG editor for you to use, but it's helpful to understand what's behind it. Your content is all written in very simple text files. To add formatting, we use something called "Markdown" (see my blog post on how to use it: ["The Basics of Markdown"](http://www.sonnetmedia.net/articles/the-basics-of-markdown-tutorial/)). In fact, you can use Markdown in these comments here on Github. 

Markdown, as you'll see in the post, is just a simple way of writing plain text so that it will be formatted on the web. So putting a couple of asterisks (**) around a word or line makes it bold, etc.

So, here's the Holiday Gift Guide:
https://raw.githubusercontent.com/sonnetmedia/brooklinebooksmith.com/gh-pages/_posts/2015-11-20-holiday-gift-guide-kids.md 

Again, you'll have a nice WYSIWYG editor for day-to-day use, so don't think that you'll be stuck having to edit files like these ( I actually prefer just writing in the text rather than using the editor). But, particularly as we add in some of the fancy stuff, it'll be helpful for you to understand that behind-the-scenes stuff.

**Comment by zchyde** [comment]
Oh weird...and cool...this looks a little like javascript to me but I guess its just that there's no brackets

**Comment by zchyde** [comment]
I mean the difference being this I can grasp and Javascript..... .. ..  .. . . ... . ..well I'm working on it

**Comment by budparr** [comment]
Funny, well it's just simple text. I take the concepts of simplicity and minimalism extremely seriously.

I hearya on the javascript - it can be a challenge.

**Comment by budparr** [comment]
So, this is cool. If you can grok this stuff, the rest is easy. 

One of the great things about having your content in these simple text files is that you could edit right here in Github. 

Not only that, you can see every single change you've ever made (and who made it) to a piece of content, forever, so there's no mistake that can't be corrected, etc.

So here's that page on Github:
https://github.com/sonnetmedia/brooklinebooksmith.com/blob/gh-pages/_posts/2015-11-20-holiday-gift-guide-kids.md

If you click on the "Raw" button toward the top you'll get the version I showed you earlier.

If you click on the "history" button toward the top, you'll see the edits I've made to the file. If you click on the bunch of numbers to the right of each change, you'll even see precisely what each change was. Editors tend to love this.

**Comment by budparr** [comment]
I should add, of course, in case you hadn't seen it, that formatted, that page looks like: http://brookline-151123-11052.surge.sh/holiday-gift-guide/2015/11/20/holiday-gift-guide-kids/

note that I haven't added your extras in there yet.

**Comment by zchyde** [comment]
This is what Git *is*, right? I did a Git tutorial the other day but it was only semi helpful to me.

**Comment by zchyde** [comment]
Oh man I just did it to italicize is
I am a true genius

**Comment by budparr** [comment]
You are indeed awesome! Not a bad idea to do the tutorial, but it's only
important to know that it's there. Git is just a way to keep versions of
things; Github is the service we're using to make it easy to use.
