### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#32]
New releases-
Can the new releases listed on the bottom be the new releases from Paul's last bmail?
http://www.brooklinebooksmith.com/thisweek/111815.jpg

**Comment by budparr** [comment]
Sure, just send along the ISBNs

**Comment by shuchibooksmith** [comment]
438 days - 9781501116292
About Women - 9780385539869
The Only Street In Pairs - 9780393242379
Hell & Back - 9780670024582
Sleep of the Righteous - 9781931883474
Beatlebone - 9780385540292
This Old Man - 9780385541138
First Bite - 9780465064984

**Comment by shuchibooksmith** [comment]
did you decide to forgo the covers for the events books on the homepage?

**Comment by budparr** [comment]
yeah, for brevity and because of all the other images. You want them there?

**Comment by shuchibooksmith** [comment]
i think so, yes? at the very least they should be on the events page with each listing, but i think on the homepage too.

**Comment by budparr** [comment]
@shuchibooksmith I put the covers back on the home page events. It was actually a coding error, not a deliberate decision - not sure what I was thinking when I said otherwise, but yesterday was a busy, fragmented day, so I'll chalk it up to Monday lunacy.

**Comment by shuchibooksmith** [comment]
@budparr okay great! and now i have banner images for you. compressing and sending now...

**Comment by shuchibooksmith** [comment]
![_dsc2908_mini](https://cloud.githubusercontent.com/assets/15218891/11380932/16453f92-92c7-11e5-8045-e768ae224967.jpg)

**Comment by budparr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;pd7idfG9&#x2F;14-add-new-books-to-home-page-coming-soon"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add new books to home page coming soon</a>

**Comment by shuchibooksmith** [comment]
@budparr on second thought, instead of adding the new releases to the bottom of the page, how about we instead add our weekly bestsellerS? we have a bestsellers case in the store and the top row is our six hardcover bestsellers and the second row is our seven paperback bestsellers. every monday i change it out with the previous week's bestsellers. that's 13 books though. what do you think?

**Comment by budparr** [comment]
@shuchibooksmith send me the ISBNs and I'll make it work.

**Comment by shuchibooksmith** [comment]
hardcovers-
1) Unstoppable - 9781250007148
2) My Life on the Road - 9780679456209
3) Between the World and Me - 9780812993547
4) Unfaithful Music & Disappearing Ink - 9780399167256
5) Bassoon King - 9780525954538
6) Modern Romance - 9781594206276

paperbacks-
1) Mindfulness Coloring Book - 9781615192823
2) Martian - 9780553418026
3) Opposite of Loneliness - 9781476753911
4) Everything I Never Told You - 9780143127550
5) Betrayal - 9780316271530
6) Boston Girl - 9781439199367
7) Occupation Trilogy - 9781632863720

**Comment by shuchibooksmith** [comment]
Here are the new weekly bestsellers
hardcovers-
1) Thing Explainer -  9780544668256
2) Between the World and Me - 9780812993547
3) Unfaithful Music & Disappearing Ink - 9780399167256
4) M Train -  9781101875100
5) Unstoppable- 9781250007148
6) Boys in the Trees - 9781250095893

paperbacks - 
1) Mindfulness Coloring Book - 9781615192823
2) I Am Malala - 9780316322423
3) Boston Girl - 9781439199367
4) HT Relax - 9781941529089
5) Opposite of Loneliness - 9781476753911
6) Occupation Trilogy - 9781632863720
7) Station 11 - 9780804172448

**Comment by shuchibooksmith** [comment]
Can you change these two carousels to Weekly Bestsellers - Hardcovers, and Weekly Bestsellers - Paperbacks

**Comment by budparr** [comment]
Sure.
