### ISSUE TITLE
Image uploads

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#37]
So our experiment today with launching has made me realize something, when I make these gift guides I upload the images to our domain through FTP. When Richard initiated whatever change he made today, all the image links were broken. I imagine that that's going to happen when we go live on monday? How do I host these pictures so that they still work when we make the switch?

**Comment by budparr** [comment]
Right now you have your FTP set up as an alias of (points to with what's called a CNAME record) the www.brooklinebooksmith.com domain, which is what is used for websites. You can point it anywhere. However, you'll be uploading images to the new site, not the old, so I doubt you'll need it.

**Comment by zchyde** [comment]
Right but, for example, this email blast for cooking needs to go out on Monday - so I will need to change the addresses in these image links so that they point to the images on the new site, correct? Because right now, as soon as the switch happens, all the image links on the email versions of these blasts will be broken as they are now.

**Comment by budparr** [comment]
can you send me an example link?

**Comment by zchyde** [comment]
So today, when we started switching over, this link and all links like it were dead: 

http://www.brooklinebooksmith.com/GG2015/COOKING/nomad_cover.jpg

that's a link to an image in my Cooking Gift Guide email blast.

**Comment by budparr** [comment]
Hmmm. Interesting. I would have thought you'd have those at constant contact. I have those images on the new site, but they, naturally, have a different url and they're named with ISBN numbers, so that image is here: http://brooklinebooksmith.netlify.com/uploads/9781607748229.jpg (and the netlify part won't be the final url when we change).

Let me think some more about the best way to handle it.

**Comment by budparr** [comment]
I think the best thing for you to do is to link to the new images. They all follow the same pattern:
http://brooklinebooksmith.netlify.com/uploads/ISBN.jpg
where ISBN is the ISBN of the book.

You can see them all here:
https://github.com/sonnetmedia/brooklinebooksmith.com/tree/site/uploads

**Comment by zchyde** [comment]
ok. In my blasts I also have additional extras, inserts from the book and stuff. Where should we host those? Sorry, I didn't make the connection that shutting down our website proper would make all these images unavailable.

**Comment by zchyde** [comment]
![screenshot 2015-11-30 09 24 01](https://cloud.githubusercontent.com/assets/15219441/11474176/6e76751a-9744-11e5-87e6-215ae6aa5478.png)

like this

**Comment by budparr** [comment]
No worries. Let's make sure we get all this straight before doing anything on the site itself. 

I've set up Google Cloud Storage for you and I'll give you a place to upload images. You need to have a google email address; something tied to brooklinebooksmith. Can you set one up, if you don't have one, and then I'll give you access and instructions. That will give you an easy place to throw up images for any use that's not explicitly tied to the websites.

**Comment by zchyde** [comment]
totally, one second

**Comment by zchyde** [comment]
is promobrooklinebooksmith@gmail.com ok?

**Comment by zchyde** [comment]
or promobooksmith is shorter

**Comment by budparr** [comment]
Yep

**Comment by zchyde** [comment]
promobooksmith@gmail.com is made

**Comment by budparr** [comment]
I'm just now headed to the office, so I'll take care of this in about 40 min

**Comment by budparr** [comment]
@zchyde - I just sent you an invite to Google Cloud Storage. The images are set, and I put a bunch of the 978... images that I've been using in there. 


It is really best practices to serve images from a separate domain (in this case, images.brooklinebooksmith.com) so this is a good thing to do, though normally I wouldn't have introduced the idea so early into the game.

I doubt you'll find the control panel intimidating, but there's a lot there. The ONLY thing you will need is what's called "Google Cloud Storage" - If you click on the hamburger icon on the upper left-hand side, you'll see a list of a bunch of things, you'll see **Storage.** (and you can actually click on the pin icon and it will save a link to it up-top for easy access later).

When you get to Storage, you'll see "**Buckets** and within buckets you'll see **images.brooklinebooksmith.com** and if you click on that name, you'll see a bunch of images. 

You can just drag and drop images into that "bucket" and they'll be available at "images.brooklinebooksmith.com/image-name.jpg"

Let me know how it goes. I think you can access this from the cyberduck ftp manager, but I've found that once you bookmark the link to that page, it's easier to do it directly from there.

**Comment by zchyde** [comment]
INTERESTING ok, I will check that out now. Why is this best practices? To cut down on situations like this?

**Comment by zchyde** [comment]
Is google storage a thing we are paying for? Do I have to sign up for the free trial?

**Comment by budparr** [comment]
It's best practices for technical (and somewhat arcane) reasons that have to do with performance.

As long as you're working with me, I pay for it. However, even if you were paying for it, it amounts to a few dollars per month at most.

**Comment by zchyde** [comment]
ok cool, I'm just curious.

**Comment by zchyde** [comment]
Images are all set, folks @shuchibooksmith. All cooking images have been changed and are good to go.

**Comment by budparr** [comment]
By the way. I've been using images right from booksense (e.g. http://images.booksense.com/images/256/668/9780544668256.jpg). It seems to work just fine. Any reason you know why we shouldn't do that when we can?
