### ISSUE TITLE
update kids weekly bestsellers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#39]
similar to weekly bestsellers on the homepage, we'd like to do a bestsellers "carousel" or list on the kidsmith homepage.

**Comment by budparr** [comment]
Okay, send me the list.

**Comment by shuchibooksmith** [comment]
oh, we haven't run it yet, this is something to look at once the website is live. i added enhancement, is that the right label?

**Comment by budparr** [comment]
Perfect. Note that I'm going to change the title to be more action oriented, like a todo item.

**Comment by shuchibooksmith** [comment]
1. Book With No Pictures  -9780803741713
2. Make Way For Ducklings -9780670451494
3. Diary of a Wimpy Kid: Old School -9781419717017
4. The Year We Fell Apart -9781481438414
5. Firsts -9781250075963
6. The Snowy Day -9780140501827
7. Wings of Fire: Escaping Peril -9780545685443
8. This Is Where It Ends -9781492622468
9. Star Wars The Force Awakens Visual Dictionary -9781465438164
10. Waiting is Not Easy -9781423199571
