### ISSUE TITLE
Make sure we can still access staff schedule

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#40]
another thing that i notice get lost in the transition...

http://www.brooklinebooksmith.com/schedules/brooklineschedule.htm

im not sure how this actually gets uploaded, i can ask peter and get back to you...

**Comment by budparr** [comment]
@shuchibooksmith oy. It looks like that page just has links to other pages?

**Comment by shuchibooksmith** [comment]
yeah so i guess its really the two other pages that we need access to - this week's schedule and next week.

**Comment by budparr** [comment]
okay. I added the page. The only difference is that the end of the url has to be .html, not .htm
like this:
/schedules/brooklineschedule.html
not (as it is now):
/schedules/brooklineschedule.htm

**Comment by shuchibooksmith** [comment]
@budparr oh great okay, thanks!

**Comment by budparr** [comment]
Actually, I got it to work with the htm extension.
