### ISSUE TITLE
Figure out a favicon 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#44]

**Comment by budparr** [comment]
you mean favicon? I have one on there (may take a bit to show up), but we can come up with something that's specific to bb.

**Comment by shuchibooksmith** [comment]
@budparr ah, that's what it's called! okay. i'll wait for the one you created to show up and we can continue discussion from there!

**Comment by shuchibooksmith** [comment]
for now can we just use a lowercase b for the favicon? maybe in a shade of blue? thoughts?

**Comment by budparr** [comment]
So I put something up. A "b."

**Comment by shuchibooksmith** [comment]
i think this is okay for now! we'll probably refine once i get feedback, but it's closer to some sort of branding in the meantime...

**Comment by budparr** [comment]
Yeah, I just threw this together to replace my placeholder. It does work in a vague sort of way, but can certainly be refined.

**Comment by shuchibooksmith** [comment]
revisiting this @budparr - we were thinking something a little more refined, something that resembles their favicon: http://www.remodelista.com/?

**Comment by budparr** [comment]
you mean a smaller b?

**Comment by peterbooksmith** [comment]
What if it was just the blue "b" without the lighter shading or shadow behind it?  Might stand out a little more?

**Comment by budparr** [comment]
No problem. I'm in the thick of reimagining the nav, but as soon as I finish I'll whip a new favicon.

**Comment by budparr** [comment]
I've updated the favicon to be a bit cleaner.

**Comment by shuchibooksmith** [comment]
not sure that this stands out enough - thoughts on making it stand out more? maybe a different font? maybe we defer to your creative instincts here? :)

**Comment by budparr** [comment]
The font is close to brand font, so I wouldn't change that.  The first iteration had a background, this one does not, so I think the only thing left is to change the color of the font itself. I suppose it doesn't have to be brand color. Not too much to do with a "b" in 16x16 pixels.

**Comment by shuchibooksmith** [comment]
what do you think of a white on a blue background?

**Comment by shuchibooksmith** [comment]
i'm not sure if that's right either, just tossing out an idea

**Comment by budparr** [comment]
that's what I was thinking too.

**Comment by shuchibooksmith** [comment]
okay! is it possible for us to look at a sample before we have you officially change it?

**Comment by budparr** [comment]
sure

**Comment by shuchibooksmith** [comment]
Hi @budparr! Just checking on this one too, thanks!

**Comment by budparr** [comment]
Just working down the list, trying to catch up

**Comment by shuchibooksmith** [comment]
sounds good, thanks!

**Comment by budparr** [comment]
I'm afraid you really won't get a sense of this without it being on the site, but here's the preview of a new version you wanted.
![256](https://cloud.githubusercontent.com/assets/115347/13647958/70f793aa-e604-11e5-84dd-ea5e6144c44a.png)

**Comment by shuchibooksmith** [comment]
sorry i never responded to this! let's go for it. thanks!

**Comment by budparr** [comment]
Great. I'll take care of it first of the week. Leaving this issue open until I get it complete. Have a great weekend!
