### ISSUE TITLE
Remove gift guide posts from blog page 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#45]

**Comment by budparr** [comment]
what's your thinking on this? Not everyone's going to click through to the gift-guide page, so the exposure of having them on the home page is good, in my view.

**Comment by shuchibooksmith** [comment]
Hm. I think it's that it's on the homepage, and has its own page, and then on the blog too, it might just be too much? I guess getting the other blog posts on there are preferable. But open to leaving it too...

**Comment by budparr** [comment]
Well it's my opinion that the more places it shows up the better. It's assuming a lot to think everyone's going to see the gift-guide page.

**Comment by shuchibooksmith** [comment]
Ok! Let's leave it for now, if there are any strong objections internally we'll revisit.
