### ISSUE TITLE
NEED TO RESOLVE ASAP- the search window/link to ABA needs to be accessible on homepage 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#47]

**Comment by budparr** [comment]
Can you let me know what you mean, exactly?

**Comment by shuchibooksmith** [comment]
Yes! Right now the only way to search for books or get to the shopping cart is clicking on "buy now" from one of the books on the gift guide. People need a way to access the ABA site to search for books much more easily, And on the homepage.

**Comment by budparr** [comment]
Okay, how about a button above the events on the home page that says "Search and Shop the Bookshop"?

**Comment by shuchibooksmith** [comment]
Yes, just switch out Booksmith for bookshop

**Comment by budparr** [comment]
Well I said bookshop to differentiate the two, bookshop being the ABA site. But I'm fine either way.

**Comment by shuchibooksmith** [comment]
How about just 'Search and Shop' ?

**Comment by budparr** [comment]
sure.

**Comment by budparr** [comment]
what page do you want it to go to, exactly?

**Comment by shuchibooksmith** [comment]
http://www.brooklinebooksmith-shop.com/

**Comment by shuchibooksmith** [comment]
it's a little harder to put a search window on the homepage, i assume?

**Comment by budparr** [comment]
Yes. How about a link to this page? http://www.brooklinebooksmith-shop.com/search/advanced_search

**Comment by shuchibooksmith** [comment]
yes, that works! thanks!

**Comment by shuchibooksmith** [comment]
wait @budparr on second thought, can it go here: http://www.brooklinebooksmith-shop.com/search/site

**Comment by shuchibooksmith** [comment]
our customers might get confused with all of those fields

**Comment by budparr** [comment]
I agree! But I don't think I can make a search field from one site to another, and not terribly sure it's a good idea, so it would need to be to something.

there's this: http://www.brooklinebooksmith-shop.com/search/site

**Comment by shuchibooksmith** [comment]
ha yes i linked to that in the message before, i should have combined them into one message - yes link to that one, it's a lot easier!! thanks!!

**Comment by budparr** [comment]
I've added a search page and a link to it from the main nav. That way people won't be abruptly carried away to a different site. Feel free to re-open the issue if that's not satisfactory.
