### ISSUE TITLE
Brighten banner images

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#49]
A number of people find the cast on banner images too dark. Possible to brighten them a bit?

**Comment by budparr** [comment]
It is, but the text won't show up as well.

**Comment by budparr** [comment]
I gave it a nudge. Let me know if that works for you. (note you may have to load the page a couple of times to clear the cache).

**Comment by shuchibooksmith** [comment]
i think that this works now, many thanks!
