### ISSUE TITLE
Another high priority - Broken images in gift guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#50]
Just got a note from coworker, the images aren't available on the email gift guides.

**Comment by budparr** [comment]
can you forward me one, please?

**Comment by shuchibooksmith** [comment]
Sure sending to your email

**Comment by budparr** [comment]
got it. This looks like it was an old email because @zchyde  had changed it, as far as I understand, to reflect where the images are now. Is that not correct?

**Comment by shuchibooksmith** [comment]
Ah ok! Zoë is in tomorrow before me, @zchyde can you let us know about the images once you're in?
