### ISSUE TITLE
Giftcard Button

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#54]
Don't mean to overload you but when it rains, it pours. Apparently we are in our peak season for gift cards, and we're wondering if we can get a link on the homepage that leads directly to 

http://www.brooklinebooksmith-shop.com/gift-card

possibly a link right below the search field? "Purchase a Gift Card"?

**Comment by budparr** [comment]
You guys are full of surprises! No more room in the banner. We could put a button above the events in the home page.

**Comment by zchyde** [comment]
Ok, works for me

**Comment by zchyde** [comment]
I know ,we are very needy today

**Comment by budparr** [comment]
And why not send them directly to this page? http://www.brooklinebooksmith-shop.com/gift-card-booksmith

**Comment by zchyde** [comment]
Yes yeah, thats even better

**Comment by budparr** [comment]
Add giftcard to the main menu. I'm going to close this for now, but feel free to re-open if that's not satisfactory.
