### ISSUE TITLE
Add January Events to Events Page

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#57]
formatting guidelines-
-titles in the blurbs should be italicized
-author names bolded in blurbs when it's a multiple author event

Monday, January 4th at 7:30pm
Book Club

The Brookline Booksmith Book Club meets at 7:30pm downstairs in our Writers and Readers Room. No need to sign up, just show up. To contact our moderator, email bookclub@brooklinebooksmith.com 

Friday, January 8th at 7:00pm
YOUNG ADULT
Real Teen Lives Young Adult Panel 
featuring Marieke Nijkamp, Laurie Elizabeth Flynn, Annie Cardi, Emily Martin and Jen Malone

Join us as our panel of authors discuss “Real Teen Lives” in Young Adult literature. Moderator Jen Malone (Wanderlost) will be joined by authors Marieke Nijkamp (This is Where It Ends), Laurie Elizabeth Flynn (Firsts), Annie Cardi (The Chance You Won’t Return), and Emily Martin (The Year We Fell Apart).

Monday, January 11th at 7:00pm
MYSTERY
Val McDermid
Splinter the Silence

Widely recognized as one of our finest crime writers, with numerous accolades and legions of devoted readers worldwide, bestselling author Val McDermid is back with the latest installment in her much-beloved series featuring psychologist Tony Hill and former police detective Carol Jordan. A masterful novel centered on the mysterious deaths of women who were the victims of vicious cyberbullying, Splinter the Silence is an adrenaline-fueled rollercoaster guaranteed to keep you on the edge of your seat.

Tuesday, January 12th at 7:00pm
FICTION
Janice Y. K. Lee
The Expatriates

Janice Y. K. Lee’s blockbuster hit debut The Piano Teacher was called “immensely satisfying” by People; “intensely readable” by O, The Oprah Magazine; and “a rare and exquisite story” by Elizabeth Gilbert. Now, in her long-awaited new novel, Lee explores with devastating poignancy the emotions, identities, and relationships of three very different American women living in the same small expat community in Hong Kong.

Wednesday, January 13th at 7:00pm
MEMOIR/MUSIC
Lindsey Stirling
The Only Pirate at the Party

A classically trained musician gone rogue, Lindsey Stirling is the epitome of independent, success: after being voted off the set of America’s Got Talent, she went on to record two full-length albums, release multiple hits with billions of YouTube views, and tour sold-out venues across the world. Lindsey’s magnetizing story testifies that there is no single recipe for success, and despite what people may say, sometimes it’s okay to be The Only Pirate at the Party. This is a signing-only event. Purchase of The Only Pirate at the Party from Brookline Booksmith is required to attend.

Thursday, January 14th at 7:00pm
SCIENCE/PSYCHOLOGY
Eliezer J. Sternberg
NeuroLogic: The Brain’s Hidden Rationale Behind Our Irrational Behavior

NeuroLogic explores the brain’s internal system of reasoning and illuminates our most outlandish as well as our most stereotyped behaviors. From sleepwalking murderers, contagious yawning, and the brains of sports fans, to false memories, subliminal messages, and the secret of ticklishness, Dr. Eliezer Sternberg shows that there are patterns to the way we interpret the world—–patterns that fit the brain’s unique logic. 

Friday, January 15th at 7:00pm
Breakwater

Join us for a night of new stories, essays, and poems by MFA candidates from Emerson, BU, and UMass Boston. Fore more information, please visit breakwaterreadingseries.wordpress.com

Saturday, January 16th at 10:30am
KIDS
Storytime

Do you love picture books? Join us in our children’s section as our fine children’s team reads stories aloud every third Saturday and last Sunday of the month.

Tuesday, January 19th at 7:00pm
HEALTH/DIET
David Ludwig
Always Hungry?: Conquer Cravings, Retrain Your Fat Cells, and Lose Weight Permanently

Forget everything you've been taught about dieting. In Always Hungry?, renowned endocrinologist and leading Harvard Medical School expert Dr. David Ludwig explains why traditional diets don't work, and presents a radical new plan to help you lose weight without hunger, improve your health, and feel great. Low-fat diets work against you by triggering fat cells to hoard more calories for themselves, leaving too few for the rest of the body. Always Hungry? turns dieting on its head with a program that ignores calories and targets fat cells directly. This is dieting without deprivation.

Wednesday, January 20th at 6:00pm at the Coolidge Corner Theatre
HUMOR/MEMOIR
Michael Ian Black
Navel Gazing: True Tales of Bodies, Mostly Mine (but also my mom’s, which I know sounds weird) 

In Navel Gazing, New York Times bestselling author and stand-up comedian Michael Ian Black delivers a frank and funny memoir about confronting his genetic legacy as he hits his forties. Whether it’s family history, religion, aging, or his parents, Michael Ian Black always has something to say in the dry, irreverent voice that has captured a fanbase of millions. This event requires tickets which are $5.00 each or free with the purchase of Navel Gazing from Brookline Booksmith.

Thursday, January 21st at 7:00pm
Small Press Book Club

Our newest book club selects readings from independent presses. Join us to discuss the novel Rails Under My Back by Jeffery Renard Allen and poetry collection Bastards of the Reagan Era by Reginald Dwayne Betts. Free and open to the public, meeting the third Thursday of every month at 7:00pm. To contact our moderator, email smallpress@brooklinebooksmith.com 

Sunday, January 31st at 10:30am
KIDS
Storytime

Do you love picture books? Join us in our children’s section as our fine children’s team reads stories aloud every third Saturday and last Sunday of the month.

**Comment by shuchibooksmith** [comment]
@budparr Michael Ian Black will be a ticketed event. Tickets will go on sale on Friday so please add, in bold-

Tickets on sale Friday! 

Once Zoe creates the link to purchase tickets I'll send that to you.
We'll also have to add the "Ticketed" tab for this one.

**Comment by budparr** [comment]
noted. I'm working on changing the kids gift guide first though, just so you know. I assume that's your priority, but let me know if otherwise.

**Comment by shuchibooksmith** [comment]
it is the priority! january events should go up by friday at the latest.

**Comment by shuchibooksmith** [comment]
Not to heap more on to the plate! But the Michael Ian Black tickets will go on sale tomorrow at 12 and want the website to reflect that. @zchyde can you give bud the purchase ticket link when you have it?

**Comment by budparr** [comment]
No problem, I took Friday as Friday, but happy to knock it out today.
