### ISSUE TITLE
Search Field Design Enhancement Suggestions

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#58]
Some feedback from our online orders guy, who is keeping the elderly (the customers he frequently deals with) in mind -
1) can we highlight the white search box to make it more prominent and noticeable?
2) underneath the white search box can you add "Shop Online" which links to the aba homepage (so, similar to what you had created in the menu previously, but instead of shopping being in the main menu it will now be an option under the search field)

**Comment by zchyde** [comment]
I think we should add "Shop Online" to the main menu? Is there any way we could move the Gift Guide, since the link is only temporary, to the "more" drop down menu and replace it with "shop online"?

**Comment by shuchibooksmith** [comment]
hi @budparr, chiming in here. i know we wanted to wait for the dust to settle before enhancing the search fields but we're getting a number of customers calling us and complaining that they can't figure out how to shop our store, and they don't know how to find gift cards. can we boost this to higher priority?

**Comment by budparr** [comment]
Sure thing. What were these people doing before we launched the new site, which didn't have those things (at least noticeably)?

**Comment by shuchibooksmith** [comment]
So I think the two things that were more noticeable with the old one (but i'm working off of memory here) was that Shop Online was in the main menu, in addition to the search window. Is that right? So I'm guessing people are assuming the search bar is to search the entire website, and not for shopping? So we might have to do things -

1) call attention to the search bar more - include shop online underneath it and a search "button" next to it that they can click on after they type what they're looking for in the field
AND
2) shop online also in main menu

Thoughts?

This gets tricky because then we have an extra long menu again. I think we could maybe bump Gift Guide into the "More" - not ideal, but I think that's the only one we can push off the menu.

**Comment by budparr** [comment]
Yeah, we have to remove something to add something from the menu.

**Comment by shuchibooksmith** [comment]
Yea looking at the menu again, gift guide is the only thing that can be bumped.

**Comment by budparr** [comment]
what shop link do you want?

**Comment by budparr** [comment]
I've been out at a meeting today, but I'll do this as soon as I get to the office - about one hour.

**Comment by shuchibooksmith** [comment]
not to worry, thanks! 
and this link
http://www.brooklinebooksmith-shop.com/

**Comment by budparr** [comment]
Have a look at this, @shuchibooksmith @zchyde : 
http://brookline-151203-1549.surge.sh/

**Comment by shuchibooksmith** [comment]
-The Shop Online in the bar menu is great!! But Giftsmith *has* to stay in the Main Menu. Can you put the Holiday Gift Guide into the drop down menu under More?

-Can Gift Cards be in a box above gift guide posts or events listings? similar to how it looks on our ABA homepage. I think it's a little too much over the banner. And the wording is a little off so 
![image](https://cloud.githubusercontent.com/assets/15218891/11574770/90cb4fd4-99db-11e5-92bb-765d1605237d.png)

-The button under the search window is great. Can you just correct the typo? it says 'onlne' instead of "online"

**Comment by budparr** [comment]
Taking out "Holiday Gift Guide" from the menu gave me space to add giftcards to the menu. 
let me know what you think:
http://brookline-151203-1653.surge.sh/

I have to go pick up my kids, so will be out of touch for just a bit.

**Comment by shuchibooksmith** [comment]
only just saw this sorry about the delay!!! 
it looks good, thanks! i think its really time to let the dust settle, but main holiday shopping concerns seem to be addressed. 
i'm not in until 2:30 tomorrow, and zoe is off. email me at my gmail before then if you need me though!

**Comment by budparr** [comment]
Okay. I'll push out that change and get the events up.
