### ISSUE TITLE
Add Navigation Tabs at the Top Of Kids Gift Guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#59]
Would it be possible to add some tabs at the very top of the kids gift guide that will jump to that particular section? 
so-
Picture Books   First Chapter Books    Intermediate Fiction   Young Adult   Nonfiction   Graphica   Gifts

Just because this one is so beastly it might help for people who are looking for a specific category.

**Comment by budparr** [comment]
Sure, once we get more content in there, I think it's a good idea.

**Comment by shuchibooksmith** [comment]
We won't be getting more content for the kids blast, so this would be just for the kids blast, to bypass the scrolling that otherwise happens...

**Comment by budparr** [comment]
So is this the same as issue #60 ?

**Comment by shuchibooksmith** [comment]
No, the ages should be within the body, under each header. 
And, if you create a nav bar for the kids gift guide - 
-Picture Books   -First Chapter Books   -Intermediate Fiction  -Young Adult   -Nonfiction   -Graphica -Gifts 
- then the ages would be in parentheses there as well.
