### ISSUE TITLE
Add Ages to Kids Giftsmith Categories

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#60]
This one is coming from the owner 
Picture Books (ages 4-8)
First Chapter Books (ages 5-7)
Intermediate (ages 8-12)
Young Adult (ages 12 and up)
Nonfiction (all ages)
Graphica (ages 6 and up)

**Comment by budparr** [comment]
You mean to the individual blog posts? If so, sounds like a great idea (coming from a parent!). 

p.s. Your indie-bookstore heart would have been warmed if you heard one of my 8 yr olds last weekend, giving me the rundown on each of his favorite bookstores in the city.

**Comment by shuchibooksmith** [comment]
sorry no i meant for the gift guide! underneath the headers for each section.

and that does warm my heart!! :)
