### ISSUE TITLE
Sharpen contrast between background and posts 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#62]
maybe by making background a darker color? or the posts a darker color?

**Comment by budparr** [comment]
do you mean the banner images?

**Comment by shuchibooksmith** [comment]
no - the banners look great! - i mean the white space underneath need to be contrasted with the blog items/events listings a little more clearly.

**Comment by budparr** [comment]
just to clarify
<img width="480" alt="skitch" src="https://cloud.githubusercontent.com/assets/115347/11515070/e816b5f0-9849-11e5-865f-de0b1d15a76a.png">

**Comment by shuchibooksmith** [comment]
yes, exactly. 
just so that it's more obviously different items. 
but if you think it looks better as is we can leave it too...

**Comment by budparr** [comment]
We can leave this open for the moment (the whole dust-settling thing). It's a fair criticism. I've created less contrast there because we have a lot of images — trying to reduce the visual noise, which increasing that will add to.

**Comment by budparr** [comment]
I'll also made the background a tad bit darker and made the borders around posts a tad bit more prominent. I'm going to close this for now and we can address later if need-be.

**Comment by shuchibooksmith** [comment]
OH this looks great! Thanks.
