### ISSUE TITLE
Upload Remaining Content for Cooking Gift Guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#63]
![stone 1](https://cloud.githubusercontent.com/assets/15218891/11515192/9d93ab7c-984a-11e5-82db-1c6a25819659.jpeg)
![inapinch 1](https://cloud.githubusercontent.com/assets/15218891/11515195/9d9736fc-984a-11e5-9494-9ee33e0d47a1.jpeg)
![whipit 1](https://cloud.githubusercontent.com/assets/15218891/11515191/9d9394a2-984a-11e5-8cb4-ab6827544785.jpeg)
![localboards](https://cloud.githubusercontent.com/assets/15218891/11515194/9d94a220-984a-11e5-95fb-2d3445395602.jpeg)
![pop](https://cloud.githubusercontent.com/assets/15218891/11515196/9d9777de-984a-11e5-992f-9cc7d7e572df.jpeg)
![spoons](https://cloud.githubusercontent.com/assets/15218891/11515193/9d9483f8-984a-11e5-9d48-7f08674ec519.jpeg)

*Bar Boards with Local Flair $19.95*
No kitchen prep surface would be complete without a little local pride, and these bar cutting boards remind us that home is where the heart is this holiday season. Custom made for the Giftsmith by J.K. Adams Co., each board features either an "Entering Brookline" or "Entering Boston" insignia, or the latitude/longitude of our fine town, engraved at the end.

*Whip It Good! Twisted Towels $12*
This mischievous bunch of dishtowels sums up the sardonic cook's response to the ceaseless toil that comes at this magical time of year. Each towel is made in the USA and features a cheeky kitchen phrase or pun ("I have mixed drinks about feelings" might be our favorite).

*In a Pinch Bowl! $4.95*
Master your favorite holiday recipes with a little help from our colorful collection of mini prep bowls. In a pinch, these liven up a party spread by doubling as dishes for nuts, dips or condiments.

*Rockin' Utensils $8.95-$16.95*
"Don't play with your food" does not apply to these rebellious utensils. You'll be amped up to use the Drum Stick Spoons and Guitar Flipper while rocking around the kitchen this holiday season.

*Pop Popcorn Maker $22*
The Lekue popcorn maker uses steam for a healthier version of your favorite movie treat. The silicone bowl is BPA-free and includes a book of recipes inspired by famous films to try - or use as inspiration for your own popcorn concoction!

**Comment by shuchibooksmith** [comment]
@budparr as far as priority level goes, the cooking email blast is scheduled to go out tomorrow at 12:30pm, so the cooking gift guide should be available on the website before then.

**Comment by budparr** [comment]
Okay. tick-tock tick tock! (note to self, show @zchyde how to do this stuff!).
