### ISSUE TITLE
Add credit line to Line's Banner

### ISSUE THREAD

**Issue by zchyde** [sonnetmedia/brooklinebooksmith.com#66]
the words "artwork by Line Olsson" have to be added to the gift guide banner itself or somewhere around the banner. I can do it in Photoshop if need be.

**Comment by budparr** [comment]
I added it. It will look like this page: http://www.brooklinebooksmith.com/giftsmith/ (image credit: Liz Linder),
but of course, that's at the bottom of the page. Should we move it up higher? Perhaps on the right-hand-side of the page.

**Comment by zchyde** [comment]
Yeah, that sounds good
