### ISSUE TITLE
Edit Cooking Gift Guide - Gift Items

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#69]
Make the headers and price for each gift item bold, and on a separate line from the description

**Comment by budparr** [comment]
you have prices for each item?

**Comment by shuchibooksmith** [comment]
no the general price. 
right now it looks like this:
Bar Boards with Local Flair $19.95No kitchen prep surface would be complete without a little local pride, and these bar cutting boards remind us that home is where the heart is this holiday season. Custom made for the Giftsmith by J.K. Adams Co., each board features either an “Entering Brookline” or “Entering Boston” insignia, or the latitude/longitude of our fine town, engraved at the end.

and instead i want it to look like this
Bar Boards with Local Flair $19.95 <---in bold
No kitchen prep surface would be complete without a little local pride, and these bar cutting boards remind us that home is where the heart is this holiday season. Custom made for the Giftsmith by J.K. Adams Co., each board features either an “Entering Brookline” or “Entering Boston” insignia, or the latitude/longitude of our fine town, engraved at the end.

**Comment by shuchibooksmith** [comment]
(this is following the style/format of the gifts in the kids gift guide)

**Comment by budparr** [comment]
duh, I was thinking the books, not the gift items. no prob
