### ISSUE TITLE
Privacy Policy question

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#70]
Richard brought this up, I hadn't looked through it yet. Wondering where you get the copy for the privacy policy?

His main concern/in his words-
"We will collect and use of personal information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law."
 
Anyone run this stuff past a lawyer?  Apart from the problem inherent in "we will collect and use of", this says we'll collect your personal information and do whatever we want with it unless you tell us we can... ???

**Comment by budparr** [comment]
Nah, that's just boilerplate from a site called docracy, that I put in because I know you're busy. You're responsible for you own content, ultimately. I'm happy to help you with it, or refer you to a media lawyer, but writing a legal document is outside of my abilities :).

**Comment by shuchibooksmith** [comment]
OH great, okay thanks!!

**Comment by budparr** [comment]
I can't find one from the old site, but if you have it, I'll drop it in for you.

**Comment by budparr** [comment]
Can't find one on the store. You really should have one there, that's where you have paying customers who are logging in.
