### ISSUE TITLE
Add ticket link for Michael Ian Black

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#71]
Customers can purchase tickets here - 
http://www.brooklinebooksmith-shop.com/event/michael-ian-black-navel-gazing-author-event

**Comment by budparr** [comment]
Added. It's kinda big, let me know what you think.

**Comment by shuchibooksmith** [comment]
I think that's okay for now, we'll revisit on Monday if we need to. Have a great weekend!
