### ISSUE TITLE
New Weekly Bestsellers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#73]
HC
1) Best Advice in Six Words -  9781250067012
2) Petty - 9780805099683
3) Between the World and Me (already there)
4) Unfaithful Music and Disappearing Ink (already there)
5) Notorious RBG - 9780062415837
6) Lake House - 9781451649321

Pbk
1) Mindfulness Coloring Book (already there)
2) Boston Girl (already there) 
3) Gratitude - 9780451492937
4) Brave Enough - 9781101946909
5)  Brooklyn - 9781439148952
6) Station 11 (already there)
7) Lobster Is the Best Medicine -  9780762458684

**Comment by budparr** [comment]
I should have these up very soon.
