### ISSUE TITLE
Add Travel & Nature Gift Guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#79]
This is going live tomorrow at noon. I'm so sorry to send this so late!!!

Cabin Porn: Inspiration for Your Quiet Place Somewhere 
by Zach Klein and Steven Leckart, photography by Noah Kalina (9780316378215)
It's exactly what it is. It's cabin porn. Every conceivable style, location, and reason for being is in these pages. There are converted silos, treehouses, modernist shapes extending as if by magic out over the stream, or what appears to be a pile of ancient farm equipment and peeling plywood in the most overgrown corner of the field. Let's face it, most of us who dream of our own little cabin in the woods will never build one. That's what this book is for. 

The Cell: A Visual Tour of the Building Block of Life (9780226224183)
by Jack Challoner 
The old descriptive phrase 'building blocks of life' brings to mind homogeneous cookie cutter entities, but that image could not be less indicative of what is happening inside those cell walls. Jack Challoner has assembled the best science, the clearest information graphics, and the most jaw-dropping hi-res images of the life in, on, and around cells of every sort. A highly engaging read for any cellular spelunkers, whether they be novice or advanced. 

Bird Love (9781419718458)
by Leila Jeffreys
Leila Jeffreys' exquisitely detailed portraits capture the virility and individuality of dozens of species of bird. We rarely see them but from a distance or behind the bars of a cage, yet here they stand still for the camera, allowing us access to more of their inner nature than we ever expected to find. Look at that owl on the cover. Fierce, lighter than air, demanding. Wait until you see the parakeets: in Jeffreys' eye they are more intimidating than a hungry bear. 

Thunder & Lightning: Weather Past, Present, Future (9780812993172)
by Lauren Redniss
Lauren Redniss respects no precedent. In Radioactive, the world was introduced to Marie Curie in an expressive, enigmatic blend of art and biography. Thunder & Lightning blazes with an even hotter creative fire. Here is an exhilarating passage to the heart of the human experience of weather; its effects on our history, our stories, our body and soul. Drawing from first person accounts, news reports and her unfairly rich imagination, Lauren Redniss has, once again, redefined what a book can be. 

Atlas of Cursed Places: A Travel Guide to Dangerous and Frightful Destinations (9781631910005)
by Olivier Le Carrer 
Zapadnaya Litsa, northwest Russia, where nearly half of Russia's retired nuclear submarines lie rusting, holding as much radioactive fuel as thirty Chernobyls. Aokigahara forest, at the foot of Mount Fuji, where local volunteers organize an annual search, hunting among the trees for the bodies of the estimated one hundred people who come there each year to commit suicide. Cumbre Vieja, the Canary Island volcano whose eruption would likely emit a ring of tsunamis that would make a Hollywood special effects team give up on even trying. Detailing all of these places and a few dozen more, The Atlas of Cursed Places is the most deliciously miserable book of the year. 

Thing Explainer: Complicated Stuff in Simple Words (9780544668256)
by Randall Munroe
Signed copies available!
In 2006, Randall Munroe saw the writing on the wall. The political atmosphere was thick with science-denial, and telling someone that you were a NASA roboticist just didn't impress anymore. Like so many others, he decided that it was time to make the leap into web comics. Nine years into this new career, Munroe has released his second hard-science-for-the-layperson book, and it's simply amazing. You want to know exactly why we built the Large Hadron Collider? Read the incredibly detailed "Big Tiny Thing Hitter" page, where Munroe gracefully explains the most complex machine in history - by likening it to tossing a car overboard to see if the splash brings up any of the really big fish which you hypothesize may be pushing your boat through what could be an ocean of beer. Somehow Randall Munroe makes it all make sense. 

The Dogist: Photographic Encounters with 1,000 Dogs (9781579656713)
by Elias Weiss Friedman
You can tell as you turn the pages, this isn't just another catalog of endearing dogs. There is something passing between the photographer and his subjects. Elias Weiss Friedman goes right for the eyes; if you know anything at all about dogs, you know that the eyes are where its at. They are the prehistoric bridge between our species, and in this collection of portraits of a thousand dogs, Friedman catches the light of a thousand different souls. A joyful, thoughtful book that is guaranteed to strike a chord.

Booksellers Also Recommend

Jutaku Japanese Houses- 9780714869629
Stories in the Stars - 9780145128137
Humans of New York: Stories - 9781250058904
Skylines: A Journey -9781781314517
Lonely Planet's Ultimate Travel Our List- 9781760342777

From the Giftsmith:

Flour Sack Towel $10.95
Give presents you can feel good about giving this season, with eco-friendly, artistically crafted, and socially responsible gifts.  The flour sack dish towels feature hand screened animals on 100% natural cotton. Beautiful and versatile, try using one to wrap up an eco-friendly candle or handmade lotion.

Wooden Frames $26-$29.95
Made in New England and distressed by hand, these painted wooden frames will compliment any style or decor. Add a personal touch by framing a family portrait, letter, drawing or a post card for a gift that will be cherished for years to come.

Globe $14.95
Need something for that armchair traveler? The Crossing Continents 4" standing globe  offers a worldly accent on a bookshelf next to your favorite travel literature.

Journals $10.99-$16.95, Travel Kit $12
Check your list and avoid hassles with our travel journals this season. Itineraries, references, notes and even restaurant reviews are made simple with a handy guide to help you organize your travels. And with the Inflight Comfort Kit you'll be able to maximize your travel time so that you arrive at your destination relaxed, refreshed, and ready to explore.

Travel Pillows $18.95
Whether you're traveling by train, plane or automobiles this season, you're guaranteed to catch some zzz's using a Birch or Log Pillow and Head Rest. The microbead fill offers a comfortable cradle for your head and neck. The pillows are great for home decor too!

Flask $29.95, Shaving Kit $12.95, On-The-Go Kit $14.95
No trips to the haberdasher are needed when you have access to these necessary grooming tools. The On-The-Go Men's Kit comes with collar stays, a shoehorn, and nail clippers and doubles as a shoebrush, and the shaving kit includes moisture, soap, and balm in a soft sandalwood scent. And don't forget to grab your stainless steel vacuum flask before you kick off your adventure.

(photos coming)

**Comment by budparr** [comment]
I need ISBNs too!

**Comment by shuchibooksmith** [comment]
oh yes, i'll revise above!

**Comment by shuchibooksmith** [comment]
![shave](https://cloud.githubusercontent.com/assets/15218891/11672544/99c5d070-9ddf-11e5-8bc0-ab75db114fb0.jpg)
![dishtowels](https://cloud.githubusercontent.com/assets/15218891/11672545/99c69f6e-9ddf-11e5-814b-d049469fb04b.jpg)
![logpillow](https://cloud.githubusercontent.com/assets/15218891/11672549/99c7a01c-9ddf-11e5-90b3-0f3bbaba1201.jpg)
![globes](https://cloud.githubusercontent.com/assets/15218891/11672548/99c7a666-9ddf-11e5-9aba-ade5b370630d.jpg)
![frames](https://cloud.githubusercontent.com/assets/15218891/11672547/99c759c2-9ddf-11e5-8827-354b9cf4d8e3.jpg)

**Comment by budparr** [comment]
@shuchibooksmith this is ready to go, just let me know when you want me to make it live. FYI, could not find: Stories in the Stars - 9780145128137

@zchyde if you want the images for this for your email they're all at http://images.brooklinebooksmith.com/ISBN.jpg where ISBN is the each book's isbn.

and the gift images are 
http://images.brooklinebooksmith.com/2015-gift-guide-travel-flour-sack-towel.jpg
http://images.brooklinebooksmith.com/2015-gift-guide-travel-globe.jpg
http://images.brooklinebooksmith.com/2015-gift-guide-travel-kit.jpg
http://images.brooklinebooksmith.com/2015-gift-guide-travel-travel-pillows.jpg
http://images.brooklinebooksmith.com/2015-gift-guide-travel-wooden-frames.jpg

and this is the image I used for the banner:
http://images.brooklinebooksmith.com/2015-gift-guide-travel-cabin-porn.jpg

**Comment by shuchibooksmith** [comment]
@budparr here's stories in the stars - 978-0091954451
I'm not in today, but you can make it live now if it's all done. Email blast will go out probably mid-day.

**Comment by budparr** [comment]
Can you point me to the page on the shop site with the stories book?

**Comment by shuchibooksmith** [comment]
Yes! http://www.brooklinebooksmith-shop.com/book/9780143128137

**Comment by budparr** [comment]
this is set. One other thing. There was no picture for "journals" in the gifts.

**Comment by budparr** [comment]
http://www.brooklinebooksmith.com/holiday-gift-guide/2015/12/08/holiday-gift-guide-travel-and-nature/

**Comment by shuchibooksmith** [comment]
![inflight](https://cloud.githubusercontent.com/assets/15218891/11726504/f5e2b47c-9f4c-11e5-9af8-6293add973aa.jpg)
