### ISSUE TITLE
Add January event

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#80]
Tuesday, January 12th at 7:00pm
FICTION
Janice Y. K. Lee
The Expatriates

Janice Y. K. Lee’s blockbuster hit debut The Piano Teacher was called “immensely satisfying” by People; “intensely readable” by O, The Oprah Magazine; and “a rare and exquisite story” by Elizabeth Gilbert. Now, in her long-awaited new novel, Lee explores with devastating poignancy the emotions, identities, and relationships of three very different American women living in the same small expat community in Hong Kong.

**Comment by shuchibooksmith** [comment]
Hey Bud, the cover is wrong, here is the right one - 9780525429470

**Comment by budparr** [comment]
Oops! I put the wrong ISBN in. Fixed now.
