### ISSUE TITLE
Add New January events

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#81]
Tuesday, January 26th at 7:00pm
HISTORY/BIOGRAPHY
T.J. Stiles
Custer’s Trials: A Life on the Frontier of a New America - 9780307592644
In this magisterial biography, Pulitzer Prize and National Book Award winner T. J. Stiles paints a portrait of Gen. George Custer both deeply personal and sweeping in scope, proving how much of Custer’s legacy has been ignored. In the Civil War, the West, and many areas overlooked in previous biographies, Custer helped to create modern America, but he could never adapt to it. Custer’s Trials casts surprising new light on a near-mythic American figure, a man both widely known and little understood.

 
Wednesday, January 27th at 7:00pm
SCIENCE FICTION/FANTASY
Charlie Jane Anders
All The Birds in the Sky - 9780765379948
From the editor-in-chief of io9.com comes a stunning novel about the end of the world--and the beginning of our future. Childhood friends Patricia Delfine and Laurence Armstead didn't expect 
to see each other again. After all, the development of magical powers and the invention of a time machine could hardly fail to alarm one's peers and families. But now they're both adults and the planet is falling apart around them. Little do they realize that something bigger than either of them is 
determined to bring them together--to either save the world, or plunge it into a new dark ages.

Thursday, January 28th at 7:00pm
FICTION
Suzanne Berne
The Dogs of Littlefield - 9781476794242
A “brilliantly done” (Sunday Times) comedy of manners that explores the unease behind the manicured lawns of suburban America from the Orange Prize–winning author of A Crime in the Neighborhood. Littlefield, Massachusetts, named one of the Ten Best Places to Live in America, is proud of its fine schools and charming village center. Yet no sooner has sociologist Dr. Clarice Watkins arrived to study the elements of “good quality of life” than someone begins poisoning the 
town’s dogs. Are the poisonings in protest to an off-leash proposal for Baldwin Park—the subject of much town debate—or the sign of a far deeper disorder? Certainly these types of things don’t happen in Littlefield.

**Comment by budparr** [comment]
Do you have ISBN's on the books? If not, no big deal, just don't want to pick the wrong one.

**Comment by shuchibooksmith** [comment]
oh sure, i'll add them to the listing

**Comment by budparr** [comment]
These are posted. Note that sometimes I close an issue without comment (not to be unfriendly!) but just so you know that means it's done, but if there's something amiss or needs further discussion, you can always re-open the issue. Still working on those damn blog posts, btw.
