### ISSUE TITLE
New Weekly Bestsellers 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#82]
Hardcovers-
1) Between the World and Me (already there)
2) Gratitude - 9780451492937 (pull from paperback list)
3) Thing Explainer (already there)
4) Notorious RBG -(already there)
5) Drawing Blood -  9780062323644
6) Unfaithful Music & Disappearing Ink (already there)

Paperback 
1) Mindfulness Coloring Book (already there)
2) Lobster is the Best Medicine (already there) 
3) Boston Girl (already there)
4) Brooklyn (already there)
5) Martian - 9780553418026
6) Betrayal - 9780316271530
7) Dog Songs - 9780143125839

**Comment by budparr** [comment]
Hi @shuchibooksmith - these are set. Nearly done with importing old blog posts (all the way back to 2007!).

**Comment by shuchibooksmith** [comment]
@budparr HOORAY! That must have been a beast to do, thank you!!
