### ISSUE TITLE
Kids Bestsellers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#83]
Can we put a carousel of bestsellers similar to the homepage on the kidsmith page? 
Here is the list for this week-
The Harry Potter Coloring Book : 9781338029994
Harry Potter and the Sorcerer's Stone Ilustrated Edition: 9780545790352
I Really Like Slop: 9781484722626
Home: 9780763665296
Waiting is Not Easy: 9781423199571
Julia's House for Lost Creatures: 9781596438668
The Day the Crayon's Came Home: 9780399172755
Diary of a Wimpy Kid: Old School: 9781419717017
The Snowy Day: 9780670867332
Make Way for Ducklings: 9780140564341

**Comment by budparr** [comment]
Yes, no problem. I'll do this right after I finish the posts.

**Comment by budparr** [comment]
Hi @shuchibooksmith I'm going to put this up right when I get home (in case there are issues, don't want to do it just before I leave). FYI - I structured the page like the home page to accommodate all the elements. I think I'll change that, partly for variety and wayfinding and I think people are more apt to scroll on the home page and less so on interior pages. So, stay tuned for that a bit later.

**Comment by budparr** [comment]
@shuchibooksmith This is up. http://www.brooklinebooksmith.com/kidsmith/
