### ISSUE TITLE
Events on homepage

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#84]
I've had a few people mention to me that they think the events side bar on the homepage needs a header. What do you think @budparr and @zchyde ?

**Comment by budparr** [comment]
I'll think about this. I understand the request, though in my minimalist opinion, I think that showing date-based content does the job. Have you had customers mention this?

**Comment by budparr** [comment]
Note how I've put headers above the columns on the Kidsmith page. This might be a model for the home page. Also note that it needs to be balanced and logical to work very well (i.e. I don't think it would work well with only one column labeled, but do both need a label?). So I'm going to think about this for a few days and appreciate your feedback, @shuchibooksmith and @zchyde 
http://www.brooklinebooksmith.com/kidsmith/

**Comment by shuchibooksmith** [comment]
@budparr for some reason my notifications don't always show up, so i see this one has been languishing a bit. 
i like how the labels look on the kidsmith page, but the phrase "blog posts" is giving me pause for the homepage. i'm not quite sure why though. maybe im worried that "blog" might deter people? it indicates to readers and visitors that reading the post might take more time instead of something they could just glance at? i don't know if that makes sense, but my instinct is to keep the blog page for blog posts and the homepage free of that label. thoughts?

**Comment by budparr** [comment]
Good observation. The word "blog" has always been problematic. Could just be "Latest Updates."

**Comment by shuchibooksmith** [comment]
Could be. I'd rather leave it as is for now, and let's see if anyone else makes a comment about needing headers for events on the homepage.
