### ISSUE TITLE
Art & Literature Gift Guide

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#85]
Leap Before You Look: Black Mountain College 1933-1957 by Helen Molesworth, with Ruth Erickson 
9780300211917
Twenty-four years was all the time it was given, but the influence of Black Mountain College endures all the way to the present. From 1933-1957, the rural college founded by John Rice ("We must realize that the world as it is isn't worth saving; it must be made over.") operated self-sufficiently, with men and women sharing equally the joys and toils of building, harvesting, and, of course, providing world-class instruction to a crop of young artists in every creative field imaginable. This book, companion to the ICA exhibit, is the closest thing to being a student in that briefly-realized-utopia, Black Mountain College.

Mathematics & Art: A Cultural History by Lynn Gamwell, with a foreword by Neil deGrasse Tyson
9780691165288
If you think about it in terms of Smartphones and Big Data, it seems a relatively new phenomenon, the way that zeroes and ones are woven into every facet of our lives. But really, the language of mathematics has always been with us, waiting to be deciphered bit by bit, helping us in our quest to better know our world and ourselves. Lynn Gamwell's monumental study illuminates the people and ideas who have pushed at the boundaries of mathematics and art, and demonstrates how, when they intersect, masterpieces come into being.

Plotted: A Literary Atlas by Andrew DeGraff and Daniel Harmon 
9781936976867
Andrew DeGraff offers a master-class in information design in Plotted: A Literary Atlas. He charts the path of each of Hamlet’s characters through the cut-away halls and corridors of Elsinore Castle; distills into one iconic image the tight orbit and existential angst of Waiting for Godot; winds page after page down the lazy Mississippi with Huck Finn; and zooms out to follow the claustrophobic car ride, the worst family road trip ever, in Flannery O'Connor's A Good Man Is Hard To Find.

Have a Little Pun by Frida Clements
9781452114160
Pepper your holiday cheer with a stocking full of groans this year by giving someone on your list Frida Clement's Have a Little Pun. "NICE MUSSELS" compliments the pile of mussels, but the trio of yaks don't hear because "YAK YAK YAK.” I agree with the sheep, "EWE CRAZY" if you don't buy this book.

101 Artists to Listen to Before You Die by Ricardo Cavolo 
9781910620007
Shrewd editorial decision, keeping that number down low. Usually these before-you-die lists clock out at 1,001, making it an impossibility to actually complete the job in one lifetime. Bonus: everyone is going to have a legit beef with the list, because it inevitably leaves off one or more of your favorite artists! Well done, Ricardo Cavolo, your book (the brilliantly illustrated diary of his musical awakening, actually) is both debate-worthy and actionable.

Presenting Shakespeare: 1,100 Posters from Around the World by Mirko Ilic and Steven Heller, preface by Julie Taymor 
9781616892920
Shakespeare's themes are universal and timeless - they lend themselves to being reworked into different eras and locations. And if such license is given to the director, the same must be extended to the designer...of the show's poster. Each of the plays' posters are grouped together, highlighting the dramatic variety of approaches taken by designers representing 56 countries, from the nineteenth century to the present day.

The Annotated Alice: 150th Anniversary Deluxe Edition by Lewis Carroll, edited by Martin Gardner and Mark Burnstein, illustrated by John Tenniel
978-0393245431
Even the most knowledgeable devotees of Alice's adventures will find innumerable gems in the columns of The Annotated Alice. The roots of Lewis Carroll's creation are at times even more fascinating than the book itself. This 150th anniversary edition - with its copious side notes and illustrations dating from the original version to the present day - is a fantastically twisting and turning rabbit hole in and of itself.

-Staff Also Recommends
9781631910012
9783836532297
9780871404565
9781784781767
9780547485850
9781631490712
9780762458684
9780805212655

**Comment by shuchibooksmith** [comment]
Travel Easel Set $35.50, Milan 50 ct Set $22.95, Stabilo Set $22.95, Farber-Castell Connector Pen Set $20.95

Stimulate the creative senses this holiday! The Portable Art Studio makes getting started easy, with a variety of artist materials and a light, transportable design – perfect for sketching in the park, painting by the seaside, or setting up wherever inspiration strikes. For more seasoned artists we offer a selection of fine pen and marker sets from Stabilo and Faber-Castell. Pair them with any of our adult coloring books for the gift of meditative beauty.


 

Puzzles $17.95

Puzzles and games are fun ways to bring the whole family together during the holidays. The collage Art and Literature themed jigsaw puzzles combine bold colors and nostalgic images that everyone can enjoy. The White Mtn. Puzzle Co. proudly makes each puzzle in America out of recycled materials.


 

T-Shirts $24-$28, Scarf $24, Mug $12.95, Socks $10.95

Gifts that keep on giving all through the year! The Out of Print Co. celebrates classic titles and iconic cover art with their line of apparel and accessories. Our personal favorite? The t-shirts - each one is soft, comfy, and designed to look like a well-worn book (no pun intended). For each product sold, Out of Print donates one book through their partnership with Books For Africa.


 

Mugs $14.95

From the Unemployed Philosophers Guild comes a line of smart, funny and even educational ceramic mugs for the snarky literary nerd on your list. These are perfect for the educator, student or co-worker who enjoys books, art history, or learning how to draw as much as they love a hot cup o' joe.


 

Saints Candle $12.95

These Secular Saint candles keep a flame of devotion burning for your favorite guardian of the arts - and shield you from bohemian miseries at the same time! Give a nod to honored virtuosos like William Shakespeare, the patron saint of star-crossed lovers, and Jane Austen, our lady of poor relations. Each candle includes a tailored hymn to inspire and enlighten.


 

Knee High Socks $8.95-$10.95

Inspired by classic and contemporary artists, the "Art Collection" of legwear from the Giftsmith brings sock drawers to new heights.Gift your loved one with a masterpiece by the likes of Frida Kahlo or Vincent van Gogh while keeping their calves warm this winter.


 

Library Travel Tin Candles $8.00

Library candles pair cherished authors like Austen, Dickens, Poe and more with signature fragrances inspired by their work. Each 2-wick candle is composed of hand-poured soy wax in a travel copper tin and makes any room feel like the cozy pages of a favorite book - a perfect stocking stuffer for a lover of the classics.


 

"There is nothing like staying at home for real comfort." - Jane Austen

**Comment by shuchibooksmith** [comment]
![tshirts](https://cloud.githubusercontent.com/assets/15218891/11826730/139a185a-a355-11e5-81b7-fd23c8ba0de4.jpeg)
![socks](https://cloud.githubusercontent.com/assets/15218891/11826732/14c47d42-a355-11e5-8cab-802d98c83738.jpeg)
![puzzles](https://cloud.githubusercontent.com/assets/15218891/11826733/15d19742-a355-11e5-9861-258816e77fe9.jpeg)
![mugs](https://cloud.githubusercontent.com/assets/15218891/11826737/19d5c0de-a355-11e5-89ba-de630734c048.jpeg)
![saintcandle](https://cloud.githubusercontent.com/assets/15218891/11826739/1b6ade70-a355-11e5-966c-09b565d08e6e.jpeg)
![libcandle](https://cloud.githubusercontent.com/assets/15218891/11826741/1e47cf90-a355-11e5-9fe4-c909b7cb3e0a.jpeg)
![artsupplies](https://cloud.githubusercontent.com/assets/15218891/11826743/2006bf3a-a355-11e5-8ba3-0ba4395656fe.jpeg)

**Comment by shuchibooksmith** [comment]
Zoe is setting this one to go live tomorrow at noon! I'm sorry I keep sending it so late. If you need more time let her know and she can schedule it a little bit later.

**Comment by budparr** [comment]
No worries!

**Comment by budparr** [comment]
@shuchibooksmith @zchyde http://www.brooklinebooksmith.com/holiday-gift-guide/2015/12/16/holiday-gift-guide-art-literature/
