### ISSUE TITLE
Mindfulness & Home gift blast 

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#88]
Here's the final gift blast!! Zoe is sending out the email tomorrow-

Inside the Now: Meditations on Time by Thich Nhat Hanh
978-1937006792
Perhaps Thich Nhat Hanh's most lyrical book, Inside the Now is an artfully bound vessel filled with the wisdom earned by Hanh through countless hours of meditation. Inspired by the great 13th century Zen master Dogen's text Being Time, this book offers moments of laser-like focus and immeasurable space to the modern reader, equally suited to those who have logged many years on the cushion, or those who are just searching for a second of equanimity between tweets.

Lost Ocean: An Inky Adventure and Coloring Book by Johanna Basford
978-0143108993
Johanna Basford's newest coloring book invites us to take a plunge into the swirling ocean deep, where the only limit to our creativity is how economical we can be with a pencil sharpener. (we stock plenty of those, too.) Each turn of the page provides a whole new approach to coloring; her elegant line drawings might sprawl across the spread in a skyline of shells, or they might rise in a single strand of seahorses through the empty expanse. There is so much room to grow on these pages, just let go and stay inside the lines.

Gratitude by Oliver Sacks
978-0451492937
After a lifetime of focusing on the intimate experiences of people in the most unusual and misunderstood regions of illness, beloved author and physician Oliver Sacks was faced with the one condition that we all eventually share. What to do with the knowledge that only a handful of months remained? Sacks sat down at his writing desk and penned four final essays in which he offers a wise and graceful message of what it means to live, and how we may come to accept death. Doctor, heal thyself, indeed.

The Kinfolk Home: Interiors for Slow Living by Nathan Williams 
978-1579656652
The emerging ethos of slow living, as illustrated by Kinfolk magazine, is embodied in thirty-five residences across five continents. Think of it as minimalism with a soft touch: living spaces are cleared of the non-essential, allowing the most necessary surfaces and tools for work, art and life to come into their own. Walking into The Kinfolk Home somehow feels like stepping outside for a cool breath of fresh air.

The New Bohemians: Cool and Collected Homes by Justina Blakeney 
978-1617691515
The New Bohemians will spark a chain reaction of creative redecorating in your home, we guarantee it. Scrub away the barriers between work and play; erase the distinction between living room and dining room; turn your home into an expression of your creative aspirations. Every page in this book is an inspiration, a carnival of color, texture, and playfully reimagined living space.

Spark Joy: An Illustrated Master Class on the Art of Organizing and Tidying Up by Marie Kondo
Marie Kondo's trademark motto of "spark joy" might not have been the way her siblings would have described her actions as a child, since she regularly raided their bedrooms to spirit away little-used toys and clothes, like a mini Zen Grinch in the night. But age has brought wisdom, and the world is ready to receive it, as evidenced by the runaway success of her first book, The Life-Changing Magic of Tidying Up. Let Kondo help you give the gift of clarity, awareness and a fresh start to someone you love. And watch out for her new book, Spark Joy, coming early in 2016. 

Booksellers Also Recommend
Rethink - 9781452139197
One Year Wiser - 9781910593011
Felicity - 9781594206764
HT Split Wood Shuck An Oyster & Master - 9781616893996

GIFTSMITH

MINDFULNESS

Gratitude Journal $14.95, 5-Year Journal $16.99

Amid the chaos of the holidays it's easy to lose time for appreciation and reflection. Our Gratitude Journals give the chance to pause and recall what brings us joy - even when we feel overwhelmed by our shopping lists - while the Five-Year Journal provides a moment for one entry a day, one thought a day, one day at a time.

 

Artisan Dish $14.95 Wrapped Soap $8.95

Sometimes our schedules leave us too harried to stop, breathe, and remember the joys of the season. These artisan dishes remind us of the beauty in even our smallest instruments. They are microwave and dishwasher safe for use with food and easy cleaning. Pair any dish with a handcrafted bar of soap for a nice gift set.

 

Charm Bracelets $24.95

Our 24k gold-plated Gift Charm Bracelets are a simple and thoughtful gift for a loved one this holiday. Inspirational reminders like "shoot for the moon", "the key to happiness" and "we are all made of stars" are just a few of the charming designs from this collection.

 

Yoga Mug $14.95, Eco Candle $17.95 Matches $3.95

Zen for the holidays! Do your mind, body and soul some good during the dark winter. The How-To Yoga Mug comes equipped with a lotus yoga mat coaster and illustrates poses you can practice while burning your favorite calming candle. So don't just sip there, do some yoga!

 

HOME

Blankets $24.95

Wrap yourself in comfort this holiday with the ultra soft and warm Fuwa Fleece Blanket. Generously sized and multi-purpose, the blankets roll up with ease for travel and are available in a variety of  designs (hand wash and hang dry recommended).

 

Kobito Room Shoes $24.95

The Kobito Room Shoes are crafted from a wool blend which keeps them cushy and cozy. Slip on the form-fitting shoes in the morning before breakfast and then again after a long night at the office holiday party. With a variety of colors and size options there's a pair for everyone in the family.

**Comment by budparr** [comment]
Got it. You're posting images for the gifts?

**Comment by shuchibooksmith** [comment]
![5yrjournal 1](https://cloud.githubusercontent.com/assets/15218891/11943393/9c1bc5ec-a80b-11e5-8f79-e5103b2564fb.jpeg)
![artdishes](https://cloud.githubusercontent.com/assets/15218891/11943392/9c1bcf10-a80b-11e5-9df2-cd54047ebadf.jpeg)
![cardjewels](https://cloud.githubusercontent.com/assets/15218891/11943395/9c2069bc-a80b-11e5-9f88-9f00254db80e.jpeg)
![fleeceblk](https://cloud.githubusercontent.com/assets/15218891/11943394/9c1f2372-a80b-11e5-84f9-bcd38d6d526e.jpeg)
![kobito](https://cloud.githubusercontent.com/assets/15218891/11943396/9c20b93a-a80b-11e5-84f3-a2082faba174.jpeg)
![yogacandle](https://cloud.githubusercontent.com/assets/15218891/11943397/9c2321b6-a80b-11e5-93dc-c3275cc1a83e.jpeg)

**Comment by budparr** [comment]
Got it. I'll have them up in the morning, if that's okay.

**Comment by shuchibooksmith** [comment]
thats perfect! Thanks!
