### ISSUE TITLE
Kids bestsellers

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#89]
Snowy Day : 9780670867332
Make Way for Ducklings: 9780140564341
Harry Potter the Coloring Book: 9781338029994
I Really Like Slop: 9781484722626
The Very Hungry Caterpillar: 9780399226908
The Little Blue Truck: 9780544568037
The Day the Crayons Came Home: 9780399172755
Diary of a Wimpy Kid Old School: 9781419717017
The Sword of Summer: 9781423160915
My Crazy Inventions Sketchbook: 9781780676111

**Comment by budparr** [comment]
I should have these up within an hour.
