### ISSUE TITLE
Top 25 of 2015

### ISSUE THREAD

**Issue by shuchibooksmith** [sonnetmedia/brooklinebooksmith.com#93]
We have this in a display in the store and we update it every six weeks or so. Thoughts on finding a place for it on the website? Maybe we could combine the weekly bestsellers carousel (so hardcovers and paperbacks in one) and the best of the year could be a carousel underneath?

**Comment by budparr** [comment]
I think it would get the most attention as a blog post.

**Comment by shuchibooksmith** [comment]
Okay! I think just a post with all of the book covers would be great. I'll include the list with ISBNs here, but it can go up next week.

**Comment by budparr** [comment]
Okay. I was just re-reading your post. This is the top of 2015, but you update it every 6 weeks? Not sure I understand that. Initially I thought it was a static thing.

**Comment by shuchibooksmith** [comment]
@budparr UGH i said six weeks i meant SIX MONTHS. sorry. we do a top 25 on july 1st and we make a flier that says top 25 of the year...so far. and then we do a complete top 25 in december. 
still adding ISBNs to this list, but here it is. 
i do think blog post is the way to go.

1) The Life-Changing Magic of Tidying Up: The Japanese Art of Decluttering and Organizing by Marie Kondo - 9781607747307
2) Secret Garden: An Inky Treasure Hunt and Coloring Book by Johanna Basford - 9781780671062
3) All the Light We Cannot See by Anthony Doerr - 9781476746586
4) Between the World and Me by Ta-Nehisi Coates - 9780812993547
5) Why Not Me? by Mindy Kaling
6) The Mindfulness Coloring Book: Anti-Stress Art Therapy for Busy People  by Emma Farrarons
7) The Little Book of Mindfulness: 10 Minutes a Day to Less Stress, More Peace by Patricia Collard
8) My Brilliant Friend: Neapolitan Novels, Book One by Elena Ferrante, translated by Ann Goldestein
9) Enchanted Forest: An Inky Quest & Coloring Book by Johanna Basford
10) Being Mortal: Medicine and What Matters in the End by Atul Gawande
11) The Martian by Andy Weir
12) We Should All Be Feminists by Chimamanda Ngozi Adichie
13) Americanah by Chimamanda Ngozi Adichie
14) Euphoria by Lily King
15) The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics by Daniel James Brown
16) The Girl on the Train by Paula Hawkins 
17) The Examined Life: How We Lose and Find Ourselves by Stephen Grosz
18) Is Everyone Hanging Out Without Me? (And Other Concerns) by Mindy Kaling
19) H is for Hawk by Helen Macdonald
20) Citizen: An American Lyric by Claudia Rankine
21) The Boston Girl by Anita Diamant
22) The Moth edited by Catherine Burns 
23) Everything I Never Told You by Celeste Ng 
24) Wild: From Lost to Found on the Pacific Crest Trail by Cheryl Strayed
25) Bad Feminist: Essays by Roxane Gay

**Comment by budparr** [comment]
I see. Yeah, agree on the blog post way.

**Comment by shuchibooksmith** [comment]
haha sorry. my brain is still working its way back to normal. like i said, no real rush on this it can wait until next week! i'm just trying to catch up on all the things i ignored the last two weeks...

**Comment by budparr** [comment]
I put the post up. Let me know if you're not okay with the way it's presented (i.e. feel free to re-open issue if so). The books are kind of just there, but I think that many books would indeed be too many for the carousel.
